# CPU ID declarations  generated by parsecpuids.py  Apr 16, 2015  15:58:35

# don't modify this file. Make changes to cpuids.txt and regenerate
# CPU names
HOST=0x0	# 
ME=0x0	# 
YOU=0x0	# 
DIRECT=0x0	# 
MAIN_CPU=0x1	# 
MAIN_HOST=0x2	# host ports on cpus
ROUTING_POINTS=0x3	# number of points for routing

# who dictionary
whoDict = {
    'Host': HOST,
    'Me': ME,
    'You': YOU,
    'Direct': DIRECT,
    'Main Cpu': MAIN_CPU,
    'Main Host': MAIN_HOST,
    'Routing Points': ROUTING_POINTS,
	'':0
}