# CPU ID declarations  generated by parsecpuids.py  Sep 28, 2012  16:25:35

# don't modify this file. Make changes to cpuids.txt and regenerate
# CPU names
HOST=0x0	# 
ME=0x0	# 
YOU=0x0	# 
DIRECT=0x0	# 
MAIN_CPU=0x1	# 
DISPLAY_CPU=0x2	# 
SLOTA_CPU=0x3	# 
SLOTB_CPU=0x4	# 
MAIN_HOST=0x5	# host ports on cpus
DISPLAY_HOST=0x6	# 
SLOTA_HOST=0x7	# 
SLOTB_HOST=0x8	# 
ROUTING_POINTS=0x9	# number of points for routing

# who dictionary
whoDict = {
    'Host': HOST,
    'Me': ME,
    'You': YOU,
    'Direct': DIRECT,
    'Main CPU': MAIN_CPU,
    'Display CPU': DISPLAY_CPU,
    'Slota CPU': SLOTA_CPU,
    'Slotb CPU': SLOTB_CPU,
    'Main Host': MAIN_HOST,
    'Display Host': DISPLAY_HOST,
    'Slota Host': SLOTA_HOST,
    'Slotb Host': SLOTB_HOST,
    'Routing Points': ROUTING_POINTS,
	'':0
}