# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sun Mar 29 20:42:46 2015
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1041, 604)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.Controls = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Controls.sizePolicy().hasHeightForWidth())
        self.Controls.setSizePolicy(sizePolicy)
        self.Controls.setMinimumSize(QtCore.QSize(390, 470))
        self.Controls.setMaximumSize(QtCore.QSize(420, 470))
        self.Controls.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Controls.setObjectName(_fromUtf8("Controls"))
        self.Serial = QtGui.QWidget()
        self.Serial.setObjectName(_fromUtf8("Serial"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.Serial)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.Serial)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.SerialPort = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SerialPort.sizePolicy().hasHeightForWidth())
        self.SerialPort.setSizePolicy(sizePolicy)
        self.SerialPort.setObjectName(_fromUtf8("SerialPort"))
        self.SerialPort.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.SerialPort)
        self.BaudRate = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaudRate.sizePolicy().hasHeightForWidth())
        self.BaudRate.setSizePolicy(sizePolicy)
        self.BaudRate.setAcceptDrops(False)
        self.BaudRate.setFrame(True)
        self.BaudRate.setObjectName(_fromUtf8("BaudRate"))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.BaudRate)
        self.toolButton = QtGui.QToolButton(self.groupBox_2)
        self.toolButton.setText(_fromUtf8("N 8 1"))
        self.toolButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_10.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.ResetRcvr = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetRcvr.sizePolicy().hasHeightForWidth())
        self.ResetRcvr.setSizePolicy(sizePolicy)
        self.ResetRcvr.setObjectName(_fromUtf8("ResetRcvr"))
        self.horizontalLayout_11.addWidget(self.ResetRcvr)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.Ping = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ping.sizePolicy().hasHeightForWidth())
        self.Ping.setSizePolicy(sizePolicy)
        self.Ping.setObjectName(_fromUtf8("Ping"))
        self.horizontalLayout_11.addWidget(self.Ping)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.whoFrom = QtGui.QComboBox(self.groupBox_2)
        self.whoFrom.setMinimumSize(QtCore.QSize(111, 26))
        self.whoFrom.setMaximumSize(QtCore.QSize(111, 26))
        self.whoFrom.setObjectName(_fromUtf8("whoFrom"))
        self.horizontalLayout.addWidget(self.whoFrom)
        self.Serial1 = QtGui.QRadioButton(self.groupBox_2)
        self.Serial1.setChecked(False)
        self.Serial1.setObjectName(_fromUtf8("Serial1"))
        self.serialProtocol = QtGui.QButtonGroup(MainWindow)
        self.serialProtocol.setObjectName(_fromUtf8("serialProtocol"))
        self.serialProtocol.addButton(self.Serial1)
        self.horizontalLayout.addWidget(self.Serial1)
        self.SFP = QtGui.QRadioButton(self.groupBox_2)
        self.SFP.setChecked(True)
        self.SFP.setObjectName(_fromUtf8("SFP"))
        self.serialProtocol.addButton(self.SFP)
        self.horizontalLayout.addWidget(self.SFP)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_28.addWidget(self.label_4)
        self.whoTo = QtGui.QComboBox(self.groupBox_2)
        self.whoTo.setMinimumSize(QtCore.QSize(111, 26))
        self.whoTo.setMaximumSize(QtCore.QSize(111, 26))
        self.whoTo.setObjectName(_fromUtf8("whoTo"))
        self.horizontalLayout_28.addWidget(self.whoTo)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.LoopBack = QtGui.QCheckBox(self.groupBox_2)
        self.LoopBack.setObjectName(_fromUtf8("LoopBack"))
        self.horizontalLayout_2.addWidget(self.LoopBack)
        self.ProtocolDump = QtGui.QCheckBox(self.groupBox_2)
        self.ProtocolDump.setObjectName(_fromUtf8("ProtocolDump"))
        self.horizontalLayout_2.addWidget(self.ProtocolDump)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.Serial)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.InBuffered = QtGui.QRadioButton(self.groupBox)
        self.InBuffered.setObjectName(_fromUtf8("InBuffered"))
        self.horizontalLayout_3.addWidget(self.InBuffered)
        self.InRaw = QtGui.QRadioButton(self.groupBox)
        self.InRaw.setChecked(True)
        self.InRaw.setObjectName(_fromUtf8("InRaw"))
        self.horizontalLayout_3.addWidget(self.InRaw)
        self.InRawEcho = QtGui.QRadioButton(self.groupBox)
        self.InRawEcho.setObjectName(_fromUtf8("InRawEcho"))
        self.horizontalLayout_3.addWidget(self.InRawEcho)
        self.InHex = QtGui.QRadioButton(self.groupBox)
        self.InHex.setObjectName(_fromUtf8("InHex"))
        self.horizontalLayout_3.addWidget(self.InHex)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LFnada = QtGui.QRadioButton(self.groupBox)
        self.LFnada.setChecked(True)
        self.LFnada.setObjectName(_fromUtf8("LFnada"))
        self.LfOut = QtGui.QButtonGroup(MainWindow)
        self.LfOut.setObjectName(_fromUtf8("LfOut"))
        self.LfOut.addButton(self.LFnada)
        self.gridLayout.addWidget(self.LFnada, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.CRCR = QtGui.QRadioButton(self.groupBox)
        self.CRCR.setChecked(False)
        self.CRCR.setObjectName(_fromUtf8("CRCR"))
        self.CrOut = QtGui.QButtonGroup(MainWindow)
        self.CrOut.setObjectName(_fromUtf8("CrOut"))
        self.CrOut.addButton(self.CRCR)
        self.gridLayout.addWidget(self.CRCR, 0, 3, 1, 1)
        self.CRnada = QtGui.QRadioButton(self.groupBox)
        self.CRnada.setObjectName(_fromUtf8("CRnada"))
        self.CrOut.addButton(self.CRnada)
        self.gridLayout.addWidget(self.CRnada, 0, 1, 1, 1)
        self.LFLF = QtGui.QRadioButton(self.groupBox)
        self.LFLF.setObjectName(_fromUtf8("LFLF"))
        self.LfOut.addButton(self.LFLF)
        self.gridLayout.addWidget(self.LFLF, 1, 2, 1, 1)
        self.LFCR = QtGui.QRadioButton(self.groupBox)
        self.LFCR.setObjectName(_fromUtf8("LFCR"))
        self.LfOut.addButton(self.LFCR)
        self.gridLayout.addWidget(self.LFCR, 1, 3, 1, 1)
        self.CRLF = QtGui.QRadioButton(self.groupBox)
        self.CRLF.setChecked(False)
        self.CRLF.setObjectName(_fromUtf8("CRLF"))
        self.CrOut.addButton(self.CRLF)
        self.gridLayout.addWidget(self.CRLF, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_12.addWidget(self.label_21)
        self.inputIgnore = QtGui.QComboBox(self.groupBox)
        self.inputIgnore.setObjectName(_fromUtf8("inputIgnore"))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.inputIgnore)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_12.addWidget(self.line)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.sendHex = QtGui.QPushButton(self.groupBox)
        self.sendHex.setObjectName(_fromUtf8("sendHex"))
        self.horizontalLayout_12.addWidget(self.sendHex)
        self.hexNum = QtGui.QLineEdit(self.groupBox)
        self.hexNum.setMinimumSize(QtCore.QSize(30, 0))
        self.hexNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hexNum.setObjectName(_fromUtf8("hexNum"))
        self.horizontalLayout_12.addWidget(self.hexNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_14.addLayout(self.verticalLayout_4)
        self.Controls.addTab(self.Serial, _fromUtf8(""))
        self.SRecords = QtGui.QWidget()
        self.SRecords.setObjectName(_fromUtf8("SRecords"))
        self.srecordTargets = QtGui.QFrame(self.SRecords)
        self.srecordTargets.setGeometry(QtCore.QRect(0, 10, 381, 259))
        self.srecordTargets.setFrameShape(QtGui.QFrame.WinPanel)
        self.srecordTargets.setFrameShadow(QtGui.QFrame.Sunken)
        self.srecordTargets.setObjectName(_fromUtf8("srecordTargets"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.srecordTargets)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_26 = QtGui.QLabel(self.srecordTargets)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_7.addWidget(self.label_26)
        self.targetSelect = QtGui.QComboBox(self.srecordTargets)
        self.targetSelect.setObjectName(_fromUtf8("targetSelect"))
        self.horizontalLayout_7.addWidget(self.targetSelect)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.unlockFlash = QtGui.QPushButton(self.srecordTargets)
        self.unlockFlash.setEnabled(False)
        self.unlockFlash.setObjectName(_fromUtf8("unlockFlash"))
        self.horizontalLayout_7.addWidget(self.unlockFlash)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_18 = QtGui.QLabel(self.srecordTargets)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 4, 0, 1, 1)
        self.srecordFile = QtGui.QLineEdit(self.srecordTargets)
        self.srecordFile.setObjectName(_fromUtf8("srecordFile"))
        self.gridLayout_3.addWidget(self.srecordFile, 0, 1, 1, 2)
        self.label_20 = QtGui.QLabel(self.srecordTargets)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.srecordTargets)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 5, 0, 1, 1)
        self.fileSelect = QtGui.QPushButton(self.srecordTargets)
        self.fileSelect.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSelect.sizePolicy().hasHeightForWidth())
        self.fileSelect.setSizePolicy(sizePolicy)
        self.fileSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.fileSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.fileSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileSelect.setObjectName(_fromUtf8("fileSelect"))
        self.gridLayout_3.addWidget(self.fileSelect, 0, 0, 1, 1)
        self.size = QtGui.QLineEdit(self.srecordTargets)
        self.size.setObjectName(_fromUtf8("size"))
        self.gridLayout_3.addWidget(self.size, 3, 1, 1, 1)
        self.entryPoint = QtGui.QLineEdit(self.srecordTargets)
        self.entryPoint.setEnabled(False)
        self.entryPoint.setObjectName(_fromUtf8("entryPoint"))
        self.gridLayout_3.addWidget(self.entryPoint, 4, 1, 1, 1)
        self.checkSum = QtGui.QLineEdit(self.srecordTargets)
        self.checkSum.setEnabled(False)
        self.checkSum.setObjectName(_fromUtf8("checkSum"))
        self.gridLayout_3.addWidget(self.checkSum, 5, 1, 1, 1)
        self.addressStart = QtGui.QLineEdit(self.srecordTargets)
        self.addressStart.setEnabled(False)
        self.addressStart.setMinimumSize(QtCore.QSize(60, 0))
        self.addressStart.setObjectName(_fromUtf8("addressStart"))
        self.gridLayout_3.addWidget(self.addressStart, 2, 1, 1, 1)
        self.targetAddress = QtGui.QLineEdit(self.srecordTargets)
        self.targetAddress.setObjectName(_fromUtf8("targetAddress"))
        self.gridLayout_3.addWidget(self.targetAddress, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.srecordTargets)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.srecordTargets)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.header = QtGui.QCheckBox(self.srecordTargets)
        self.header.setObjectName(_fromUtf8("header"))
        self.gridLayout_3.addWidget(self.header, 1, 2, 1, 1)
        self.Run = QtGui.QPushButton(self.srecordTargets)
        self.Run.setObjectName(_fromUtf8("Run"))
        self.gridLayout_3.addWidget(self.Run, 2, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_29.addLayout(self.verticalLayout_6)
        self.frame_2 = QtGui.QFrame(self.SRecords)
        self.frame_2.setGeometry(QtCore.QRect(12, 287, 330, 60))
        self.frame_2.setMinimumSize(QtCore.QSize(261, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(330, 60))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.sendSrecord = QtGui.QPushButton(self.frame_2)
        self.sendSrecord.setMinimumSize(QtCore.QSize(71, 32))
        self.sendSrecord.setMaximumSize(QtCore.QSize(71, 32))
        self.sendSrecord.setObjectName(_fromUtf8("sendSrecord"))
        self.horizontalLayout_20.addWidget(self.sendSrecord)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.progressBar = QtGui.QProgressBar(self.frame_2)
        self.progressBar.setMinimumSize(QtCore.QSize(241, 23))
        self.progressBar.setMaximumSize(QtCore.QSize(241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_7.addWidget(self.progressBar)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(1)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.eraseLed = QtGui.QFrame(self.frame_2)
        self.eraseLed.setEnabled(False)
        self.eraseLed.setMinimumSize(QtCore.QSize(12, 10))
        self.eraseLed.setMaximumSize(QtCore.QSize(12, 10))
        self.eraseLed.setStyleSheet(_fromUtf8("background-color: green;"))
        self.eraseLed.setFrameShape(QtGui.QFrame.Panel)
        self.eraseLed.setFrameShadow(QtGui.QFrame.Raised)
        self.eraseLed.setLineWidth(3)
        self.eraseLed.setMidLineWidth(3)
        self.eraseLed.setObjectName(_fromUtf8("eraseLed"))
        self.horizontalLayout_9.addWidget(self.eraseLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_17.addWidget(self.label_7)
        self.transferLed = QtGui.QFrame(self.frame_2)
        self.transferLed.setEnabled(False)
        self.transferLed.setMinimumSize(QtCore.QSize(12, 10))
        self.transferLed.setMaximumSize(QtCore.QSize(12, 10))
        self.transferLed.setStyleSheet(_fromUtf8("background-color: rgb(255, 204, 102);\n"
""))
        self.transferLed.setFrameShape(QtGui.QFrame.Panel)
        self.transferLed.setFrameShadow(QtGui.QFrame.Raised)
        self.transferLed.setLineWidth(3)
        self.transferLed.setMidLineWidth(3)
        self.transferLed.setObjectName(_fromUtf8("transferLed"))
        self.horizontalLayout_17.addWidget(self.transferLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_16.addWidget(self.label_8)
        self.verifyLed = QtGui.QToolButton(self.frame_2)
        self.verifyLed.setMaximumSize(QtCore.QSize(12, 10))
        self.verifyLed.setStyleSheet(_fromUtf8("border: none;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.852217 rgba(241, 0, 0, 255), stop:1 rgba(255, 161, 161, 255));"))
        self.verifyLed.setText(_fromUtf8(""))
        self.verifyLed.setObjectName(_fromUtf8("verifyLed"))
        self.horizontalLayout_16.addWidget(self.verifyLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        self.layoutWidget = QtGui.QWidget(self.SRecords)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 360, 385, 60))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_27.setSpacing(1)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.Recover = QtGui.QPushButton(self.layoutWidget)
        self.Recover.setObjectName(_fromUtf8("Recover"))
        self.horizontalLayout_27.addWidget(self.Recover)
        self.Version = QtGui.QPushButton(self.layoutWidget)
        self.Version.setIconSize(QtCore.QSize(16, 16))
        self.Version.setObjectName(_fromUtf8("Version"))
        self.horizontalLayout_27.addWidget(self.Version)
        self.frame_3 = QtGui.QFrame(self.layoutWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.reboot = QtGui.QPushButton(self.frame_3)
        self.reboot.setObjectName(_fromUtf8("reboot"))
        self.horizontalLayout_21.addWidget(self.reboot)
        self.recoverOption = QtGui.QCheckBox(self.frame_3)
        self.recoverOption.setObjectName(_fromUtf8("recoverOption"))
        self.horizontalLayout_21.addWidget(self.recoverOption)
        self.horizontalLayout_27.addWidget(self.frame_3)
        self.Controls.addTab(self.SRecords, _fromUtf8(""))
        self.Packages = QtGui.QWidget()
        self.Packages.setObjectName(_fromUtf8("Packages"))
        self.PackageTable = QtGui.QTableWidget(self.Packages)
        self.PackageTable.setGeometry(QtCore.QRect(10, 50, 240, 261))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PackageTable.sizePolicy().hasHeightForWidth())
        self.PackageTable.setSizePolicy(sizePolicy)
        self.PackageTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.PackageTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PackageTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PackageTable.setAutoScroll(True)
        self.PackageTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.PackageTable.setTabKeyNavigation(False)
        self.PackageTable.setProperty("showDropIndicator", False)
        self.PackageTable.setDragDropOverwriteMode(False)
        self.PackageTable.setAlternatingRowColors(False)
        self.PackageTable.setWordWrap(False)
        self.PackageTable.setRowCount(8)
        self.PackageTable.setColumnCount(2)
        self.PackageTable.setObjectName(_fromUtf8("PackageTable"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(230, 230, 230))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.PackageTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.PackageTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.PackageTable.setItem(7, 1, item)
        self.PackageTable.horizontalHeader().setDefaultSectionSize(80)
        self.PackageTable.horizontalHeader().setMinimumSectionSize(2)
        self.PackageTable.verticalHeader().setHighlightSections(True)
        self.PackageTable.verticalHeader().setMinimumSectionSize(14)
        self.Refresh = QtGui.QPushButton(self.Packages)
        self.Refresh.setGeometry(QtCore.QRect(30, 0, 90, 32))
        self.Refresh.setObjectName(_fromUtf8("Refresh"))
        self.groupBox_3 = QtGui.QGroupBox(self.Packages)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 30, 121, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setMargin(4)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_33 = QtGui.QLabel(self.groupBox_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_33)
        self.runningChoiceStatus = QtGui.QLabel(self.groupBox_3)
        self.runningChoiceStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.runningChoiceStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.runningChoiceStatus.setObjectName(_fromUtf8("runningChoiceStatus"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.runningChoiceStatus)
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_34)
        self.pendingChoiceStatus = QtGui.QLabel(self.groupBox_3)
        self.pendingChoiceStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.pendingChoiceStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pendingChoiceStatus.setObjectName(_fromUtf8("pendingChoiceStatus"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pendingChoiceStatus)
        self.SlotTable = QtGui.QTableWidget(self.Packages)
        self.SlotTable.setGeometry(QtCore.QRect(10, 350, 361, 81))
        self.SlotTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlotTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlotTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.SlotTable.setTabKeyNavigation(False)
        self.SlotTable.setProperty("showDropIndicator", False)
        self.SlotTable.setDragDropOverwriteMode(False)
        self.SlotTable.setObjectName(_fromUtf8("SlotTable"))
        self.SlotTable.setColumnCount(4)
        self.SlotTable.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.SlotTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SlotTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.SlotTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SlotTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.SlotTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.SlotTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.SlotTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlotTable.setItem(1, 3, item)
        self.SlotTable.horizontalHeader().setDefaultSectionSize(80)
        self.MainbootTable = QtGui.QTableWidget(self.Packages)
        self.MainbootTable.setGeometry(QtCore.QRect(290, 200, 81, 51))
        self.MainbootTable.setObjectName(_fromUtf8("MainbootTable"))
        self.MainbootTable.setColumnCount(1)
        self.MainbootTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.MainbootTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.MainbootTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.MainbootTable.setItem(0, 0, item)
        self.MainbootTable.horizontalHeader().setDefaultSectionSize(80)
        self.MainbootTable.verticalHeader().setVisible(False)
        self.label_31 = QtGui.QLabel(self.Packages)
        self.label_31.setGeometry(QtCore.QRect(0, 30, 62, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.Packages)
        self.label_32.setGeometry(QtCore.QRect(0, 330, 62, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.DatabaseTable = QtGui.QTableWidget(self.Packages)
        self.DatabaseTable.setGeometry(QtCore.QRect(290, 260, 81, 51))
        self.DatabaseTable.setObjectName(_fromUtf8("DatabaseTable"))
        self.DatabaseTable.setColumnCount(1)
        self.DatabaseTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.DatabaseTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DatabaseTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.DatabaseTable.setItem(0, 0, item)
        self.DatabaseTable.horizontalHeader().setDefaultSectionSize(80)
        self.DatabaseTable.verticalHeader().setVisible(False)
        self.label_35 = QtGui.QLabel(self.Packages)
        self.label_35.setGeometry(QtCore.QRect(260, 120, 62, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.Packages)
        self.label_36.setGeometry(QtCore.QRect(260, 140, 81, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.magicStatus = QtGui.QLabel(self.Packages)
        self.magicStatus.setGeometry(QtCore.QRect(340, 120, 62, 16))
        self.magicStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.magicStatus.setObjectName(_fromUtf8("magicStatus"))
        self.checksumStatus = QtGui.QLabel(self.Packages)
        self.checksumStatus.setGeometry(QtCore.QRect(340, 140, 62, 16))
        self.checksumStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.checksumStatus.setObjectName(_fromUtf8("checksumStatus"))
        self.Rebuild = QtGui.QPushButton(self.Packages)
        self.Rebuild.setGeometry(QtCore.QRect(160, 0, 90, 32))
        self.Rebuild.setObjectName(_fromUtf8("Rebuild"))
        self.Controls.addTab(self.Packages, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_0 = QtGui.QWidget()
        self.page_0.setGeometry(QtCore.QRect(0, 0, 344, 307))
        self.page_0.setObjectName(_fromUtf8("page_0"))
        self.layoutWidget1 = QtGui.QWidget(self.page_0)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 21, 311, 189))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.serialInputs = QtGui.QLineEdit(self.layoutWidget1)
        self.serialInputs.setEnabled(False)
        self.serialInputs.setObjectName(_fromUtf8("serialInputs"))
        self.gridLayout_5.addWidget(self.serialInputs, 1, 1, 1, 1)
        self.serialOutputs = QtGui.QLineEdit(self.layoutWidget1)
        self.serialOutputs.setEnabled(False)
        self.serialOutputs.setObjectName(_fromUtf8("serialOutputs"))
        self.gridLayout_5.addWidget(self.serialOutputs, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.sfpLoInputs = QtGui.QLineEdit(self.layoutWidget1)
        self.sfpLoInputs.setEnabled(False)
        self.sfpLoInputs.setObjectName(_fromUtf8("sfpLoInputs"))
        self.gridLayout_5.addWidget(self.sfpLoInputs, 2, 1, 1, 1)
        self.sfpLoOutputs = QtGui.QLineEdit(self.layoutWidget1)
        self.sfpLoOutputs.setEnabled(False)
        self.sfpLoOutputs.setObjectName(_fromUtf8("sfpLoOutputs"))
        self.gridLayout_5.addWidget(self.sfpLoOutputs, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.sfpHiInputs = QtGui.QLineEdit(self.layoutWidget1)
        self.sfpHiInputs.setEnabled(False)
        self.sfpHiInputs.setObjectName(_fromUtf8("sfpHiInputs"))
        self.gridLayout_5.addWidget(self.sfpHiInputs, 3, 1, 1, 1)
        self.sfpHiOutputs = QtGui.QLineEdit(self.layoutWidget1)
        self.sfpHiOutputs.setEnabled(False)
        self.sfpHiOutputs.setObjectName(_fromUtf8("sfpHiOutputs"))
        self.gridLayout_5.addWidget(self.sfpHiOutputs, 3, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 4, 0, 1, 1)
        self.inPackets = QtGui.QLineEdit(self.layoutWidget1)
        self.inPackets.setEnabled(False)
        self.inPackets.setText(_fromUtf8(""))
        self.inPackets.setObjectName(_fromUtf8("inPackets"))
        self.gridLayout_5.addWidget(self.inPackets, 4, 1, 1, 1)
        self.outPackets = QtGui.QLineEdit(self.layoutWidget1)
        self.outPackets.setEnabled(False)
        self.outPackets.setText(_fromUtf8(""))
        self.outPackets.setObjectName(_fromUtf8("outPackets"))
        self.gridLayout_5.addWidget(self.outPackets, 4, 2, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_5)
        self.clearTranStats = QtGui.QPushButton(self.layoutWidget1)
        self.clearTranStats.setMaximumSize(QtCore.QSize(81, 32))
        self.clearTranStats.setObjectName(_fromUtf8("clearTranStats"))
        self.verticalLayout_16.addWidget(self.clearTranStats)
        self.toolBox.addItem(self.page_0, _fromUtf8(""))
        self.page_1 = QtGui.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 361, 299))
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.loadRun = QtGui.QPushButton(self.page_1)
        self.loadRun.setGeometry(QtCore.QRect(10, 80, 67, 32))
        self.loadRun.setObjectName(_fromUtf8("loadRun"))
        self.groupBox_8 = QtGui.QGroupBox(self.page_1)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 130, 161, 51))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.clearStats = QtGui.QPushButton(self.groupBox_8)
        self.clearStats.setGeometry(QtCore.QRect(10, 20, 67, 32))
        self.clearStats.setObjectName(_fromUtf8("clearStats"))
        self.getStats = QtGui.QPushButton(self.groupBox_8)
        self.getStats.setGeometry(QtCore.QRect(90, 20, 67, 32))
        self.getStats.setObjectName(_fromUtf8("getStats"))
        self.layoutWidget_2 = QtGui.QWidget(self.page_1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 341, 24))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_18.addWidget(self.label)
        self.loadFrames = QtGui.QLineEdit(self.layoutWidget_2)
        self.loadFrames.setObjectName(_fromUtf8("loadFrames"))
        self.horizontalLayout_18.addWidget(self.loadFrames)
        self.label_27 = QtGui.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_18.addWidget(self.label_27)
        self.loadSize = QtGui.QLineEdit(self.layoutWidget_2)
        self.loadSize.setObjectName(_fromUtf8("loadSize"))
        self.horizontalLayout_18.addWidget(self.loadSize)
        self.label_28 = QtGui.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_18.addWidget(self.label_28)
        self.loadDelay = QtGui.QLineEdit(self.layoutWidget_2)
        self.loadDelay.setObjectName(_fromUtf8("loadDelay"))
        self.horizontalLayout_18.addWidget(self.loadDelay)
        self.toolBox.addItem(self.page_1, _fromUtf8(""))
        self.UARTBoot = QtGui.QWidget()
        self.UARTBoot.setGeometry(QtCore.QRect(0, 0, 344, 307))
        self.UARTBoot.setObjectName(_fromUtf8("UARTBoot"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.UARTBoot)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(7)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.initBoot = QtGui.QPushButton(self.UARTBoot)
        self.initBoot.setObjectName(_fromUtf8("initBoot"))
        self.horizontalLayout_22.addWidget(self.initBoot)
        self.line_2 = QtGui.QFrame(self.UARTBoot)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_22.addWidget(self.line_2)
        self.getCommand = QtGui.QPushButton(self.UARTBoot)
        self.getCommand.setObjectName(_fromUtf8("getCommand"))
        self.horizontalLayout_22.addWidget(self.getCommand)
        self.gvCommand = QtGui.QPushButton(self.UARTBoot)
        self.gvCommand.setObjectName(_fromUtf8("gvCommand"))
        self.horizontalLayout_22.addWidget(self.gvCommand)
        self.gidCommand = QtGui.QPushButton(self.UARTBoot)
        self.gidCommand.setObjectName(_fromUtf8("gidCommand"))
        self.horizontalLayout_22.addWidget(self.gidCommand)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.readCommand = QtGui.QPushButton(self.UARTBoot)
        self.readCommand.setObjectName(_fromUtf8("readCommand"))
        self.horizontalLayout_5.addWidget(self.readCommand)
        self.label_9 = QtGui.QLabel(self.UARTBoot)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.readAddress = QtGui.QLineEdit(self.UARTBoot)
        self.readAddress.setObjectName(_fromUtf8("readAddress"))
        self.horizontalLayout_5.addWidget(self.readAddress)
        self.label_22 = QtGui.QLabel(self.UARTBoot)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_5.addWidget(self.label_22)
        self.readLength = QtGui.QLineEdit(self.UARTBoot)
        self.readLength.setObjectName(_fromUtf8("readLength"))
        self.horizontalLayout_5.addWidget(self.readLength)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.goCommand = QtGui.QPushButton(self.UARTBoot)
        self.goCommand.setObjectName(_fromUtf8("goCommand"))
        self.horizontalLayout_8.addWidget(self.goCommand)
        self.label_23 = QtGui.QLabel(self.UARTBoot)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_8.addWidget(self.label_23)
        self.goAddress = QtGui.QLineEdit(self.UARTBoot)
        self.goAddress.setObjectName(_fromUtf8("goAddress"))
        self.horizontalLayout_8.addWidget(self.goAddress)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(7)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.writeCommand = QtGui.QPushButton(self.UARTBoot)
        self.writeCommand.setObjectName(_fromUtf8("writeCommand"))
        self.horizontalLayout_13.addWidget(self.writeCommand)
        self.label_24 = QtGui.QLabel(self.UARTBoot)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_13.addWidget(self.label_24)
        self.writeAddress = QtGui.QLineEdit(self.UARTBoot)
        self.writeAddress.setObjectName(_fromUtf8("writeAddress"))
        self.horizontalLayout_13.addWidget(self.writeAddress)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.writeLength = QtGui.QLabel(self.UARTBoot)
        self.writeLength.setObjectName(_fromUtf8("writeLength"))
        self.horizontalLayout_13.addWidget(self.writeLength)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.writeData = QtGui.QPlainTextEdit(self.UARTBoot)
        self.writeData.setMaximumSize(QtCore.QSize(16777215, 60))
        self.writeData.setObjectName(_fromUtf8("writeData"))
        self.verticalLayout_9.addWidget(self.writeData)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.eraseCommand = QtGui.QPushButton(self.UARTBoot)
        self.eraseCommand.setObjectName(_fromUtf8("eraseCommand"))
        self.horizontalLayout_14.addWidget(self.eraseCommand)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.eraseData = QtGui.QPlainTextEdit(self.UARTBoot)
        self.eraseData.setMaximumSize(QtCore.QSize(16777215, 60))
        self.eraseData.setObjectName(_fromUtf8("eraseData"))
        self.verticalLayout_9.addWidget(self.eraseData)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem14)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_9.setStretch(4, 1)
        self.verticalLayout_9.setStretch(5, 1)
        self.verticalLayout_9.setStretch(6, 1)
        self.toolBox.addItem(self.UARTBoot, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.toolBox)
        self.Controls.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(7, 10, 372, 286))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.phrase1 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase1.sizePolicy().hasHeightForWidth())
        self.phrase1.setSizePolicy(sizePolicy)
        self.phrase1.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase1.setObjectName(_fromUtf8("phrase1"))
        self.gridLayout_2.addWidget(self.phrase1, 1, 0, 1, 1)
        self.phrase2 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(127)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase2.sizePolicy().hasHeightForWidth())
        self.phrase2.setSizePolicy(sizePolicy)
        self.phrase2.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase2.setObjectName(_fromUtf8("phrase2"))
        self.gridLayout_2.addWidget(self.phrase2, 0, 0, 1, 1)
        self.phrase4 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase4.sizePolicy().hasHeightForWidth())
        self.phrase4.setSizePolicy(sizePolicy)
        self.phrase4.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase4.setObjectName(_fromUtf8("phrase4"))
        self.gridLayout_2.addWidget(self.phrase4, 3, 0, 1, 1)
        self.send2 = QtGui.QPushButton(self.layoutWidget2)
        self.send2.setObjectName(_fromUtf8("send2"))
        self.gridLayout_2.addWidget(self.send2, 0, 1, 1, 1)
        self.phrase3 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase3.sizePolicy().hasHeightForWidth())
        self.phrase3.setSizePolicy(sizePolicy)
        self.phrase3.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase3.setObjectName(_fromUtf8("phrase3"))
        self.gridLayout_2.addWidget(self.phrase3, 2, 0, 1, 1)
        self.send6 = QtGui.QPushButton(self.layoutWidget2)
        self.send6.setObjectName(_fromUtf8("send6"))
        self.gridLayout_2.addWidget(self.send6, 5, 1, 1, 1)
        self.phrase6 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase6.sizePolicy().hasHeightForWidth())
        self.phrase6.setSizePolicy(sizePolicy)
        self.phrase6.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase6.setObjectName(_fromUtf8("phrase6"))
        self.gridLayout_2.addWidget(self.phrase6, 5, 0, 1, 1)
        self.send8 = QtGui.QPushButton(self.layoutWidget2)
        self.send8.setObjectName(_fromUtf8("send8"))
        self.gridLayout_2.addWidget(self.send8, 7, 1, 1, 1)
        self.send7 = QtGui.QPushButton(self.layoutWidget2)
        self.send7.setObjectName(_fromUtf8("send7"))
        self.gridLayout_2.addWidget(self.send7, 6, 1, 1, 1)
        self.send3 = QtGui.QPushButton(self.layoutWidget2)
        self.send3.setObjectName(_fromUtf8("send3"))
        self.gridLayout_2.addWidget(self.send3, 2, 1, 1, 1)
        self.phrase5 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase5.sizePolicy().hasHeightForWidth())
        self.phrase5.setSizePolicy(sizePolicy)
        self.phrase5.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase5.setObjectName(_fromUtf8("phrase5"))
        self.gridLayout_2.addWidget(self.phrase5, 4, 0, 1, 1)
        self.send1 = QtGui.QPushButton(self.layoutWidget2)
        self.send1.setObjectName(_fromUtf8("send1"))
        self.gridLayout_2.addWidget(self.send1, 1, 1, 1, 1)
        self.phrase8 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase8.sizePolicy().hasHeightForWidth())
        self.phrase8.setSizePolicy(sizePolicy)
        self.phrase8.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase8.setObjectName(_fromUtf8("phrase8"))
        self.gridLayout_2.addWidget(self.phrase8, 7, 0, 1, 1)
        self.phrase7 = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase7.sizePolicy().hasHeightForWidth())
        self.phrase7.setSizePolicy(sizePolicy)
        self.phrase7.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase7.setObjectName(_fromUtf8("phrase7"))
        self.gridLayout_2.addWidget(self.phrase7, 6, 0, 1, 1)
        self.send4 = QtGui.QPushButton(self.layoutWidget2)
        self.send4.setObjectName(_fromUtf8("send4"))
        self.gridLayout_2.addWidget(self.send4, 3, 1, 1, 1)
        self.send5 = QtGui.QPushButton(self.layoutWidget2)
        self.send5.setObjectName(_fromUtf8("send5"))
        self.gridLayout_2.addWidget(self.send5, 4, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 290)
        self.gridLayout_2.setColumnStretch(0, 290)
        self.Controls.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.Controls)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.textEdit.setMinimumSize(QtCore.QSize(601, 471))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        font.setItalic(False)
        font.setKerning(False)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet(_fromUtf8("color: cyan;"))
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setPlainText(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_5.addWidget(self.textEdit)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setSpacing(7)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.Find = QtGui.QPushButton(self.centralwidget)
        self.Find.setObjectName(_fromUtf8("Find"))
        self.horizontalLayout_35.addWidget(self.Find)
        self.FindText = QtGui.QLineEdit(self.centralwidget)
        self.FindText.setObjectName(_fromUtf8("FindText"))
        self.horizontalLayout_35.addWidget(self.FindText)
        self.FindBackwards = QtGui.QCheckBox(self.centralwidget)
        self.FindBackwards.setObjectName(_fromUtf8("FindBackwards"))
        self.horizontalLayout_35.addWidget(self.FindBackwards)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem15)
        self.saveText = QtGui.QPushButton(self.centralwidget)
        self.saveText.setObjectName(_fromUtf8("saveText"))
        self.horizontalLayout_35.addWidget(self.saveText)
        self.ClearText = QtGui.QPushButton(self.centralwidget)
        self.ClearText.setMaximumSize(QtCore.QSize(107, 32))
        self.ClearText.setObjectName(_fromUtf8("ClearText"))
        self.horizontalLayout_35.addWidget(self.ClearText)
        self.verticalLayout_5.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Controls.setCurrentIndex(3)
        self.BaudRate.setCurrentIndex(5)
        self.targetSelect.setCurrentIndex(-1)
        self.toolBox.setCurrentIndex(2)
        QtCore.QObject.connect(self.ClearText, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Port Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.SerialPort.setItemText(0, QtGui.QApplication.translate("MainWindow", "(Select a Port)", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(0, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(1, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(2, QtGui.QApplication.translate("MainWindow", "28800", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(3, QtGui.QApplication.translate("MainWindow", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(4, QtGui.QApplication.translate("MainWindow", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(5, QtGui.QApplication.translate("MainWindow", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(6, QtGui.QApplication.translate("MainWindow", "230400", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(7, QtGui.QApplication.translate("MainWindow", "460800", None, QtGui.QApplication.UnicodeUTF8))
        self.BaudRate.setItemText(8, QtGui.QApplication.translate("MainWindow", "500000", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetRcvr.setText(QtGui.QApplication.translate("MainWindow", "Reset Rcvr", None, QtGui.QApplication.UnicodeUTF8))
        self.Ping.setText(QtGui.QApplication.translate("MainWindow", "Ping", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.Serial1.setText(QtGui.QApplication.translate("MainWindow", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP.setText(QtGui.QApplication.translate("MainWindow", "SFP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Dest:", None, QtGui.QApplication.UnicodeUTF8))
        self.LoopBack.setText(QtGui.QApplication.translate("MainWindow", "Loop back", None, QtGui.QApplication.UnicodeUTF8))
        self.ProtocolDump.setText(QtGui.QApplication.translate("MainWindow", "Protocol Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Input/Output", None, QtGui.QApplication.UnicodeUTF8))
        self.InBuffered.setText(QtGui.QApplication.translate("MainWindow", "Buffered", None, QtGui.QApplication.UnicodeUTF8))
        self.InRaw.setText(QtGui.QApplication.translate("MainWindow", "Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.InRawEcho.setText(QtGui.QApplication.translate("MainWindow", "Raw+Echo", None, QtGui.QApplication.UnicodeUTF8))
        self.InHex.setText(QtGui.QApplication.translate("MainWindow", "Hex", None, QtGui.QApplication.UnicodeUTF8))
        self.LFnada.setText(QtGui.QApplication.translate("MainWindow", "nada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Output CR as:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Output LF as:", None, QtGui.QApplication.UnicodeUTF8))
        self.CRCR.setText(QtGui.QApplication.translate("MainWindow", "CR", None, QtGui.QApplication.UnicodeUTF8))
        self.CRnada.setText(QtGui.QApplication.translate("MainWindow", "nada", None, QtGui.QApplication.UnicodeUTF8))
        self.LFLF.setText(QtGui.QApplication.translate("MainWindow", "LF", None, QtGui.QApplication.UnicodeUTF8))
        self.LFCR.setText(QtGui.QApplication.translate("MainWindow", "CR", None, QtGui.QApplication.UnicodeUTF8))
        self.CRLF.setText(QtGui.QApplication.translate("MainWindow", "LF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.inputIgnore.setItemText(0, QtGui.QApplication.translate("MainWindow", "Passive", None, QtGui.QApplication.UnicodeUTF8))
        self.inputIgnore.setItemText(1, QtGui.QApplication.translate("MainWindow", "Ignore CR", None, QtGui.QApplication.UnicodeUTF8))
        self.inputIgnore.setItemText(2, QtGui.QApplication.translate("MainWindow", "Ignore LF", None, QtGui.QApplication.UnicodeUTF8))
        self.inputIgnore.setItemText(3, QtGui.QApplication.translate("MainWindow", "Ignore CRLF", None, QtGui.QApplication.UnicodeUTF8))
        self.sendHex.setText(QtGui.QApplication.translate("MainWindow", "Send Hex:", None, QtGui.QApplication.UnicodeUTF8))
        self.Controls.setTabText(self.Controls.indexOf(self.Serial), QtGui.QApplication.translate("MainWindow", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Target:", None, QtGui.QApplication.UnicodeUTF8))
        self.unlockFlash.setText(QtGui.QApplication.translate("MainWindow", "Unlock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Entry Point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "CheckSum:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSelect.setText(QtGui.QApplication.translate("MainWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Address Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Target Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.header.setText(QtGui.QApplication.translate("MainWindow", "+Header", None, QtGui.QApplication.UnicodeUTF8))
        self.Run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.sendSrecord.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Verify", None, QtGui.QApplication.UnicodeUTF8))
        self.Recover.setText(QtGui.QApplication.translate("MainWindow", "Recover", None, QtGui.QApplication.UnicodeUTF8))
        self.Version.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.reboot.setText(QtGui.QApplication.translate("MainWindow", "Reboot", None, QtGui.QApplication.UnicodeUTF8))
        self.recoverOption.setText(QtGui.QApplication.translate("MainWindow", "+recover", None, QtGui.QApplication.UnicodeUTF8))
        self.Controls.setTabText(self.Controls.indexOf(self.SRecords), QtGui.QApplication.translate("MainWindow", "S-Records", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Package", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Launcher", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Main App", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "uBoot", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Linux", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Display App", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "IO App", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "PM App", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.PackageTable.isSortingEnabled()
        self.PackageTable.setSortingEnabled(False)
        item = self.PackageTable.item(1, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "empty", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.item(1, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.item(2, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "bad header", None, QtGui.QApplication.UnicodeUTF8))
        item = self.PackageTable.item(2, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "bad image", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageTable.setSortingEnabled(__sortingEnabled)
        self.Refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Running:", None, QtGui.QApplication.UnicodeUTF8))
        self.runningChoiceStatus.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Pending:", None, QtGui.QApplication.UnicodeUTF8))
        self.pendingChoiceStatus.setText(QtGui.QApplication.translate("MainWindow", "Invalid", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "SlotA", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "SlotB", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Boot", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Hiboot", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "App", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.SlotTable.isSortingEnabled()
        self.SlotTable.setSortingEnabled(False)
        item = self.SlotTable.item(0, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Empty", None, QtGui.QApplication.UnicodeUTF8))
        item = self.SlotTable.item(1, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Empty", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotTable.setSortingEnabled(__sortingEnabled)
        item = self.MainbootTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        item = self.MainbootTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Main Boot", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.MainbootTable.isSortingEnabled()
        self.MainbootTable.setSortingEnabled(False)
        item = self.MainbootTable.item(0, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "1.1.1", None, QtGui.QApplication.UnicodeUTF8))
        self.MainbootTable.setSortingEnabled(__sortingEnabled)
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Packages:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Slots:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DatabaseTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DatabaseTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.DatabaseTable.isSortingEnabled()
        self.DatabaseTable.setSortingEnabled(False)
        item = self.DatabaseTable.item(0, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "1.1.1", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseTable.setSortingEnabled(__sortingEnabled)
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Magic:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Checksum:", None, QtGui.QApplication.UnicodeUTF8))
        self.magicStatus.setText(QtGui.QApplication.translate("MainWindow", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.checksumStatus.setText(QtGui.QApplication.translate("MainWindow", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.Rebuild.setText(QtGui.QApplication.translate("MainWindow", "Rebuild", None, QtGui.QApplication.UnicodeUTF8))
        self.Controls.setTabText(self.Controls.indexOf(self.Packages), QtGui.QApplication.translate("MainWindow", "Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "SFP lo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "SFP hi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Packets", None, QtGui.QApplication.UnicodeUTF8))
        self.clearTranStats.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_0), QtGui.QApplication.translate("MainWindow", "Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.loadRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.clearStats.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.getStats.setText(QtGui.QApplication.translate("MainWindow", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFrames.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSize.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Delay(mS):", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDelay.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), QtGui.QApplication.translate("MainWindow", "Load Test", None, QtGui.QApplication.UnicodeUTF8))
        self.initBoot.setText(QtGui.QApplication.translate("MainWindow", "7F", None, QtGui.QApplication.UnicodeUTF8))
        self.getCommand.setText(QtGui.QApplication.translate("MainWindow", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.gvCommand.setText(QtGui.QApplication.translate("MainWindow", "GV", None, QtGui.QApplication.UnicodeUTF8))
        self.gidCommand.setText(QtGui.QApplication.translate("MainWindow", "GID", None, QtGui.QApplication.UnicodeUTF8))
        self.readCommand.setText(QtGui.QApplication.translate("MainWindow", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.goCommand.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.writeCommand.setText(QtGui.QApplication.translate("MainWindow", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.writeLength.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.eraseCommand.setText(QtGui.QApplication.translate("MainWindow", "X Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.UARTBoot), QtGui.QApplication.translate("MainWindow", "STM32 Boot Loader", None, QtGui.QApplication.UnicodeUTF8))
        self.Controls.setTabText(self.Controls.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.send2.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send6.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send8.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send7.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send3.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send1.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send4.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.send5.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.Controls.setTabText(self.Controls.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Phrases", None, QtGui.QApplication.UnicodeUTF8))
        self.Find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.FindBackwards.setText(QtGui.QApplication.translate("MainWindow", "Backwards", None, QtGui.QApplication.UnicodeUTF8))
        self.saveText.setText(QtGui.QApplication.translate("MainWindow", "Save Text", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearText.setText(QtGui.QApplication.translate("MainWindow", "Clear Text", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

