# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1031, 597)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setMargin(12)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setMargin(12)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(12, 0, 12, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.Controls = QtGui.QTabWidget(self.centralwidget)
        self.Controls.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Controls.sizePolicy().hasHeightForWidth())
        self.Controls.setSizePolicy(sizePolicy)
        self.Controls.setMinimumSize(QtCore.QSize(390, 470))
        self.Controls.setMaximumSize(QtCore.QSize(420, 470))
        self.Controls.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Controls.setObjectName(_fromUtf8("Controls"))
        self.Interface = QtGui.QWidget()
        self.Interface.setObjectName(_fromUtf8("Interface"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.Interface)
        self.verticalLayout_24.setMargin(12)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.groupBox_5 = QtGui.QGroupBox(self.Interface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_30.setMargin(12)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setMargin(12)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setMargin(12)
        self.horizontalLayout_38.setSpacing(6)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.serialIf = QtGui.QRadioButton(self.groupBox_5)
        self.serialIf.setChecked(True)
        self.serialIf.setObjectName(_fromUtf8("serialIf"))
        self.horizontalLayout_38.addWidget(self.serialIf)
        self.ethernetIf = QtGui.QRadioButton(self.groupBox_5)
        self.ethernetIf.setObjectName(_fromUtf8("ethernetIf"))
        self.horizontalLayout_38.addWidget(self.ethernetIf)
        self.verticalLayout_14.addLayout(self.horizontalLayout_38)
        self.PortSelect = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortSelect.sizePolicy().hasHeightForWidth())
        self.PortSelect.setSizePolicy(sizePolicy)
        self.PortSelect.setMaximumSize(QtCore.QSize(150, 16777215))
        self.PortSelect.setObjectName(_fromUtf8("PortSelect"))
        self.PortSelect.addItem(_fromUtf8(""))
        self.verticalLayout_14.addWidget(self.PortSelect)
        self.horizontalLayout_30.addLayout(self.verticalLayout_14)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setMargin(12)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.widget = QtGui.QWidget(self.groupBox_5)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.BaudRate = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaudRate.sizePolicy().hasHeightForWidth())
        self.BaudRate.setSizePolicy(sizePolicy)
        self.BaudRate.setAcceptDrops(False)
        self.BaudRate.setFrame(True)
        self.BaudRate.setObjectName(_fromUtf8("BaudRate"))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.BaudRate.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.BaudRate)
        self.toolButton = QtGui.QToolButton(self.widget)
        self.toolButton.setEnabled(True)
        self.toolButton.setText(_fromUtf8("N 8 1"))
        self.toolButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.verticalLayout_5.addWidget(self.toolButton)
        self.verticalLayout_18.addWidget(self.widget)
        self.ethernetWidget = QtGui.QWidget(self.groupBox_5)
        self.ethernetWidget.setVisible(False)
        self.ethernetWidget.setObjectName(_fromUtf8("ethernetWidget"))
        self.formLayout_4 = QtGui.QFormLayout(self.ethernetWidget)
        self.formLayout_4.setMargin(5)
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.portDest = QtGui.QLabel(self.ethernetWidget)
        self.portDest.setObjectName(_fromUtf8("portDest"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.portDest)
        self.destIp = QtGui.QLineEdit(self.ethernetWidget)
        self.destIp.setMinimumSize(QtCore.QSize(0, 0))
        self.destIp.setObjectName(_fromUtf8("destIp"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.destIp)
        self.portPort = QtGui.QLabel(self.ethernetWidget)
        self.portPort.setObjectName(_fromUtf8("portPort"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.portPort)
        self.ipPort = QtGui.QLineEdit(self.ethernetWidget)
        self.ipPort.setMinimumSize(QtCore.QSize(0, 0))
        self.ipPort.setObjectName(_fromUtf8("ipPort"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.ipPort)
        self.verticalLayout_18.addWidget(self.ethernetWidget)
        self.horizontalLayout_30.addLayout(self.verticalLayout_18)
        self.horizontalLayout_30.setStretch(0, 1)
        self.horizontalLayout_30.setStretch(1, 2)
        self.verticalLayout_24.addWidget(self.groupBox_5)
        self.groupBox_2 = QtGui.QGroupBox(self.Interface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_121 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_121.setMargin(12)
        self.verticalLayout_121.setSpacing(6)
        self.verticalLayout_121.setObjectName(_fromUtf8("verticalLayout_121"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(12)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(12)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_151 = QtGui.QHBoxLayout()
        self.horizontalLayout_151.setMargin(12)
        self.horizontalLayout_151.setSpacing(6)
        self.horizontalLayout_151.setObjectName(_fromUtf8("horizontalLayout_151"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(12)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Serial1 = QtGui.QRadioButton(self.groupBox_2)
        self.Serial1.setChecked(False)
        self.Serial1.setObjectName(_fromUtf8("Serial1"))
        self.serialProtocol = QtGui.QButtonGroup(MainWindow)
        self.serialProtocol.setObjectName(_fromUtf8("serialProtocol"))
        self.serialProtocol.addButton(self.Serial1)
        self.verticalLayout_4.addWidget(self.Serial1)
        self.SFP = QtGui.QRadioButton(self.groupBox_2)
        self.SFP.setChecked(True)
        self.SFP.setObjectName(_fromUtf8("SFP"))
        self.serialProtocol.addButton(self.SFP)
        self.verticalLayout_4.addWidget(self.SFP)
        self.AT = QtGui.QRadioButton(self.groupBox_2)
        self.AT.setObjectName(_fromUtf8("AT"))
        self.serialProtocol.addButton(self.AT)
        self.verticalLayout_4.addWidget(self.AT)
        self.horizontalLayout_151.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_151.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_151)
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(12)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setMargin(12)
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_26.addWidget(self.label_5)
        self.whoFrom = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whoFrom.sizePolicy().hasHeightForWidth())
        self.whoFrom.setSizePolicy(sizePolicy)
        self.whoFrom.setMinimumSize(QtCore.QSize(130, 26))
        self.whoFrom.setMaximumSize(QtCore.QSize(130, 26))
        self.whoFrom.setObjectName(_fromUtf8("whoFrom"))
        self.horizontalLayout_26.addWidget(self.whoFrom)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setMargin(12)
        self.horizontalLayout_28.setSpacing(6)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_28.addWidget(self.label_4)
        self.whoTo = QtGui.QComboBox(self.groupBox_2)
        self.whoTo.setMinimumSize(QtCore.QSize(130, 26))
        self.whoTo.setMaximumSize(QtCore.QSize(130, 26))
        self.whoTo.setObjectName(_fromUtf8("whoTo"))
        self.horizontalLayout_28.addWidget(self.whoTo)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.line_5 = QtGui.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setMargin(12)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.LoopBack = QtGui.QCheckBox(self.groupBox_2)
        self.LoopBack.setObjectName(_fromUtf8("LoopBack"))
        self.gridLayout_6.addWidget(self.LoopBack, 1, 0, 1, 1)
        self.ResetRcvr = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetRcvr.sizePolicy().hasHeightForWidth())
        self.ResetRcvr.setSizePolicy(sizePolicy)
        self.ResetRcvr.setObjectName(_fromUtf8("ResetRcvr"))
        self.gridLayout_6.addWidget(self.ResetRcvr, 1, 3, 1, 1)
        self.ProtocolDump = QtGui.QCheckBox(self.groupBox_2)
        self.ProtocolDump.setObjectName(_fromUtf8("ProtocolDump"))
        self.gridLayout_6.addWidget(self.ProtocolDump, 0, 0, 1, 1)
        self.Ping = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ping.sizePolicy().hasHeightForWidth())
        self.Ping.setSizePolicy(sizePolicy)
        self.Ping.setObjectName(_fromUtf8("Ping"))
        self.gridLayout_6.addWidget(self.Ping, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.verticalLayout_121.addLayout(self.verticalLayout_3)
        self.verticalLayout_24.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem2)
        self.Controls.addTab(self.Interface, _fromUtf8(""))
        self.Text = QtGui.QWidget()
        self.Text.setObjectName(_fromUtf8("Text"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.Text)
        self.verticalLayout_23.setMargin(12)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.groupBox_6 = QtGui.QGroupBox(self.Text)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_22.setMargin(12)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setMargin(12)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.inputIgnore = QtGui.QComboBox(self.groupBox_6)
        self.inputIgnore.setObjectName(_fromUtf8("inputIgnore"))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.inputIgnore.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.inputIgnore)
        self.line = QtGui.QFrame(self.groupBox_6)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_12.addWidget(self.line)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.sendHex = QtGui.QPushButton(self.groupBox_6)
        self.sendHex.setObjectName(_fromUtf8("sendHex"))
        self.horizontalLayout_12.addWidget(self.sendHex)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.hexNum = QtGui.QLineEdit(self.groupBox_6)
        self.hexNum.setMinimumSize(QtCore.QSize(40, 0))
        self.hexNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hexNum.setObjectName(_fromUtf8("hexNum"))
        self.horizontalLayout_12.addWidget(self.hexNum)
        self.verticalLayout_22.addLayout(self.horizontalLayout_12)
        self.verticalLayout_23.addWidget(self.groupBox_6)
        self.groupBox = QtGui.QGroupBox(self.Text)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setMargin(12)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(12)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.InBuffered = QtGui.QRadioButton(self.groupBox)
        self.InBuffered.setObjectName(_fromUtf8("InBuffered"))
        self.horizontalLayout_3.addWidget(self.InBuffered)
        self.InRaw = QtGui.QRadioButton(self.groupBox)
        self.InRaw.setChecked(True)
        self.InRaw.setObjectName(_fromUtf8("InRaw"))
        self.horizontalLayout_3.addWidget(self.InRaw)
        self.InRawEcho = QtGui.QRadioButton(self.groupBox)
        self.InRawEcho.setObjectName(_fromUtf8("InRawEcho"))
        self.horizontalLayout_3.addWidget(self.InRawEcho)
        self.InHex = QtGui.QRadioButton(self.groupBox)
        self.InHex.setObjectName(_fromUtf8("InHex"))
        self.horizontalLayout_3.addWidget(self.InHex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(12)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LFnada = QtGui.QRadioButton(self.groupBox)
        self.LFnada.setChecked(True)
        self.LFnada.setObjectName(_fromUtf8("LFnada"))
        self.LfOut = QtGui.QButtonGroup(MainWindow)
        self.LfOut.setObjectName(_fromUtf8("LfOut"))
        self.LfOut.addButton(self.LFnada)
        self.gridLayout.addWidget(self.LFnada, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.CRCR = QtGui.QRadioButton(self.groupBox)
        self.CRCR.setChecked(False)
        self.CRCR.setObjectName(_fromUtf8("CRCR"))
        self.CrOut = QtGui.QButtonGroup(MainWindow)
        self.CrOut.setObjectName(_fromUtf8("CrOut"))
        self.CrOut.addButton(self.CRCR)
        self.gridLayout.addWidget(self.CRCR, 0, 3, 1, 1)
        self.CRnada = QtGui.QRadioButton(self.groupBox)
        self.CRnada.setObjectName(_fromUtf8("CRnada"))
        self.CrOut.addButton(self.CRnada)
        self.gridLayout.addWidget(self.CRnada, 0, 1, 1, 1)
        self.LFLF = QtGui.QRadioButton(self.groupBox)
        self.LFLF.setObjectName(_fromUtf8("LFLF"))
        self.LfOut.addButton(self.LFLF)
        self.gridLayout.addWidget(self.LFLF, 1, 2, 1, 1)
        self.LFCR = QtGui.QRadioButton(self.groupBox)
        self.LFCR.setObjectName(_fromUtf8("LFCR"))
        self.LfOut.addButton(self.LFCR)
        self.gridLayout.addWidget(self.LFCR, 1, 3, 1, 1)
        self.CRLF = QtGui.QRadioButton(self.groupBox)
        self.CRLF.setChecked(False)
        self.CRLF.setObjectName(_fromUtf8("CRLF"))
        self.CrOut.addButton(self.CRLF)
        self.gridLayout.addWidget(self.CRLF, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_23.addWidget(self.groupBox)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem6)
        self.Controls.addTab(self.Text, _fromUtf8(""))
        self.Transfer = QtGui.QWidget()
        self.Transfer.setObjectName(_fromUtf8("Transfer"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.Transfer)
        self.verticalLayout_9.setMargin(12)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.srecordTargets = QtGui.QFrame(self.Transfer)
        self.srecordTargets.setFrameShape(QtGui.QFrame.WinPanel)
        self.srecordTargets.setFrameShadow(QtGui.QFrame.Sunken)
        self.srecordTargets.setObjectName(_fromUtf8("srecordTargets"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.srecordTargets)
        self.horizontalLayout_29.setMargin(12)
        self.horizontalLayout_29.setSpacing(6)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setMargin(12)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(12)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_26 = QtGui.QLabel(self.srecordTargets)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_7.addWidget(self.label_26)
        self.targetSelect = QtGui.QComboBox(self.srecordTargets)
        self.targetSelect.setObjectName(_fromUtf8("targetSelect"))
        self.horizontalLayout_7.addWidget(self.targetSelect)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setMargin(12)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_18 = QtGui.QLabel(self.srecordTargets)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 4, 0, 1, 1)
        self.srecordFile = QtGui.QLineEdit(self.srecordTargets)
        self.srecordFile.setObjectName(_fromUtf8("srecordFile"))
        self.gridLayout_3.addWidget(self.srecordFile, 0, 1, 1, 2)
        self.label_20 = QtGui.QLabel(self.srecordTargets)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.srecordTargets)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 5, 0, 1, 1)
        self.fileSelect = QtGui.QPushButton(self.srecordTargets)
        self.fileSelect.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSelect.sizePolicy().hasHeightForWidth())
        self.fileSelect.setSizePolicy(sizePolicy)
        self.fileSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.fileSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.fileSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileSelect.setObjectName(_fromUtf8("fileSelect"))
        self.gridLayout_3.addWidget(self.fileSelect, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.size = QtGui.QLineEdit(self.srecordTargets)
        self.size.setObjectName(_fromUtf8("size"))
        self.gridLayout_3.addWidget(self.size, 3, 1, 1, 1)
        self.entryPoint = QtGui.QLineEdit(self.srecordTargets)
        self.entryPoint.setEnabled(False)
        self.entryPoint.setObjectName(_fromUtf8("entryPoint"))
        self.gridLayout_3.addWidget(self.entryPoint, 4, 1, 1, 1)
        self.checkSum = QtGui.QLineEdit(self.srecordTargets)
        self.checkSum.setEnabled(False)
        self.checkSum.setObjectName(_fromUtf8("checkSum"))
        self.gridLayout_3.addWidget(self.checkSum, 5, 1, 1, 1)
        self.addressStart = QtGui.QLineEdit(self.srecordTargets)
        self.addressStart.setEnabled(False)
        self.addressStart.setMinimumSize(QtCore.QSize(60, 0))
        self.addressStart.setObjectName(_fromUtf8("addressStart"))
        self.gridLayout_3.addWidget(self.addressStart, 2, 1, 1, 1)
        self.targetAddress = QtGui.QLineEdit(self.srecordTargets)
        self.targetAddress.setObjectName(_fromUtf8("targetAddress"))
        self.gridLayout_3.addWidget(self.targetAddress, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.srecordTargets)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.srecordTargets)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.header = QtGui.QCheckBox(self.srecordTargets)
        self.header.setObjectName(_fromUtf8("header"))
        self.gridLayout_3.addWidget(self.header, 1, 2, 1, 1)
        self.Run = QtGui.QPushButton(self.srecordTargets)
        self.Run.setObjectName(_fromUtf8("Run"))
        self.gridLayout_3.addWidget(self.Run, 4, 2, 1, 1)
        self.endian = QtGui.QCheckBox(self.srecordTargets)
        self.endian.setChecked(True)
        self.endian.setObjectName(_fromUtf8("endian"))
        self.gridLayout_3.addWidget(self.endian, 2, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_29.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addWidget(self.srecordTargets)
        self.frame_2 = QtGui.QFrame(self.Transfer)
        self.frame_2.setMinimumSize(QtCore.QSize(261, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(330, 60))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_20.setMargin(12)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.sendSrecord = QtGui.QPushButton(self.frame_2)
        self.sendSrecord.setMinimumSize(QtCore.QSize(71, 32))
        self.sendSrecord.setMaximumSize(QtCore.QSize(71, 32))
        self.sendSrecord.setObjectName(_fromUtf8("sendSrecord"))
        self.horizontalLayout_20.addWidget(self.sendSrecord)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setMargin(12)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.progressBar = QtGui.QProgressBar(self.frame_2)
        self.progressBar.setMinimumSize(QtCore.QSize(241, 23))
        self.progressBar.setMaximumSize(QtCore.QSize(241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_7.addWidget(self.progressBar)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setMargin(12)
        self.horizontalLayout_19.setSpacing(1)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(12)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.eraseLed = QtGui.QFrame(self.frame_2)
        self.eraseLed.setEnabled(False)
        self.eraseLed.setMinimumSize(QtCore.QSize(12, 10))
        self.eraseLed.setMaximumSize(QtCore.QSize(12, 10))
        self.eraseLed.setStyleSheet(_fromUtf8("background-color: green;"))
        self.eraseLed.setFrameShape(QtGui.QFrame.Panel)
        self.eraseLed.setFrameShadow(QtGui.QFrame.Raised)
        self.eraseLed.setLineWidth(3)
        self.eraseLed.setMidLineWidth(3)
        self.eraseLed.setObjectName(_fromUtf8("eraseLed"))
        self.horizontalLayout_9.addWidget(self.eraseLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setMargin(12)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_17.addWidget(self.label_7)
        self.transferLed = QtGui.QFrame(self.frame_2)
        self.transferLed.setEnabled(False)
        self.transferLed.setMinimumSize(QtCore.QSize(12, 10))
        self.transferLed.setMaximumSize(QtCore.QSize(12, 10))
        self.transferLed.setStyleSheet(_fromUtf8("background-color: rgb(255, 204, 102);\n"
""))
        self.transferLed.setFrameShape(QtGui.QFrame.Panel)
        self.transferLed.setFrameShadow(QtGui.QFrame.Raised)
        self.transferLed.setLineWidth(3)
        self.transferLed.setMidLineWidth(3)
        self.transferLed.setObjectName(_fromUtf8("transferLed"))
        self.horizontalLayout_17.addWidget(self.transferLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setMargin(12)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_16.addWidget(self.label_8)
        self.verifyLed = QtGui.QToolButton(self.frame_2)
        self.verifyLed.setMaximumSize(QtCore.QSize(12, 10))
        self.verifyLed.setStyleSheet(_fromUtf8("border: none;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.852217 rgba(241, 0, 0, 255), stop:1 rgba(255, 161, 161, 255));"))
        self.verifyLed.setText(_fromUtf8(""))
        self.verifyLed.setObjectName(_fromUtf8("verifyLed"))
        self.horizontalLayout_16.addWidget(self.verifyLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setMargin(12)
        self.horizontalLayout_27.setSpacing(1)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.Recover = QtGui.QPushButton(self.Transfer)
        self.Recover.setObjectName(_fromUtf8("Recover"))
        self.horizontalLayout_27.addWidget(self.Recover)
        self.Version = QtGui.QPushButton(self.Transfer)
        self.Version.setIconSize(QtCore.QSize(16, 16))
        self.Version.setObjectName(_fromUtf8("Version"))
        self.horizontalLayout_27.addWidget(self.Version)
        self.frame_3 = QtGui.QFrame(self.Transfer)
        self.frame_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_21.setMargin(12)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.reboot = QtGui.QPushButton(self.frame_3)
        self.reboot.setObjectName(_fromUtf8("reboot"))
        self.horizontalLayout_21.addWidget(self.reboot)
        self.recoverOption = QtGui.QCheckBox(self.frame_3)
        self.recoverOption.setObjectName(_fromUtf8("recoverOption"))
        self.horizontalLayout_21.addWidget(self.recoverOption)
        self.horizontalLayout_27.addWidget(self.frame_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_27)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.Controls.addTab(self.Transfer, _fromUtf8(""))
        self.Info = QtGui.QWidget()
        self.Info.setObjectName(_fromUtf8("Info"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.Info)
        self.verticalLayout_10.setMargin(12)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setMargin(12)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.Refresh = QtGui.QPushButton(self.Info)
        self.Refresh.setObjectName(_fromUtf8("Refresh"))
        self.horizontalLayout_24.addWidget(self.Refresh)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setMargin(12)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.groupBox_3 = QtGui.QGroupBox(self.Info)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setMargin(4)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_33 = QtGui.QLabel(self.groupBox_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_33)
        self.runningChoiceStatus = QtGui.QLabel(self.groupBox_3)
        self.runningChoiceStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.runningChoiceStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.runningChoiceStatus.setObjectName(_fromUtf8("runningChoiceStatus"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.runningChoiceStatus)
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_34)
        self.pendingChoiceStatus = QtGui.QLabel(self.groupBox_3)
        self.pendingChoiceStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.pendingChoiceStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pendingChoiceStatus.setObjectName(_fromUtf8("pendingChoiceStatus"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pendingChoiceStatus)
        self.horizontalLayout_23.addWidget(self.groupBox_3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setMargin(12)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_35 = QtGui.QLabel(self.Info)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_35)
        self.magicStatus = QtGui.QLabel(self.Info)
        self.magicStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.magicStatus.setObjectName(_fromUtf8("magicStatus"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.magicStatus)
        self.label_36 = QtGui.QLabel(self.Info)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_36)
        self.checksumStatus = QtGui.QLabel(self.Info)
        self.checksumStatus.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.checksumStatus.setObjectName(_fromUtf8("checksumStatus"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.checksumStatus)
        self.horizontalLayout_23.addLayout(self.formLayout_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.groupBox_4 = QtGui.QGroupBox(self.Info)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_25.setMargin(12)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setMargin(12)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 0, 0, 1, 1)
        self.bootVersion = QtGui.QLineEdit(self.groupBox_4)
        self.bootVersion.setObjectName(_fromUtf8("bootVersion"))
        self.gridLayout_4.addWidget(self.bootVersion, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 1, 0, 1, 1)
        self.leftAppVersion = QtGui.QLineEdit(self.groupBox_4)
        self.leftAppVersion.setObjectName(_fromUtf8("leftAppVersion"))
        self.gridLayout_4.addWidget(self.leftAppVersion, 1, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.rightAppVersion = QtGui.QLineEdit(self.groupBox_4)
        self.rightAppVersion.setObjectName(_fromUtf8("rightAppVersion"))
        self.gridLayout_4.addWidget(self.rightAppVersion, 2, 1, 1, 1)
        self.horizontalLayout_25.addLayout(self.gridLayout_4)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        spacerItem13 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.Controls.addTab(self.Info, _fromUtf8(""))
        self.Tools = QtGui.QWidget()
        self.Tools.setObjectName(_fromUtf8("Tools"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.Tools)
        self.verticalLayout_15.setMargin(12)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.toolBox = QtGui.QToolBox(self.Tools)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 360, 281))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_19.setMargin(12)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.tabWidget = QtGui.QTabWidget(self.page)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.STMBootTransfer = QtGui.QWidget()
        self.STMBootTransfer.setObjectName(_fromUtf8("STMBootTransfer"))
        self.gridLayout_10 = QtGui.QGridLayout(self.STMBootTransfer)
        self.gridLayout_10.setMargin(12)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.sendBoot = QtGui.QPushButton(self.STMBootTransfer)
        self.sendBoot.setMinimumSize(QtCore.QSize(71, 32))
        self.sendBoot.setMaximumSize(QtCore.QSize(83, 32))
        self.sendBoot.setObjectName(_fromUtf8("sendBoot"))
        self.gridLayout_10.addWidget(self.sendBoot, 7, 0, 1, 1)
        self.bootSize = QtGui.QLineEdit(self.STMBootTransfer)
        self.bootSize.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bootSize.setReadOnly(True)
        self.bootSize.setObjectName(_fromUtf8("bootSize"))
        self.gridLayout_10.addWidget(self.bootSize, 6, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.STMBootTransfer)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_10.addWidget(self.label_32, 2, 0, 1, 1)
        self.run = QtGui.QCheckBox(self.STMBootTransfer)
        self.run.setChecked(True)
        self.run.setObjectName(_fromUtf8("run"))
        self.gridLayout_10.addWidget(self.run, 0, 3, 1, 1)
        self.bootStart = QtGui.QLineEdit(self.STMBootTransfer)
        self.bootStart.setObjectName(_fromUtf8("bootStart"))
        self.gridLayout_10.addWidget(self.bootStart, 2, 1, 1, 1)
        self.bootFile = QtGui.QLineEdit(self.STMBootTransfer)
        self.bootFile.setObjectName(_fromUtf8("bootFile"))
        self.gridLayout_10.addWidget(self.bootFile, 0, 1, 1, 2)
        self.label_29 = QtGui.QLabel(self.STMBootTransfer)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_10.addWidget(self.label_29, 6, 0, 1, 1)
        self.bootLoaderProgressBar = QtGui.QProgressBar(self.STMBootTransfer)
        self.bootLoaderProgressBar.setMinimumSize(QtCore.QSize(200, 23))
        self.bootLoaderProgressBar.setMaximumSize(QtCore.QSize(200, 23))
        self.bootLoaderProgressBar.setProperty("value", 0)
        self.bootLoaderProgressBar.setObjectName(_fromUtf8("bootLoaderProgressBar"))
        self.gridLayout_10.addWidget(self.bootLoaderProgressBar, 7, 1, 1, 3)
        self.Go = QtGui.QPushButton(self.STMBootTransfer)
        self.Go.setObjectName(_fromUtf8("Go"))
        self.gridLayout_10.addWidget(self.Go, 2, 3, 1, 1)
        self.bootSelect = QtGui.QPushButton(self.STMBootTransfer)
        self.bootSelect.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bootSelect.sizePolicy().hasHeightForWidth())
        self.bootSelect.setSizePolicy(sizePolicy)
        self.bootSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.bootSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.bootSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bootSelect.setObjectName(_fromUtf8("bootSelect"))
        self.gridLayout_10.addWidget(self.bootSelect, 0, 0, 1, 1)
        self.tabWidget.addTab(self.STMBootTransfer, _fromUtf8(""))
        self.STMTools = QtGui.QWidget()
        self.STMTools.setObjectName(_fromUtf8("STMTools"))
        self.gridLayout_11 = QtGui.QGridLayout(self.STMTools)
        self.gridLayout_11.setMargin(12)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.Boot = QtGui.QPushButton(self.STMTools)
        self.Boot.setObjectName(_fromUtf8("Boot"))
        self.gridLayout_11.addWidget(self.Boot, 0, 0, 1, 1)
        self.Init = QtGui.QPushButton(self.STMTools)
        self.Init.setObjectName(_fromUtf8("Init"))
        self.gridLayout_11.addWidget(self.Init, 0, 1, 1, 1)
        self.Reconnect = QtGui.QPushButton(self.STMTools)
        self.Reconnect.setObjectName(_fromUtf8("Reconnect"))
        self.gridLayout_11.addWidget(self.Reconnect, 0, 2, 1, 1)
        self.Rdp = QtGui.QPushButton(self.STMTools)
        self.Rdp.setObjectName(_fromUtf8("Rdp"))
        self.gridLayout_11.addWidget(self.Rdp, 1, 0, 1, 1)
        self.Getrpd = QtGui.QPushButton(self.STMTools)
        self.Getrpd.setObjectName(_fromUtf8("Getrpd"))
        self.gridLayout_11.addWidget(self.Getrpd, 1, 1, 1, 1)
        self.Erase = QtGui.QPushButton(self.STMTools)
        self.Erase.setObjectName(_fromUtf8("Erase"))
        self.gridLayout_11.addWidget(self.Erase, 1, 2, 1, 1)
        self.Get = QtGui.QPushButton(self.STMTools)
        self.Get.setObjectName(_fromUtf8("Get"))
        self.gridLayout_11.addWidget(self.Get, 2, 0, 1, 1)
        self.Getid = QtGui.QPushButton(self.STMTools)
        self.Getid.setObjectName(_fromUtf8("Getid"))
        self.gridLayout_11.addWidget(self.Getid, 2, 1, 1, 1)
        self.Pages = QtGui.QPushButton(self.STMTools)
        self.Pages.setObjectName(_fromUtf8("Pages"))
        self.gridLayout_11.addWidget(self.Pages, 2, 2, 1, 1)
        self.Write = QtGui.QPushButton(self.STMTools)
        self.Write.setObjectName(_fromUtf8("Write"))
        self.gridLayout_11.addWidget(self.Write, 3, 0, 1, 1)
        self.Address = QtGui.QPushButton(self.STMTools)
        self.Address.setObjectName(_fromUtf8("Address"))
        self.gridLayout_11.addWidget(self.Address, 3, 1, 1, 1)
        self.Data = QtGui.QPushButton(self.STMTools)
        self.Data.setObjectName(_fromUtf8("Data"))
        self.gridLayout_11.addWidget(self.Data, 3, 2, 1, 1)
        self.tabWidget.addTab(self.STMTools, _fromUtf8(""))
        self.verticalLayout_19.addWidget(self.tabWidget)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setMargin(12)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verbose = QtGui.QCheckBox(self.page)
        self.verbose.setObjectName(_fromUtf8("verbose"))
        self.verticalLayout_17.addWidget(self.verbose)
        self.setDateTime = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setDateTime.sizePolicy().hasHeightForWidth())
        self.setDateTime.setSizePolicy(sizePolicy)
        self.setDateTime.setObjectName(_fromUtf8("setDateTime"))
        self.verticalLayout_17.addWidget(self.setDateTime)
        self.verticalLayout_19.addLayout(self.verticalLayout_17)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 265, 162))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_13.setMargin(12)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setMargin(12)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.jamFile = QtGui.QLineEdit(self.page_2)
        self.jamFile.setObjectName(_fromUtf8("jamFile"))
        self.gridLayout_12.addWidget(self.jamFile, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(12)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sendJam = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendJam.sizePolicy().hasHeightForWidth())
        self.sendJam.setSizePolicy(sizePolicy)
        self.sendJam.setMinimumSize(QtCore.QSize(0, 0))
        self.sendJam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendJam.setObjectName(_fromUtf8("sendJam"))
        self.horizontalLayout_2.addWidget(self.sendJam)
        self.sendFile = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendFile.sizePolicy().hasHeightForWidth())
        self.sendFile.setSizePolicy(sizePolicy)
        self.sendFile.setObjectName(_fromUtf8("sendFile"))
        self.horizontalLayout_2.addWidget(self.sendFile)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.jamSelect = QtGui.QPushButton(self.page_2)
        self.jamSelect.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jamSelect.sizePolicy().hasHeightForWidth())
        self.jamSelect.setSizePolicy(sizePolicy)
        self.jamSelect.setMinimumSize(QtCore.QSize(0, 0))
        self.jamSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jamSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jamSelect.setObjectName(_fromUtf8("jamSelect"))
        self.gridLayout_12.addWidget(self.jamSelect, 0, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.page_2)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_12.addWidget(self.label_40, 1, 0, 1, 1)
        self.jamLoaderProgressBar = QtGui.QProgressBar(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jamLoaderProgressBar.sizePolicy().hasHeightForWidth())
        self.jamLoaderProgressBar.setSizePolicy(sizePolicy)
        self.jamLoaderProgressBar.setMinimumSize(QtCore.QSize(130, 23))
        self.jamLoaderProgressBar.setMaximumSize(QtCore.QSize(16777215, 23))
        self.jamLoaderProgressBar.setProperty("value", 0)
        self.jamLoaderProgressBar.setInvertedAppearance(True)
        self.jamLoaderProgressBar.setObjectName(_fromUtf8("jamLoaderProgressBar"))
        self.gridLayout_12.addWidget(self.jamLoaderProgressBar, 2, 0, 1, 2)
        self.jamSize = QtGui.QLineEdit(self.page_2)
        self.jamSize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jamSize.setReadOnly(True)
        self.jamSize.setObjectName(_fromUtf8("jamSize"))
        self.gridLayout_12.addWidget(self.jamSize, 1, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_12)
        spacerItem15 = QtGui.QSpacerItem(20, 116, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem15)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 308, 221))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setMargin(12)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setMargin(12)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_72 = QtGui.QLabel(self.page_3)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_7.addWidget(self.label_72, 2, 0, 1, 1)
        self.eepromSize = QtGui.QLineEdit(self.page_3)
        self.eepromSize.setMaximumSize(QtCore.QSize(120, 16777215))
        self.eepromSize.setReadOnly(True)
        self.eepromSize.setObjectName(_fromUtf8("eepromSize"))
        self.gridLayout_7.addWidget(self.eepromSize, 2, 1, 1, 1)
        self.eepromFile = QtGui.QLineEdit(self.page_3)
        self.eepromFile.setObjectName(_fromUtf8("eepromFile"))
        self.gridLayout_7.addWidget(self.eepromFile, 1, 1, 1, 1)
        self.crcStatus = QtGui.QLabel(self.page_3)
        self.crcStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.crcStatus.setText(_fromUtf8(""))
        self.crcStatus.setObjectName(_fromUtf8("crcStatus"))
        self.gridLayout_7.addWidget(self.crcStatus, 3, 2, 1, 1)
        self.eepromTarget = QtGui.QComboBox(self.page_3)
        self.eepromTarget.setObjectName(_fromUtf8("eepromTarget"))
        self.eepromTarget.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.eepromTarget, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 3, 0, 1, 1)
        self.crcValue = QtGui.QLineEdit(self.page_3)
        self.crcValue.setMaximumSize(QtCore.QSize(120, 16777215))
        self.crcValue.setReadOnly(True)
        self.crcValue.setPlaceholderText(_fromUtf8(""))
        self.crcValue.setObjectName(_fromUtf8("crcValue"))
        self.gridLayout_7.addWidget(self.crcValue, 3, 1, 1, 1)
        self.eepromSelect = QtGui.QPushButton(self.page_3)
        self.eepromSelect.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eepromSelect.sizePolicy().hasHeightForWidth())
        self.eepromSelect.setSizePolicy(sizePolicy)
        self.eepromSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.eepromSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.eepromSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eepromSelect.setObjectName(_fromUtf8("eepromSelect"))
        self.gridLayout_7.addWidget(self.eepromSelect, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.page_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.eepromLoaderProgressBar = QtGui.QProgressBar(self.page_3)
        self.eepromLoaderProgressBar.setMinimumSize(QtCore.QSize(200, 23))
        self.eepromLoaderProgressBar.setMaximumSize(QtCore.QSize(1000, 23))
        self.eepromLoaderProgressBar.setProperty("value", 0)
        self.eepromLoaderProgressBar.setObjectName(_fromUtf8("eepromLoaderProgressBar"))
        self.gridLayout_7.addWidget(self.eepromLoaderProgressBar, 4, 0, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(12)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sendEeprom = QtGui.QPushButton(self.page_3)
        self.sendEeprom.setMinimumSize(QtCore.QSize(0, 0))
        self.sendEeprom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendEeprom.setObjectName(_fromUtf8("sendEeprom"))
        self.horizontalLayout.addWidget(self.sendEeprom)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.readEeprom = QtGui.QPushButton(self.page_3)
        self.readEeprom.setEnabled(False)
        self.readEeprom.setObjectName(_fromUtf8("readEeprom"))
        self.horizontalLayout.addWidget(self.readEeprom)
        self.gridLayout_7.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem17, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.Monitor = QtGui.QWidget()
        self.Monitor.setGeometry(QtCore.QRect(0, 0, 296, 225))
        self.Monitor.setObjectName(_fromUtf8("Monitor"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.Monitor)
        self.verticalLayout_16.setMargin(12)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.groupBox_7 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setMargin(12)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.MonitorPort1 = QtGui.QComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort1.sizePolicy().hasHeightForWidth())
        self.MonitorPort1.setSizePolicy(sizePolicy)
        self.MonitorPort1.setObjectName(_fromUtf8("MonitorPort1"))
        self.MonitorPort1.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.MonitorPort1, 0, 0, 1, 1)
        self.MonitorBaud1 = QtGui.QComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud1.sizePolicy().hasHeightForWidth())
        self.MonitorBaud1.setSizePolicy(sizePolicy)
        self.MonitorBaud1.setAcceptDrops(False)
        self.MonitorBaud1.setFrame(True)
        self.MonitorBaud1.setObjectName(_fromUtf8("MonitorBaud1"))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.MonitorBaud1.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.MonitorBaud1, 0, 1, 1, 1)
        self.Color1 = QtGui.QComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color1.sizePolicy().hasHeightForWidth())
        self.Color1.setSizePolicy(sizePolicy)
        self.Color1.setAcceptDrops(False)
        self.Color1.setFrame(True)
        self.Color1.setObjectName(_fromUtf8("Color1"))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.Color1.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.Color1, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setMargin(12)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.MonitorPort2 = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort2.sizePolicy().hasHeightForWidth())
        self.MonitorPort2.setSizePolicy(sizePolicy)
        self.MonitorPort2.setObjectName(_fromUtf8("MonitorPort2"))
        self.MonitorPort2.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.MonitorPort2, 0, 0, 1, 1)
        self.MonitorBaud2 = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud2.sizePolicy().hasHeightForWidth())
        self.MonitorBaud2.setSizePolicy(sizePolicy)
        self.MonitorBaud2.setAcceptDrops(False)
        self.MonitorBaud2.setFrame(True)
        self.MonitorBaud2.setObjectName(_fromUtf8("MonitorBaud2"))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.MonitorBaud2.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.MonitorBaud2, 0, 1, 1, 1)
        self.Color2 = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color2.sizePolicy().hasHeightForWidth())
        self.Color2.setSizePolicy(sizePolicy)
        self.Color2.setAcceptDrops(False)
        self.Color2.setFrame(True)
        self.Color2.setObjectName(_fromUtf8("Color2"))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.Color2.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.Color2, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_8)
        spacerItem19 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem19)
        self.toolBox.addItem(self.Monitor, _fromUtf8(""))
        self.verticalLayout_15.addWidget(self.toolBox)
        self.Controls.addTab(self.Tools, _fromUtf8(""))
        self.Phrases = QtGui.QWidget()
        self.Phrases.setObjectName(_fromUtf8("Phrases"))
        self.layoutWidget_4 = QtGui.QWidget(self.Phrases)
        self.layoutWidget_4.setGeometry(QtCore.QRect(7, 10, 372, 286))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setMargin(12)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.phrase1 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase1.sizePolicy().hasHeightForWidth())
        self.phrase1.setSizePolicy(sizePolicy)
        self.phrase1.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase1.setObjectName(_fromUtf8("phrase1"))
        self.gridLayout_2.addWidget(self.phrase1, 1, 0, 1, 1)
        self.phrase2 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(127)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase2.sizePolicy().hasHeightForWidth())
        self.phrase2.setSizePolicy(sizePolicy)
        self.phrase2.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase2.setObjectName(_fromUtf8("phrase2"))
        self.gridLayout_2.addWidget(self.phrase2, 0, 0, 1, 1)
        self.phrase4 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase4.sizePolicy().hasHeightForWidth())
        self.phrase4.setSizePolicy(sizePolicy)
        self.phrase4.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase4.setObjectName(_fromUtf8("phrase4"))
        self.gridLayout_2.addWidget(self.phrase4, 3, 0, 1, 1)
        self.send2 = QtGui.QPushButton(self.layoutWidget_4)
        self.send2.setObjectName(_fromUtf8("send2"))
        self.gridLayout_2.addWidget(self.send2, 0, 1, 1, 1)
        self.phrase3 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase3.sizePolicy().hasHeightForWidth())
        self.phrase3.setSizePolicy(sizePolicy)
        self.phrase3.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase3.setObjectName(_fromUtf8("phrase3"))
        self.gridLayout_2.addWidget(self.phrase3, 2, 0, 1, 1)
        self.send6 = QtGui.QPushButton(self.layoutWidget_4)
        self.send6.setObjectName(_fromUtf8("send6"))
        self.gridLayout_2.addWidget(self.send6, 5, 1, 1, 1)
        self.phrase6 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase6.sizePolicy().hasHeightForWidth())
        self.phrase6.setSizePolicy(sizePolicy)
        self.phrase6.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase6.setObjectName(_fromUtf8("phrase6"))
        self.gridLayout_2.addWidget(self.phrase6, 5, 0, 1, 1)
        self.send8 = QtGui.QPushButton(self.layoutWidget_4)
        self.send8.setObjectName(_fromUtf8("send8"))
        self.gridLayout_2.addWidget(self.send8, 7, 1, 1, 1)
        self.send7 = QtGui.QPushButton(self.layoutWidget_4)
        self.send7.setObjectName(_fromUtf8("send7"))
        self.gridLayout_2.addWidget(self.send7, 6, 1, 1, 1)
        self.send3 = QtGui.QPushButton(self.layoutWidget_4)
        self.send3.setObjectName(_fromUtf8("send3"))
        self.gridLayout_2.addWidget(self.send3, 2, 1, 1, 1)
        self.phrase5 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase5.sizePolicy().hasHeightForWidth())
        self.phrase5.setSizePolicy(sizePolicy)
        self.phrase5.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase5.setObjectName(_fromUtf8("phrase5"))
        self.gridLayout_2.addWidget(self.phrase5, 4, 0, 1, 1)
        self.send1 = QtGui.QPushButton(self.layoutWidget_4)
        self.send1.setObjectName(_fromUtf8("send1"))
        self.gridLayout_2.addWidget(self.send1, 1, 1, 1, 1)
        self.phrase8 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase8.sizePolicy().hasHeightForWidth())
        self.phrase8.setSizePolicy(sizePolicy)
        self.phrase8.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase8.setObjectName(_fromUtf8("phrase8"))
        self.gridLayout_2.addWidget(self.phrase8, 7, 0, 1, 1)
        self.phrase7 = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase7.sizePolicy().hasHeightForWidth())
        self.phrase7.setSizePolicy(sizePolicy)
        self.phrase7.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase7.setObjectName(_fromUtf8("phrase7"))
        self.gridLayout_2.addWidget(self.phrase7, 6, 0, 1, 1)
        self.send4 = QtGui.QPushButton(self.layoutWidget_4)
        self.send4.setObjectName(_fromUtf8("send4"))
        self.gridLayout_2.addWidget(self.send4, 3, 1, 1, 1)
        self.send5 = QtGui.QPushButton(self.layoutWidget_4)
        self.send5.setObjectName(_fromUtf8("send5"))
        self.gridLayout_2.addWidget(self.send5, 4, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 290)
        self.gridLayout_2.setColumnStretch(0, 290)
        self.Controls.addTab(self.Phrases, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.Controls)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_51 = QtGui.QVBoxLayout()
        self.verticalLayout_51.setMargin(12)
        self.verticalLayout_51.setSpacing(0)
        self.verticalLayout_51.setObjectName(_fromUtf8("verticalLayout_51"))
        self.textEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.textEdit.setMinimumSize(QtCore.QSize(601, 471))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(12)
        font.setItalic(False)
        font.setKerning(False)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet(_fromUtf8("color: cyan;"))
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setPlainText(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_51.addWidget(self.textEdit)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setMargin(12)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(12, 6, 12, 6)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.Find = QtGui.QPushButton(self.frame)
        self.Find.setObjectName(_fromUtf8("Find"))
        self.horizontalLayout_8.addWidget(self.Find)
        self.FindText = QtGui.QLineEdit(self.frame)
        self.FindText.setObjectName(_fromUtf8("FindText"))
        self.horizontalLayout_8.addWidget(self.FindText)
        self.FindBackwards = QtGui.QCheckBox(self.frame)
        self.FindBackwards.setObjectName(_fromUtf8("FindBackwards"))
        self.horizontalLayout_8.addWidget(self.FindBackwards)
        self.horizontalLayout_35.addWidget(self.frame)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem20)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setContentsMargins(12, 6, 12, 6)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.frame_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.fontSize = QtGui.QSpinBox(self.frame_4)
        self.fontSize.setMinimum(5)
        self.fontSize.setMaximum(40)
        self.fontSize.setProperty("value", 12)
        self.fontSize.setObjectName(_fromUtf8("fontSize"))
        self.horizontalLayout_11.addWidget(self.fontSize)
        self.horizontalLayout_35.addWidget(self.frame_4)
        self.saveText = QtGui.QPushButton(self.centralwidget)
        self.saveText.setObjectName(_fromUtf8("saveText"))
        self.horizontalLayout_35.addWidget(self.saveText)
        self.ClearText = QtGui.QPushButton(self.centralwidget)
        self.ClearText.setMaximumSize(QtCore.QSize(107, 32))
        self.ClearText.setObjectName(_fromUtf8("ClearText"))
        self.horizontalLayout_35.addWidget(self.ClearText)
        self.verticalLayout_51.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_15.addLayout(self.verticalLayout_51)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Controls.setCurrentIndex(4)
        self.BaudRate.setCurrentIndex(5)
        self.targetSelect.setCurrentIndex(-1)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.MonitorBaud1.setCurrentIndex(5)
        self.Color1.setCurrentIndex(4)
        self.MonitorBaud2.setCurrentIndex(5)
        self.Color2.setCurrentIndex(6)
        QtCore.QObject.connect(self.ClearText, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit.clear)
        QtCore.QObject.connect(self.ethernetIf, QtCore.SIGNAL(_fromUtf8("pressed()")), self.widget.hide)
        QtCore.QObject.connect(self.ethernetIf, QtCore.SIGNAL(_fromUtf8("pressed()")), self.ethernetWidget.show)
        QtCore.QObject.connect(self.serialIf, QtCore.SIGNAL(_fromUtf8("pressed()")), self.widget.show)
        QtCore.QObject.connect(self.serialIf, QtCore.SIGNAL(_fromUtf8("pressed()")), self.ethernetWidget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Port", None))
        self.serialIf.setText(_translate("MainWindow", "Serial", None))
        self.ethernetIf.setText(_translate("MainWindow", "Ethernet", None))
        self.PortSelect.setItemText(0, _translate("MainWindow", "(Select host Port)", None))
        self.BaudRate.setItemText(0, _translate("MainWindow", "9600", None))
        self.BaudRate.setItemText(1, _translate("MainWindow", "19200", None))
        self.BaudRate.setItemText(2, _translate("MainWindow", "28800", None))
        self.BaudRate.setItemText(3, _translate("MainWindow", "38400", None))
        self.BaudRate.setItemText(4, _translate("MainWindow", "57600", None))
        self.BaudRate.setItemText(5, _translate("MainWindow", "115200", None))
        self.BaudRate.setItemText(6, _translate("MainWindow", "230400", None))
        self.BaudRate.setItemText(7, _translate("MainWindow", "460800", None))
        self.BaudRate.setItemText(8, _translate("MainWindow", "500000", None))
        self.portDest.setText(_translate("MainWindow", "Dest:", None))
        self.destIp.setText(_translate("MainWindow", "192.168.2.2", None))
        self.portPort.setText(_translate("MainWindow", "Port:", None))
        self.ipPort.setText(_translate("MainWindow", "1961", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Protocol", None))
        self.Serial1.setText(_translate("MainWindow", "Serial", None))
        self.SFP.setText(_translate("MainWindow", "SFP", None))
        self.AT.setText(_translate("MainWindow", "AT", None))
        self.label_5.setText(_translate("MainWindow", "Host:", None))
        self.label_4.setText(_translate("MainWindow", "Target:", None))
        self.LoopBack.setText(_translate("MainWindow", "Loop back", None))
        self.ResetRcvr.setText(_translate("MainWindow", "Reset Receiver", None))
        self.ProtocolDump.setText(_translate("MainWindow", "Protocol Dump", None))
        self.Ping.setText(_translate("MainWindow", "Ping", None))
        self.Controls.setTabText(self.Controls.indexOf(self.Interface), _translate("MainWindow", "Interface", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Input", None))
        self.inputIgnore.setItemText(0, _translate("MainWindow", "Passive", None))
        self.inputIgnore.setItemText(1, _translate("MainWindow", "Ignore CR", None))
        self.inputIgnore.setItemText(2, _translate("MainWindow", "Ignore LF", None))
        self.inputIgnore.setItemText(3, _translate("MainWindow", "Ignore CRLF", None))
        self.sendHex.setText(_translate("MainWindow", "Send Hex:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output", None))
        self.InBuffered.setText(_translate("MainWindow", "Buffered", None))
        self.InRaw.setText(_translate("MainWindow", "Raw", None))
        self.InRawEcho.setText(_translate("MainWindow", "Raw+Echo", None))
        self.InHex.setText(_translate("MainWindow", "Hex", None))
        self.LFnada.setText(_translate("MainWindow", "nada", None))
        self.label_2.setText(_translate("MainWindow", "Output CR as:", None))
        self.label_3.setText(_translate("MainWindow", "Output LF as:", None))
        self.CRCR.setText(_translate("MainWindow", "CR", None))
        self.CRnada.setText(_translate("MainWindow", "nada", None))
        self.LFLF.setText(_translate("MainWindow", "LF", None))
        self.LFCR.setText(_translate("MainWindow", "CR", None))
        self.CRLF.setText(_translate("MainWindow", "LF", None))
        self.Controls.setTabText(self.Controls.indexOf(self.Text), _translate("MainWindow", "Text", None))
        self.label_26.setText(_translate("MainWindow", "Target:", None))
        self.label_18.setText(_translate("MainWindow", "Entry Point:", None))
        self.label_20.setText(_translate("MainWindow", "Size:", None))
        self.label_19.setText(_translate("MainWindow", "CheckSum:", None))
        self.fileSelect.setText(_translate("MainWindow", "File:", None))
        self.label_16.setText(_translate("MainWindow", "Address Start:", None))
        self.label_17.setText(_translate("MainWindow", "Target Address:", None))
        self.header.setText(_translate("MainWindow", "+Header", None))
        self.Run.setText(_translate("MainWindow", "Run", None))
        self.endian.setText(_translate("MainWindow", "Big Endian", None))
        self.sendSrecord.setText(_translate("MainWindow", "Send", None))
        self.label_6.setText(_translate("MainWindow", "Erase", None))
        self.label_7.setText(_translate("MainWindow", "Transfer", None))
        self.label_8.setText(_translate("MainWindow", "Verify", None))
        self.Recover.setText(_translate("MainWindow", "Recover", None))
        self.Version.setText(_translate("MainWindow", "Version", None))
        self.reboot.setText(_translate("MainWindow", "Reboot", None))
        self.recoverOption.setText(_translate("MainWindow", "+recover", None))
        self.Controls.setTabText(self.Controls.indexOf(self.Transfer), _translate("MainWindow", "Transfer", None))
        self.Refresh.setText(_translate("MainWindow", "Refresh", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Choice", None))
        self.label_33.setText(_translate("MainWindow", "Running:", None))
        self.runningChoiceStatus.setText(_translate("MainWindow", "Left", None))
        self.label_34.setText(_translate("MainWindow", "Pending:", None))
        self.pendingChoiceStatus.setText(_translate("MainWindow", "Invalid", None))
        self.label_35.setText(_translate("MainWindow", "Magic:", None))
        self.magicStatus.setText(_translate("MainWindow", "Fail", None))
        self.label_36.setText(_translate("MainWindow", "Checksum:", None))
        self.checksumStatus.setText(_translate("MainWindow", "Fail", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Versions", None))
        self.label_25.setText(_translate("MainWindow", "Boot", None))
        self.label_30.setText(_translate("MainWindow", "Left App", None))
        self.label_31.setText(_translate("MainWindow", "Right App", None))
        self.Controls.setTabText(self.Controls.indexOf(self.Info), _translate("MainWindow", "Info", None))
        self.sendBoot.setText(_translate("MainWindow", "Transfer", None))
        self.label_32.setText(_translate("MainWindow", "Address:", None))
        self.run.setText(_translate("MainWindow", "Run", None))
        self.label_29.setText(_translate("MainWindow", "Size:", None))
        self.Go.setText(_translate("MainWindow", "Go", None))
        self.bootSelect.setText(_translate("MainWindow", "File:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.STMBootTransfer), _translate("MainWindow", "Download", None))
        self.Boot.setText(_translate("MainWindow", "Boot", None))
        self.Init.setText(_translate("MainWindow", "Init", None))
        self.Reconnect.setText(_translate("MainWindow", "Serial", None))
        self.Rdp.setText(_translate("MainWindow", "-Rdp", None))
        self.Getrpd.setText(_translate("MainWindow", "Get Rpd", None))
        self.Erase.setText(_translate("MainWindow", "Erase", None))
        self.Get.setText(_translate("MainWindow", "Get", None))
        self.Getid.setText(_translate("MainWindow", "Get ID", None))
        self.Pages.setText(_translate("MainWindow", "Pages", None))
        self.Write.setText(_translate("MainWindow", "Write", None))
        self.Address.setText(_translate("MainWindow", "Addr", None))
        self.Data.setText(_translate("MainWindow", "Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.STMTools), _translate("MainWindow", "Tools", None))
        self.verbose.setText(_translate("MainWindow", "Verbose", None))
        self.setDateTime.setText(_translate("MainWindow", "Set Date/Time", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "STM32F4 Boot Loader", None))
        self.sendJam.setText(_translate("MainWindow", "Program CPLD", None))
        self.sendFile.setText(_translate("MainWindow", "Write FIle", None))
        self.jamSelect.setText(_translate("MainWindow", "File:", None))
        self.label_40.setText(_translate("MainWindow", "Size:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Jam Player", None))
        self.label_72.setText(_translate("MainWindow", "Size:", None))
        self.eepromTarget.setItemText(0, _translate("MainWindow", "MotherBoard", None))
        self.label_10.setText(_translate("MainWindow", "CRC:", None))
        self.eepromSelect.setText(_translate("MainWindow", "File:", None))
        self.label.setText(_translate("MainWindow", "Target:", None))
        self.sendEeprom.setText(_translate("MainWindow", "Write EEPROM", None))
        self.readEeprom.setText(_translate("MainWindow", "Read EEPROM", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "EEPROM Script", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Port 1", None))
        self.MonitorPort1.setItemText(0, _translate("MainWindow", "(Select a Port)", None))
        self.MonitorBaud1.setItemText(0, _translate("MainWindow", "9600", None))
        self.MonitorBaud1.setItemText(1, _translate("MainWindow", "19200", None))
        self.MonitorBaud1.setItemText(2, _translate("MainWindow", "28800", None))
        self.MonitorBaud1.setItemText(3, _translate("MainWindow", "38400", None))
        self.MonitorBaud1.setItemText(4, _translate("MainWindow", "57600", None))
        self.MonitorBaud1.setItemText(5, _translate("MainWindow", "115200", None))
        self.MonitorBaud1.setItemText(6, _translate("MainWindow", "230400", None))
        self.MonitorBaud1.setItemText(7, _translate("MainWindow", "460800", None))
        self.MonitorBaud1.setItemText(8, _translate("MainWindow", "500000", None))
        self.Color1.setItemText(0, _translate("MainWindow", "white", None))
        self.Color1.setItemText(1, _translate("MainWindow", "cyan", None))
        self.Color1.setItemText(2, _translate("MainWindow", "blue", None))
        self.Color1.setItemText(3, _translate("MainWindow", "green", None))
        self.Color1.setItemText(4, _translate("MainWindow", "yellow", None))
        self.Color1.setItemText(5, _translate("MainWindow", "orange", None))
        self.Color1.setItemText(6, _translate("MainWindow", "magenta", None))
        self.Color1.setItemText(7, _translate("MainWindow", "red", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Port 2", None))
        self.MonitorPort2.setItemText(0, _translate("MainWindow", "(Select a Port)", None))
        self.MonitorBaud2.setItemText(0, _translate("MainWindow", "9600", None))
        self.MonitorBaud2.setItemText(1, _translate("MainWindow", "19200", None))
        self.MonitorBaud2.setItemText(2, _translate("MainWindow", "28800", None))
        self.MonitorBaud2.setItemText(3, _translate("MainWindow", "38400", None))
        self.MonitorBaud2.setItemText(4, _translate("MainWindow", "57600", None))
        self.MonitorBaud2.setItemText(5, _translate("MainWindow", "115200", None))
        self.MonitorBaud2.setItemText(6, _translate("MainWindow", "230400", None))
        self.MonitorBaud2.setItemText(7, _translate("MainWindow", "460800", None))
        self.MonitorBaud2.setItemText(8, _translate("MainWindow", "500000", None))
        self.Color2.setItemText(0, _translate("MainWindow", "white", None))
        self.Color2.setItemText(1, _translate("MainWindow", "cyan", None))
        self.Color2.setItemText(2, _translate("MainWindow", "blue", None))
        self.Color2.setItemText(3, _translate("MainWindow", "green", None))
        self.Color2.setItemText(4, _translate("MainWindow", "yellow", None))
        self.Color2.setItemText(5, _translate("MainWindow", "orange", None))
        self.Color2.setItemText(6, _translate("MainWindow", "magenta", None))
        self.Color2.setItemText(7, _translate("MainWindow", "red", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Monitor), _translate("MainWindow", "Monitor", None))
        self.Controls.setTabText(self.Controls.indexOf(self.Tools), _translate("MainWindow", "Tools", None))
        self.send2.setText(_translate("MainWindow", "Send", None))
        self.send6.setText(_translate("MainWindow", "Send", None))
        self.send8.setText(_translate("MainWindow", "Send", None))
        self.send7.setText(_translate("MainWindow", "Send", None))
        self.send3.setText(_translate("MainWindow", "Send", None))
        self.send1.setText(_translate("MainWindow", "Send", None))
        self.send4.setText(_translate("MainWindow", "Send", None))
        self.send5.setText(_translate("MainWindow", "Send", None))
        self.Controls.setTabText(self.Controls.indexOf(self.Phrases), _translate("MainWindow", "Phrases", None))
        self.Find.setText(_translate("MainWindow", "Find", None))
        self.FindBackwards.setText(_translate("MainWindow", "Backwards", None))
        self.label_11.setText(_translate("MainWindow", "Size", None))
        self.saveText.setText(_translate("MainWindow", "Save", None))
        self.ClearText.setText(_translate("MainWindow", "Clear", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

