# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(12, 0, 12, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Controls = QtWidgets.QTabWidget(self.centralwidget)
        self.Controls.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Controls.sizePolicy().hasHeightForWidth())
        self.Controls.setSizePolicy(sizePolicy)
        self.Controls.setMinimumSize(QtCore.QSize(390, 470))
        self.Controls.setMaximumSize(QtCore.QSize(420, 470))
        self.Controls.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Controls.setObjectName("Controls")
        self.Interface = QtWidgets.QWidget()
        self.Interface.setObjectName("Interface")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.Interface)
        self.verticalLayout_24.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_30.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_38.setSpacing(6)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.serialIf = QtWidgets.QRadioButton(self.groupBox_5)
        self.serialIf.setChecked(True)
        self.serialIf.setObjectName("serialIf")
        self.horizontalLayout_38.addWidget(self.serialIf)
        self.ethernetIf = QtWidgets.QRadioButton(self.groupBox_5)
        self.ethernetIf.setObjectName("ethernetIf")
        self.horizontalLayout_38.addWidget(self.ethernetIf)
        self.verticalLayout_14.addLayout(self.horizontalLayout_38)
        self.PortSelect = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortSelect.sizePolicy().hasHeightForWidth())
        self.PortSelect.setSizePolicy(sizePolicy)
        self.PortSelect.setMaximumSize(QtCore.QSize(150, 16777215))
        self.PortSelect.setObjectName("PortSelect")
        self.PortSelect.addItem("")
        self.verticalLayout_14.addWidget(self.PortSelect)
        self.horizontalLayout_30.addLayout(self.verticalLayout_14)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget = QtWidgets.QWidget(self.groupBox_5)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.BaudRate = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaudRate.sizePolicy().hasHeightForWidth())
        self.BaudRate.setSizePolicy(sizePolicy)
        self.BaudRate.setAcceptDrops(False)
        self.BaudRate.setFrame(True)
        self.BaudRate.setObjectName("BaudRate")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.verticalLayout_5.addWidget(self.BaudRate)
        self.toolButton = QtWidgets.QToolButton(self.widget)
        self.toolButton.setEnabled(True)
        self.toolButton.setText("N 8 1")
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_5.addWidget(self.toolButton)
        self.verticalLayout_18.addWidget(self.widget)
        self.ethernetWidget = QtWidgets.QWidget(self.groupBox_5)
        self.ethernetWidget.setVisible(False)
        self.ethernetWidget.setObjectName("ethernetWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.ethernetWidget)
        self.formLayout_4.setContentsMargins(5, 5, 5, 5)
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.portDest = QtWidgets.QLabel(self.ethernetWidget)
        self.portDest.setObjectName("portDest")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.portDest)
        self.destIp = QtWidgets.QLineEdit(self.ethernetWidget)
        self.destIp.setMinimumSize(QtCore.QSize(0, 0))
        self.destIp.setObjectName("destIp")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.destIp)
        self.portPort = QtWidgets.QLabel(self.ethernetWidget)
        self.portPort.setObjectName("portPort")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portPort)
        self.ipPort = QtWidgets.QLineEdit(self.ethernetWidget)
        self.ipPort.setMinimumSize(QtCore.QSize(0, 0))
        self.ipPort.setObjectName("ipPort")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ipPort)
        self.verticalLayout_18.addWidget(self.ethernetWidget)
        self.horizontalLayout_30.addLayout(self.verticalLayout_18)
        self.horizontalLayout_30.setStretch(0, 1)
        self.horizontalLayout_30.setStretch(1, 2)
        self.verticalLayout_24.addWidget(self.groupBox_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_121 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_121.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_121.setSpacing(6)
        self.verticalLayout_121.setObjectName("verticalLayout_121")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_151 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_151.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_151.setSpacing(6)
        self.horizontalLayout_151.setObjectName("horizontalLayout_151")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Serial1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.Serial1.setChecked(False)
        self.Serial1.setObjectName("Serial1")
        self.serialProtocol = QtWidgets.QButtonGroup(MainWindow)
        self.serialProtocol.setObjectName("serialProtocol")
        self.serialProtocol.addButton(self.Serial1)
        self.verticalLayout_4.addWidget(self.Serial1)
        self.SFP = QtWidgets.QRadioButton(self.groupBox_2)
        self.SFP.setChecked(True)
        self.SFP.setObjectName("SFP")
        self.serialProtocol.addButton(self.SFP)
        self.verticalLayout_4.addWidget(self.SFP)
        self.AT = QtWidgets.QRadioButton(self.groupBox_2)
        self.AT.setObjectName("AT")
        self.serialProtocol.addButton(self.AT)
        self.verticalLayout_4.addWidget(self.AT)
        self.horizontalLayout_151.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_151.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_151)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_26.addWidget(self.label_5)
        self.whoFrom = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whoFrom.sizePolicy().hasHeightForWidth())
        self.whoFrom.setSizePolicy(sizePolicy)
        self.whoFrom.setMinimumSize(QtCore.QSize(130, 26))
        self.whoFrom.setMaximumSize(QtCore.QSize(130, 26))
        self.whoFrom.setObjectName("whoFrom")
        self.horizontalLayout_26.addWidget(self.whoFrom)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_28.setSpacing(6)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_28.addWidget(self.label_4)
        self.whoTo = QtWidgets.QComboBox(self.groupBox_2)
        self.whoTo.setMinimumSize(QtCore.QSize(130, 26))
        self.whoTo.setMaximumSize(QtCore.QSize(130, 26))
        self.whoTo.setObjectName("whoTo")
        self.horizontalLayout_28.addWidget(self.whoTo)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.LoopBack = QtWidgets.QCheckBox(self.groupBox_2)
        self.LoopBack.setObjectName("LoopBack")
        self.gridLayout_6.addWidget(self.LoopBack, 1, 0, 1, 1)
        self.ResetRcvr = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetRcvr.sizePolicy().hasHeightForWidth())
        self.ResetRcvr.setSizePolicy(sizePolicy)
        self.ResetRcvr.setObjectName("ResetRcvr")
        self.gridLayout_6.addWidget(self.ResetRcvr, 1, 3, 1, 1)
        self.ProtocolDump = QtWidgets.QCheckBox(self.groupBox_2)
        self.ProtocolDump.setObjectName("ProtocolDump")
        self.gridLayout_6.addWidget(self.ProtocolDump, 0, 0, 1, 1)
        self.Ping = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ping.sizePolicy().hasHeightForWidth())
        self.Ping.setSizePolicy(sizePolicy)
        self.Ping.setObjectName("Ping")
        self.gridLayout_6.addWidget(self.Ping, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.verticalLayout_121.addLayout(self.verticalLayout_3)
        self.verticalLayout_24.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem2)
        self.Controls.addTab(self.Interface, "")
        self.Text = QtWidgets.QWidget()
        self.Text.setObjectName("Text")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.Text)
        self.verticalLayout_23.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Text)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_22.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.inputIgnore = QtWidgets.QComboBox(self.groupBox_6)
        self.inputIgnore.setObjectName("inputIgnore")
        self.inputIgnore.addItem("")
        self.inputIgnore.addItem("")
        self.inputIgnore.addItem("")
        self.inputIgnore.addItem("")
        self.horizontalLayout_12.addWidget(self.inputIgnore)
        self.line = QtWidgets.QFrame(self.groupBox_6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_12.addWidget(self.line)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.sendHex = QtWidgets.QPushButton(self.groupBox_6)
        self.sendHex.setObjectName("sendHex")
        self.horizontalLayout_12.addWidget(self.sendHex)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.hexNum = QtWidgets.QLineEdit(self.groupBox_6)
        self.hexNum.setMinimumSize(QtCore.QSize(40, 0))
        self.hexNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hexNum.setObjectName("hexNum")
        self.horizontalLayout_12.addWidget(self.hexNum)
        self.verticalLayout_22.addLayout(self.horizontalLayout_12)
        self.verticalLayout_23.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(self.Text)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InBuffered = QtWidgets.QRadioButton(self.groupBox)
        self.InBuffered.setObjectName("InBuffered")
        self.horizontalLayout_3.addWidget(self.InBuffered)
        self.InRaw = QtWidgets.QRadioButton(self.groupBox)
        self.InRaw.setChecked(True)
        self.InRaw.setObjectName("InRaw")
        self.horizontalLayout_3.addWidget(self.InRaw)
        self.InRawEcho = QtWidgets.QRadioButton(self.groupBox)
        self.InRawEcho.setObjectName("InRawEcho")
        self.horizontalLayout_3.addWidget(self.InRawEcho)
        self.InHex = QtWidgets.QRadioButton(self.groupBox)
        self.InHex.setObjectName("InHex")
        self.horizontalLayout_3.addWidget(self.InHex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.LFnada = QtWidgets.QRadioButton(self.groupBox)
        self.LFnada.setChecked(True)
        self.LFnada.setObjectName("LFnada")
        self.LfOut = QtWidgets.QButtonGroup(MainWindow)
        self.LfOut.setObjectName("LfOut")
        self.LfOut.addButton(self.LFnada)
        self.gridLayout.addWidget(self.LFnada, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.CRCR = QtWidgets.QRadioButton(self.groupBox)
        self.CRCR.setChecked(False)
        self.CRCR.setObjectName("CRCR")
        self.CrOut = QtWidgets.QButtonGroup(MainWindow)
        self.CrOut.setObjectName("CrOut")
        self.CrOut.addButton(self.CRCR)
        self.gridLayout.addWidget(self.CRCR, 0, 3, 1, 1)
        self.CRnada = QtWidgets.QRadioButton(self.groupBox)
        self.CRnada.setObjectName("CRnada")
        self.CrOut.addButton(self.CRnada)
        self.gridLayout.addWidget(self.CRnada, 0, 1, 1, 1)
        self.LFLF = QtWidgets.QRadioButton(self.groupBox)
        self.LFLF.setObjectName("LFLF")
        self.LfOut.addButton(self.LFLF)
        self.gridLayout.addWidget(self.LFLF, 1, 2, 1, 1)
        self.LFCR = QtWidgets.QRadioButton(self.groupBox)
        self.LFCR.setObjectName("LFCR")
        self.LfOut.addButton(self.LFCR)
        self.gridLayout.addWidget(self.LFCR, 1, 3, 1, 1)
        self.CRLF = QtWidgets.QRadioButton(self.groupBox)
        self.CRLF.setChecked(False)
        self.CRLF.setObjectName("CRLF")
        self.CrOut.addButton(self.CRLF)
        self.gridLayout.addWidget(self.CRLF, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.linewrap = QtWidgets.QCheckBox(self.groupBox)
        self.linewrap.setChecked(True)
        self.linewrap.setObjectName("linewrap")
        self.verticalLayout_2.addWidget(self.linewrap)
        self.verticalLayout_23.addWidget(self.groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem6)
        self.Controls.addTab(self.Text, "")
        self.Transfer = QtWidgets.QWidget()
        self.Transfer.setObjectName("Transfer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Transfer)
        self.verticalLayout_9.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.srecordTargets = QtWidgets.QFrame(self.Transfer)
        self.srecordTargets.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.srecordTargets.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.srecordTargets.setObjectName("srecordTargets")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.srecordTargets)
        self.horizontalLayout_29.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_29.setSpacing(6)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_26 = QtWidgets.QLabel(self.srecordTargets)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_7.addWidget(self.label_26)
        self.targetSelect = QtWidgets.QComboBox(self.srecordTargets)
        self.targetSelect.setObjectName("targetSelect")
        self.horizontalLayout_7.addWidget(self.targetSelect)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.srecordTargets)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 4, 0, 1, 1)
        self.srecordFile = QtWidgets.QLineEdit(self.srecordTargets)
        self.srecordFile.setObjectName("srecordFile")
        self.gridLayout_3.addWidget(self.srecordFile, 0, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.srecordTargets)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.srecordTargets)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 5, 0, 1, 1)
        self.fileSelect = QtWidgets.QPushButton(self.srecordTargets)
        self.fileSelect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSelect.sizePolicy().hasHeightForWidth())
        self.fileSelect.setSizePolicy(sizePolicy)
        self.fileSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.fileSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.fileSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileSelect.setObjectName("fileSelect")
        self.gridLayout_3.addWidget(self.fileSelect, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.size = QtWidgets.QLineEdit(self.srecordTargets)
        self.size.setObjectName("size")
        self.gridLayout_3.addWidget(self.size, 3, 1, 1, 1)
        self.entryPoint = QtWidgets.QLineEdit(self.srecordTargets)
        self.entryPoint.setEnabled(False)
        self.entryPoint.setObjectName("entryPoint")
        self.gridLayout_3.addWidget(self.entryPoint, 4, 1, 1, 1)
        self.checkSum = QtWidgets.QLineEdit(self.srecordTargets)
        self.checkSum.setEnabled(False)
        self.checkSum.setObjectName("checkSum")
        self.gridLayout_3.addWidget(self.checkSum, 5, 1, 1, 1)
        self.addressStart = QtWidgets.QLineEdit(self.srecordTargets)
        self.addressStart.setEnabled(False)
        self.addressStart.setMinimumSize(QtCore.QSize(60, 0))
        self.addressStart.setObjectName("addressStart")
        self.gridLayout_3.addWidget(self.addressStart, 2, 1, 1, 1)
        self.targetAddress = QtWidgets.QLineEdit(self.srecordTargets)
        self.targetAddress.setObjectName("targetAddress")
        self.gridLayout_3.addWidget(self.targetAddress, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.srecordTargets)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.srecordTargets)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.header = QtWidgets.QCheckBox(self.srecordTargets)
        self.header.setObjectName("header")
        self.gridLayout_3.addWidget(self.header, 1, 2, 1, 1)
        self.Run = QtWidgets.QPushButton(self.srecordTargets)
        self.Run.setObjectName("Run")
        self.gridLayout_3.addWidget(self.Run, 4, 2, 1, 1)
        self.endian = QtWidgets.QCheckBox(self.srecordTargets)
        self.endian.setChecked(True)
        self.endian.setObjectName("endian")
        self.gridLayout_3.addWidget(self.endian, 2, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_29.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addWidget(self.srecordTargets)
        self.frame_2 = QtWidgets.QFrame(self.Transfer)
        self.frame_2.setMinimumSize(QtCore.QSize(261, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(330, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_20.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.sendSrecord = QtWidgets.QPushButton(self.frame_2)
        self.sendSrecord.setMinimumSize(QtCore.QSize(71, 32))
        self.sendSrecord.setMaximumSize(QtCore.QSize(71, 32))
        self.sendSrecord.setObjectName("sendSrecord")
        self.horizontalLayout_20.addWidget(self.sendSrecord)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setMinimumSize(QtCore.QSize(241, 23))
        self.progressBar.setMaximumSize(QtCore.QSize(241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_7.addWidget(self.progressBar)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_19.setSpacing(1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.eraseLed = QtWidgets.QFrame(self.frame_2)
        self.eraseLed.setEnabled(False)
        self.eraseLed.setMinimumSize(QtCore.QSize(12, 10))
        self.eraseLed.setMaximumSize(QtCore.QSize(12, 10))
        self.eraseLed.setStyleSheet("background-color: green;")
        self.eraseLed.setFrameShape(QtWidgets.QFrame.Panel)
        self.eraseLed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eraseLed.setLineWidth(3)
        self.eraseLed.setMidLineWidth(3)
        self.eraseLed.setObjectName("eraseLed")
        self.horizontalLayout_9.addWidget(self.eraseLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        self.transferLed = QtWidgets.QFrame(self.frame_2)
        self.transferLed.setEnabled(False)
        self.transferLed.setMinimumSize(QtCore.QSize(12, 10))
        self.transferLed.setMaximumSize(QtCore.QSize(12, 10))
        self.transferLed.setStyleSheet("background-color: rgb(255, 204, 102);\n"
"")
        self.transferLed.setFrameShape(QtWidgets.QFrame.Panel)
        self.transferLed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transferLed.setLineWidth(3)
        self.transferLed.setMidLineWidth(3)
        self.transferLed.setObjectName("transferLed")
        self.horizontalLayout_17.addWidget(self.transferLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8)
        self.verifyLed = QtWidgets.QToolButton(self.frame_2)
        self.verifyLed.setMaximumSize(QtCore.QSize(12, 10))
        self.verifyLed.setStyleSheet("border: none;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.852217 rgba(241, 0, 0, 255), stop:1 rgba(255, 161, 161, 255));")
        self.verifyLed.setText("")
        self.verifyLed.setObjectName("verifyLed")
        self.horizontalLayout_16.addWidget(self.verifyLed)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_27.setSpacing(1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Recover = QtWidgets.QPushButton(self.Transfer)
        self.Recover.setObjectName("Recover")
        self.horizontalLayout_27.addWidget(self.Recover)
        self.Version = QtWidgets.QPushButton(self.Transfer)
        self.Version.setIconSize(QtCore.QSize(16, 16))
        self.Version.setObjectName("Version")
        self.horizontalLayout_27.addWidget(self.Version)
        self.frame_3 = QtWidgets.QFrame(self.Transfer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_21.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.reboot = QtWidgets.QPushButton(self.frame_3)
        self.reboot.setObjectName("reboot")
        self.horizontalLayout_21.addWidget(self.reboot)
        self.recoverOption = QtWidgets.QCheckBox(self.frame_3)
        self.recoverOption.setObjectName("recoverOption")
        self.horizontalLayout_21.addWidget(self.recoverOption)
        self.horizontalLayout_27.addWidget(self.frame_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_27)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.Controls.addTab(self.Transfer, "")
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Info)
        self.verticalLayout_10.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.Refresh = QtWidgets.QPushButton(self.Info)
        self.Refresh.setObjectName("Refresh")
        self.horizontalLayout_24.addWidget(self.Refresh)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Info)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.runningChoiceStatus = QtWidgets.QLabel(self.groupBox_3)
        self.runningChoiceStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.runningChoiceStatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.runningChoiceStatus.setObjectName("runningChoiceStatus")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.runningChoiceStatus)
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.pendingChoiceStatus = QtWidgets.QLabel(self.groupBox_3)
        self.pendingChoiceStatus.setMinimumSize(QtCore.QSize(50, 0))
        self.pendingChoiceStatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pendingChoiceStatus.setObjectName("pendingChoiceStatus")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pendingChoiceStatus)
        self.horizontalLayout_23.addWidget(self.groupBox_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(12, 12, 12, 12)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_35 = QtWidgets.QLabel(self.Info)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.magicStatus = QtWidgets.QLabel(self.Info)
        self.magicStatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.magicStatus.setObjectName("magicStatus")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.magicStatus)
        self.label_36 = QtWidgets.QLabel(self.Info)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.checksumStatus = QtWidgets.QLabel(self.Info)
        self.checksumStatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checksumStatus.setObjectName("checksumStatus")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checksumStatus)
        self.horizontalLayout_23.addLayout(self.formLayout_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Info)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_25.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 0, 1, 1)
        self.bootVersion = QtWidgets.QLineEdit(self.groupBox_4)
        self.bootVersion.setObjectName("bootVersion")
        self.gridLayout_4.addWidget(self.bootVersion, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 1, 0, 1, 1)
        self.leftAppVersion = QtWidgets.QLineEdit(self.groupBox_4)
        self.leftAppVersion.setObjectName("leftAppVersion")
        self.gridLayout_4.addWidget(self.leftAppVersion, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.rightAppVersion = QtWidgets.QLineEdit(self.groupBox_4)
        self.rightAppVersion.setObjectName("rightAppVersion")
        self.gridLayout_4.addWidget(self.rightAppVersion, 2, 1, 1, 1)
        self.horizontalLayout_25.addLayout(self.gridLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 141, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.Controls.addTab(self.Info, "")
        self.Tools = QtWidgets.QWidget()
        self.Tools.setObjectName("Tools")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Tools)
        self.verticalLayout_15.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.toolBox = QtWidgets.QToolBox(self.Tools)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 360, 281))
        self.page.setObjectName("page")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_19.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.STMBootTransfer = QtWidgets.QWidget()
        self.STMBootTransfer.setObjectName("STMBootTransfer")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.STMBootTransfer)
        self.gridLayout_10.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.sendBoot = QtWidgets.QPushButton(self.STMBootTransfer)
        self.sendBoot.setMinimumSize(QtCore.QSize(71, 32))
        self.sendBoot.setMaximumSize(QtCore.QSize(83, 32))
        self.sendBoot.setObjectName("sendBoot")
        self.gridLayout_10.addWidget(self.sendBoot, 7, 0, 1, 1)
        self.bootSize = QtWidgets.QLineEdit(self.STMBootTransfer)
        self.bootSize.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bootSize.setReadOnly(True)
        self.bootSize.setObjectName("bootSize")
        self.gridLayout_10.addWidget(self.bootSize, 6, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.STMBootTransfer)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 2, 0, 1, 1)
        self.run = QtWidgets.QCheckBox(self.STMBootTransfer)
        self.run.setChecked(True)
        self.run.setObjectName("run")
        self.gridLayout_10.addWidget(self.run, 0, 3, 1, 1)
        self.bootStart = QtWidgets.QLineEdit(self.STMBootTransfer)
        self.bootStart.setObjectName("bootStart")
        self.gridLayout_10.addWidget(self.bootStart, 2, 1, 1, 1)
        self.bootFile = QtWidgets.QLineEdit(self.STMBootTransfer)
        self.bootFile.setObjectName("bootFile")
        self.gridLayout_10.addWidget(self.bootFile, 0, 1, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.STMBootTransfer)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 6, 0, 1, 1)
        self.bootLoaderProgressBar = QtWidgets.QProgressBar(self.STMBootTransfer)
        self.bootLoaderProgressBar.setMinimumSize(QtCore.QSize(200, 23))
        self.bootLoaderProgressBar.setMaximumSize(QtCore.QSize(200, 23))
        self.bootLoaderProgressBar.setProperty("value", 0)
        self.bootLoaderProgressBar.setObjectName("bootLoaderProgressBar")
        self.gridLayout_10.addWidget(self.bootLoaderProgressBar, 7, 1, 1, 3)
        self.Go = QtWidgets.QPushButton(self.STMBootTransfer)
        self.Go.setObjectName("Go")
        self.gridLayout_10.addWidget(self.Go, 2, 3, 1, 1)
        self.bootSelect = QtWidgets.QPushButton(self.STMBootTransfer)
        self.bootSelect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bootSelect.sizePolicy().hasHeightForWidth())
        self.bootSelect.setSizePolicy(sizePolicy)
        self.bootSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.bootSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.bootSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bootSelect.setObjectName("bootSelect")
        self.gridLayout_10.addWidget(self.bootSelect, 0, 0, 1, 1)
        self.tabWidget.addTab(self.STMBootTransfer, "")
        self.STMTools = QtWidgets.QWidget()
        self.STMTools.setObjectName("STMTools")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.STMTools)
        self.gridLayout_11.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Boot = QtWidgets.QPushButton(self.STMTools)
        self.Boot.setObjectName("Boot")
        self.gridLayout_11.addWidget(self.Boot, 0, 0, 1, 1)
        self.Init = QtWidgets.QPushButton(self.STMTools)
        self.Init.setObjectName("Init")
        self.gridLayout_11.addWidget(self.Init, 0, 1, 1, 1)
        self.Reconnect = QtWidgets.QPushButton(self.STMTools)
        self.Reconnect.setObjectName("Reconnect")
        self.gridLayout_11.addWidget(self.Reconnect, 0, 2, 1, 1)
        self.Rdp = QtWidgets.QPushButton(self.STMTools)
        self.Rdp.setObjectName("Rdp")
        self.gridLayout_11.addWidget(self.Rdp, 1, 0, 1, 1)
        self.Getrpd = QtWidgets.QPushButton(self.STMTools)
        self.Getrpd.setObjectName("Getrpd")
        self.gridLayout_11.addWidget(self.Getrpd, 1, 1, 1, 1)
        self.Erase = QtWidgets.QPushButton(self.STMTools)
        self.Erase.setObjectName("Erase")
        self.gridLayout_11.addWidget(self.Erase, 1, 2, 1, 1)
        self.Get = QtWidgets.QPushButton(self.STMTools)
        self.Get.setObjectName("Get")
        self.gridLayout_11.addWidget(self.Get, 2, 0, 1, 1)
        self.Getid = QtWidgets.QPushButton(self.STMTools)
        self.Getid.setObjectName("Getid")
        self.gridLayout_11.addWidget(self.Getid, 2, 1, 1, 1)
        self.Pages = QtWidgets.QPushButton(self.STMTools)
        self.Pages.setObjectName("Pages")
        self.gridLayout_11.addWidget(self.Pages, 2, 2, 1, 1)
        self.Write = QtWidgets.QPushButton(self.STMTools)
        self.Write.setObjectName("Write")
        self.gridLayout_11.addWidget(self.Write, 3, 0, 1, 1)
        self.Address = QtWidgets.QPushButton(self.STMTools)
        self.Address.setObjectName("Address")
        self.gridLayout_11.addWidget(self.Address, 3, 1, 1, 1)
        self.Data = QtWidgets.QPushButton(self.STMTools)
        self.Data.setObjectName("Data")
        self.gridLayout_11.addWidget(self.Data, 3, 2, 1, 1)
        self.tabWidget.addTab(self.STMTools, "")
        self.verticalLayout_19.addWidget(self.tabWidget)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verbose = QtWidgets.QCheckBox(self.page)
        self.verbose.setObjectName("verbose")
        self.verticalLayout_17.addWidget(self.verbose)
        self.setDateTime = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setDateTime.sizePolicy().hasHeightForWidth())
        self.setDateTime.setSizePolicy(sizePolicy)
        self.setDateTime.setObjectName("setDateTime")
        self.verticalLayout_17.addWidget(self.setDateTime)
        self.verticalLayout_19.addLayout(self.verticalLayout_17)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 265, 162))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_13.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.jamFile = QtWidgets.QLineEdit(self.page_2)
        self.jamFile.setObjectName("jamFile")
        self.gridLayout_12.addWidget(self.jamFile, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sendJam = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendJam.sizePolicy().hasHeightForWidth())
        self.sendJam.setSizePolicy(sizePolicy)
        self.sendJam.setMinimumSize(QtCore.QSize(0, 0))
        self.sendJam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendJam.setObjectName("sendJam")
        self.horizontalLayout_2.addWidget(self.sendJam)
        self.sendFile = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendFile.sizePolicy().hasHeightForWidth())
        self.sendFile.setSizePolicy(sizePolicy)
        self.sendFile.setObjectName("sendFile")
        self.horizontalLayout_2.addWidget(self.sendFile)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.jamSelect = QtWidgets.QPushButton(self.page_2)
        self.jamSelect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jamSelect.sizePolicy().hasHeightForWidth())
        self.jamSelect.setSizePolicy(sizePolicy)
        self.jamSelect.setMinimumSize(QtCore.QSize(0, 0))
        self.jamSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jamSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jamSelect.setObjectName("jamSelect")
        self.gridLayout_12.addWidget(self.jamSelect, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.page_2)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 1, 0, 1, 1)
        self.jamLoaderProgressBar = QtWidgets.QProgressBar(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jamLoaderProgressBar.sizePolicy().hasHeightForWidth())
        self.jamLoaderProgressBar.setSizePolicy(sizePolicy)
        self.jamLoaderProgressBar.setMinimumSize(QtCore.QSize(130, 23))
        self.jamLoaderProgressBar.setMaximumSize(QtCore.QSize(16777215, 23))
        self.jamLoaderProgressBar.setProperty("value", 0)
        self.jamLoaderProgressBar.setInvertedAppearance(True)
        self.jamLoaderProgressBar.setObjectName("jamLoaderProgressBar")
        self.gridLayout_12.addWidget(self.jamLoaderProgressBar, 2, 0, 1, 2)
        self.jamSize = QtWidgets.QLineEdit(self.page_2)
        self.jamSize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jamSize.setReadOnly(True)
        self.jamSize.setObjectName("jamSize")
        self.gridLayout_12.addWidget(self.jamSize, 1, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_12)
        spacerItem15 = QtWidgets.QSpacerItem(20, 116, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem15)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 308, 221))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_72 = QtWidgets.QLabel(self.page_3)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_7.addWidget(self.label_72, 2, 0, 1, 1)
        self.eepromSize = QtWidgets.QLineEdit(self.page_3)
        self.eepromSize.setMaximumSize(QtCore.QSize(120, 16777215))
        self.eepromSize.setReadOnly(True)
        self.eepromSize.setObjectName("eepromSize")
        self.gridLayout_7.addWidget(self.eepromSize, 2, 1, 1, 1)
        self.eepromFile = QtWidgets.QLineEdit(self.page_3)
        self.eepromFile.setObjectName("eepromFile")
        self.gridLayout_7.addWidget(self.eepromFile, 1, 1, 1, 1)
        self.crcStatus = QtWidgets.QLabel(self.page_3)
        self.crcStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.crcStatus.setText("")
        self.crcStatus.setObjectName("crcStatus")
        self.gridLayout_7.addWidget(self.crcStatus, 3, 2, 1, 1)
        self.eepromTarget = QtWidgets.QComboBox(self.page_3)
        self.eepromTarget.setObjectName("eepromTarget")
        self.eepromTarget.addItem("")
        self.gridLayout_7.addWidget(self.eepromTarget, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 3, 0, 1, 1)
        self.crcValue = QtWidgets.QLineEdit(self.page_3)
        self.crcValue.setMaximumSize(QtCore.QSize(120, 16777215))
        self.crcValue.setReadOnly(True)
        self.crcValue.setPlaceholderText("")
        self.crcValue.setObjectName("crcValue")
        self.gridLayout_7.addWidget(self.crcValue, 3, 1, 1, 1)
        self.eepromSelect = QtWidgets.QPushButton(self.page_3)
        self.eepromSelect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eepromSelect.sizePolicy().hasHeightForWidth())
        self.eepromSelect.setSizePolicy(sizePolicy)
        self.eepromSelect.setMinimumSize(QtCore.QSize(70, 32))
        self.eepromSelect.setMaximumSize(QtCore.QSize(70, 32))
        self.eepromSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eepromSelect.setObjectName("eepromSelect")
        self.gridLayout_7.addWidget(self.eepromSelect, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.eepromLoaderProgressBar = QtWidgets.QProgressBar(self.page_3)
        self.eepromLoaderProgressBar.setMinimumSize(QtCore.QSize(200, 23))
        self.eepromLoaderProgressBar.setMaximumSize(QtCore.QSize(1000, 23))
        self.eepromLoaderProgressBar.setProperty("value", 0)
        self.eepromLoaderProgressBar.setObjectName("eepromLoaderProgressBar")
        self.gridLayout_7.addWidget(self.eepromLoaderProgressBar, 4, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendEeprom = QtWidgets.QPushButton(self.page_3)
        self.sendEeprom.setMinimumSize(QtCore.QSize(0, 0))
        self.sendEeprom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendEeprom.setObjectName("sendEeprom")
        self.horizontalLayout.addWidget(self.sendEeprom)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.readEeprom = QtWidgets.QPushButton(self.page_3)
        self.readEeprom.setEnabled(False)
        self.readEeprom.setObjectName("readEeprom")
        self.horizontalLayout.addWidget(self.readEeprom)
        self.gridLayout_7.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem17, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.toolBox.addItem(self.page_3, "")
        self.Monitor = QtWidgets.QWidget()
        self.Monitor.setGeometry(QtCore.QRect(0, 0, 296, 225))
        self.Monitor.setObjectName("Monitor")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Monitor)
        self.verticalLayout_16.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Monitor)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.MonitorPort1 = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort1.sizePolicy().hasHeightForWidth())
        self.MonitorPort1.setSizePolicy(sizePolicy)
        self.MonitorPort1.setObjectName("MonitorPort1")
        self.MonitorPort1.addItem("")
        self.gridLayout_5.addWidget(self.MonitorPort1, 0, 0, 1, 1)
        self.MonitorBaud1 = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud1.sizePolicy().hasHeightForWidth())
        self.MonitorBaud1.setSizePolicy(sizePolicy)
        self.MonitorBaud1.setAcceptDrops(False)
        self.MonitorBaud1.setFrame(True)
        self.MonitorBaud1.setObjectName("MonitorBaud1")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.gridLayout_5.addWidget(self.MonitorBaud1, 0, 1, 1, 1)
        self.Color1 = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color1.sizePolicy().hasHeightForWidth())
        self.Color1.setSizePolicy(sizePolicy)
        self.Color1.setAcceptDrops(False)
        self.Color1.setFrame(True)
        self.Color1.setObjectName("Color1")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.Color1.addItem("")
        self.gridLayout_5.addWidget(self.Color1, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.Monitor)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.MonitorPort2 = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort2.sizePolicy().hasHeightForWidth())
        self.MonitorPort2.setSizePolicy(sizePolicy)
        self.MonitorPort2.setObjectName("MonitorPort2")
        self.MonitorPort2.addItem("")
        self.gridLayout_8.addWidget(self.MonitorPort2, 0, 0, 1, 1)
        self.MonitorBaud2 = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud2.sizePolicy().hasHeightForWidth())
        self.MonitorBaud2.setSizePolicy(sizePolicy)
        self.MonitorBaud2.setAcceptDrops(False)
        self.MonitorBaud2.setFrame(True)
        self.MonitorBaud2.setObjectName("MonitorBaud2")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.gridLayout_8.addWidget(self.MonitorBaud2, 0, 1, 1, 1)
        self.Color2 = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color2.sizePolicy().hasHeightForWidth())
        self.Color2.setSizePolicy(sizePolicy)
        self.Color2.setAcceptDrops(False)
        self.Color2.setFrame(True)
        self.Color2.setObjectName("Color2")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.Color2.addItem("")
        self.gridLayout_8.addWidget(self.Color2, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_8)
        spacerItem19 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem19)
        self.toolBox.addItem(self.Monitor, "")
        self.verticalLayout_15.addWidget(self.toolBox)
        self.Controls.addTab(self.Tools, "")
        self.Phrases = QtWidgets.QWidget()
        self.Phrases.setObjectName("Phrases")
        self.layoutWidget_4 = QtWidgets.QWidget(self.Phrases)
        self.layoutWidget_4.setGeometry(QtCore.QRect(7, 10, 372, 286))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.phrase1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase1.sizePolicy().hasHeightForWidth())
        self.phrase1.setSizePolicy(sizePolicy)
        self.phrase1.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase1.setObjectName("phrase1")
        self.gridLayout_2.addWidget(self.phrase1, 1, 0, 1, 1)
        self.phrase2 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(127)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase2.sizePolicy().hasHeightForWidth())
        self.phrase2.setSizePolicy(sizePolicy)
        self.phrase2.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase2.setObjectName("phrase2")
        self.gridLayout_2.addWidget(self.phrase2, 0, 0, 1, 1)
        self.phrase4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase4.sizePolicy().hasHeightForWidth())
        self.phrase4.setSizePolicy(sizePolicy)
        self.phrase4.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase4.setObjectName("phrase4")
        self.gridLayout_2.addWidget(self.phrase4, 3, 0, 1, 1)
        self.send2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send2.setObjectName("send2")
        self.gridLayout_2.addWidget(self.send2, 0, 1, 1, 1)
        self.phrase3 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase3.sizePolicy().hasHeightForWidth())
        self.phrase3.setSizePolicy(sizePolicy)
        self.phrase3.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase3.setObjectName("phrase3")
        self.gridLayout_2.addWidget(self.phrase3, 2, 0, 1, 1)
        self.send6 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send6.setObjectName("send6")
        self.gridLayout_2.addWidget(self.send6, 5, 1, 1, 1)
        self.phrase6 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase6.sizePolicy().hasHeightForWidth())
        self.phrase6.setSizePolicy(sizePolicy)
        self.phrase6.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase6.setObjectName("phrase6")
        self.gridLayout_2.addWidget(self.phrase6, 5, 0, 1, 1)
        self.send8 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send8.setObjectName("send8")
        self.gridLayout_2.addWidget(self.send8, 7, 1, 1, 1)
        self.send7 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send7.setObjectName("send7")
        self.gridLayout_2.addWidget(self.send7, 6, 1, 1, 1)
        self.send3 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send3.setObjectName("send3")
        self.gridLayout_2.addWidget(self.send3, 2, 1, 1, 1)
        self.phrase5 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase5.sizePolicy().hasHeightForWidth())
        self.phrase5.setSizePolicy(sizePolicy)
        self.phrase5.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase5.setObjectName("phrase5")
        self.gridLayout_2.addWidget(self.phrase5, 4, 0, 1, 1)
        self.send1 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send1.setObjectName("send1")
        self.gridLayout_2.addWidget(self.send1, 1, 1, 1, 1)
        self.phrase8 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase8.sizePolicy().hasHeightForWidth())
        self.phrase8.setSizePolicy(sizePolicy)
        self.phrase8.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase8.setObjectName("phrase8")
        self.gridLayout_2.addWidget(self.phrase8, 7, 0, 1, 1)
        self.phrase7 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrase7.sizePolicy().hasHeightForWidth())
        self.phrase7.setSizePolicy(sizePolicy)
        self.phrase7.setMinimumSize(QtCore.QSize(290, 0))
        self.phrase7.setObjectName("phrase7")
        self.gridLayout_2.addWidget(self.phrase7, 6, 0, 1, 1)
        self.send4 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send4.setObjectName("send4")
        self.gridLayout_2.addWidget(self.send4, 3, 1, 1, 1)
        self.send5 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.send5.setObjectName("send5")
        self.gridLayout_2.addWidget(self.send5, 4, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 290)
        self.gridLayout_2.setColumnStretch(0, 290)
        self.Controls.addTab(self.Phrases, "")
        self.verticalLayout_11.addWidget(self.Controls)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_51.setSpacing(0)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.textEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textEdit.setMinimumSize(QtCore.QSize(601, 471))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setItalic(False)
        font.setKerning(False)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("font: cyan;")
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.textEdit.setPlainText("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_51.addWidget(self.textEdit)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(12, 6, 12, 6)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Find = QtWidgets.QPushButton(self.frame)
        self.Find.setObjectName("Find")
        self.horizontalLayout_8.addWidget(self.Find)
        self.FindText = QtWidgets.QLineEdit(self.frame)
        self.FindText.setObjectName("FindText")
        self.horizontalLayout_8.addWidget(self.FindText)
        self.FindBackwards = QtWidgets.QCheckBox(self.frame)
        self.FindBackwards.setObjectName("FindBackwards")
        self.horizontalLayout_8.addWidget(self.FindBackwards)
        self.horizontalLayout_35.addWidget(self.frame)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem20)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setContentsMargins(12, 6, 12, 6)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.fontSize = QtWidgets.QSpinBox(self.frame_4)
        self.fontSize.setMinimum(5)
        self.fontSize.setMaximum(40)
        self.fontSize.setProperty("value", 12)
        self.fontSize.setObjectName("fontSize")
        self.horizontalLayout_11.addWidget(self.fontSize)
        self.horizontalLayout_35.addWidget(self.frame_4)
        self.saveText = QtWidgets.QPushButton(self.centralwidget)
        self.saveText.setObjectName("saveText")
        self.horizontalLayout_35.addWidget(self.saveText)
        self.ClearText = QtWidgets.QPushButton(self.centralwidget)
        self.ClearText.setMaximumSize(QtCore.QSize(107, 32))
        self.ClearText.setObjectName("ClearText")
        self.horizontalLayout_35.addWidget(self.ClearText)
        self.verticalLayout_51.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_15.addLayout(self.verticalLayout_51)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Controls.setCurrentIndex(0)
        self.BaudRate.setCurrentIndex(5)
        self.targetSelect.setCurrentIndex(-1)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.MonitorBaud1.setCurrentIndex(5)
        self.Color1.setCurrentIndex(4)
        self.MonitorBaud2.setCurrentIndex(5)
        self.Color2.setCurrentIndex(6)
        self.ClearText.clicked.connect(self.textEdit.clear)
        self.ethernetIf.pressed.connect(self.widget.hide)
        self.ethernetIf.pressed.connect(self.ethernetWidget.show)
        self.serialIf.pressed.connect(self.widget.show)
        self.serialIf.pressed.connect(self.ethernetWidget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Port"))
        self.serialIf.setText(_translate("MainWindow", "Serial"))
        self.ethernetIf.setText(_translate("MainWindow", "Ethernet"))
        self.PortSelect.setItemText(0, _translate("MainWindow", "(Select host Port)"))
        self.BaudRate.setItemText(0, _translate("MainWindow", "9600"))
        self.BaudRate.setItemText(1, _translate("MainWindow", "19200"))
        self.BaudRate.setItemText(2, _translate("MainWindow", "28800"))
        self.BaudRate.setItemText(3, _translate("MainWindow", "38400"))
        self.BaudRate.setItemText(4, _translate("MainWindow", "57600"))
        self.BaudRate.setItemText(5, _translate("MainWindow", "115200"))
        self.BaudRate.setItemText(6, _translate("MainWindow", "230400"))
        self.BaudRate.setItemText(7, _translate("MainWindow", "460800"))
        self.BaudRate.setItemText(8, _translate("MainWindow", "500000"))
        self.portDest.setText(_translate("MainWindow", "Dest:"))
        self.destIp.setText(_translate("MainWindow", "192.168.2.2"))
        self.portPort.setText(_translate("MainWindow", "Port:"))
        self.ipPort.setText(_translate("MainWindow", "1961"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Protocol"))
        self.Serial1.setText(_translate("MainWindow", "Serial"))
        self.SFP.setText(_translate("MainWindow", "SFP"))
        self.AT.setText(_translate("MainWindow", "AT"))
        self.label_5.setText(_translate("MainWindow", "Host:"))
        self.label_4.setText(_translate("MainWindow", "Target:"))
        self.LoopBack.setText(_translate("MainWindow", "Loop back"))
        self.ResetRcvr.setText(_translate("MainWindow", "Reset Receiver"))
        self.ProtocolDump.setText(_translate("MainWindow", "Protocol Dump"))
        self.Ping.setText(_translate("MainWindow", "Ping"))
        self.Controls.setTabText(self.Controls.indexOf(self.Interface), _translate("MainWindow", "Interface"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Input"))
        self.inputIgnore.setItemText(0, _translate("MainWindow", "Passive"))
        self.inputIgnore.setItemText(1, _translate("MainWindow", "Ignore CR"))
        self.inputIgnore.setItemText(2, _translate("MainWindow", "Ignore LF"))
        self.inputIgnore.setItemText(3, _translate("MainWindow", "Ignore CRLF"))
        self.sendHex.setText(_translate("MainWindow", "Send Hex:"))
        self.groupBox.setTitle(_translate("MainWindow", "Output"))
        self.InBuffered.setText(_translate("MainWindow", "Buffered"))
        self.InRaw.setText(_translate("MainWindow", "Raw"))
        self.InRawEcho.setText(_translate("MainWindow", "Raw+Echo"))
        self.InHex.setText(_translate("MainWindow", "Hex"))
        self.LFnada.setText(_translate("MainWindow", "nada"))
        self.label_2.setText(_translate("MainWindow", "Output CR as:"))
        self.label_3.setText(_translate("MainWindow", "Output LF as:"))
        self.CRCR.setText(_translate("MainWindow", "CR"))
        self.CRnada.setText(_translate("MainWindow", "nada"))
        self.LFLF.setText(_translate("MainWindow", "LF"))
        self.LFCR.setText(_translate("MainWindow", "CR"))
        self.CRLF.setText(_translate("MainWindow", "LF"))
        self.linewrap.setText(_translate("MainWindow", "Line wrap"))
        self.Controls.setTabText(self.Controls.indexOf(self.Text), _translate("MainWindow", "Text"))
        self.label_26.setText(_translate("MainWindow", "Target:"))
        self.label_18.setText(_translate("MainWindow", "Entry Point:"))
        self.label_20.setText(_translate("MainWindow", "Size:"))
        self.label_19.setText(_translate("MainWindow", "CheckSum:"))
        self.fileSelect.setText(_translate("MainWindow", "File:"))
        self.label_16.setText(_translate("MainWindow", "Address Start:"))
        self.label_17.setText(_translate("MainWindow", "Target Address:"))
        self.header.setText(_translate("MainWindow", "+Header"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.endian.setText(_translate("MainWindow", "Big Endian"))
        self.sendSrecord.setText(_translate("MainWindow", "Send"))
        self.label_6.setText(_translate("MainWindow", "Erase"))
        self.label_7.setText(_translate("MainWindow", "Transfer"))
        self.label_8.setText(_translate("MainWindow", "Verify"))
        self.Recover.setText(_translate("MainWindow", "Recover"))
        self.Version.setText(_translate("MainWindow", "Version"))
        self.reboot.setText(_translate("MainWindow", "Reboot"))
        self.recoverOption.setText(_translate("MainWindow", "+recover"))
        self.Controls.setTabText(self.Controls.indexOf(self.Transfer), _translate("MainWindow", "Transfer"))
        self.Refresh.setText(_translate("MainWindow", "Refresh"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Choice"))
        self.label_33.setText(_translate("MainWindow", "Running:"))
        self.runningChoiceStatus.setText(_translate("MainWindow", "Left"))
        self.label_34.setText(_translate("MainWindow", "Pending:"))
        self.pendingChoiceStatus.setText(_translate("MainWindow", "Invalid"))
        self.label_35.setText(_translate("MainWindow", "Magic:"))
        self.magicStatus.setText(_translate("MainWindow", "Fail"))
        self.label_36.setText(_translate("MainWindow", "Checksum:"))
        self.checksumStatus.setText(_translate("MainWindow", "Fail"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Versions"))
        self.label_25.setText(_translate("MainWindow", "Boot"))
        self.label_30.setText(_translate("MainWindow", "Left App"))
        self.label_31.setText(_translate("MainWindow", "Right App"))
        self.Controls.setTabText(self.Controls.indexOf(self.Info), _translate("MainWindow", "Info"))
        self.sendBoot.setText(_translate("MainWindow", "Transfer"))
        self.label_32.setText(_translate("MainWindow", "Address:"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.label_29.setText(_translate("MainWindow", "Size:"))
        self.Go.setText(_translate("MainWindow", "Go"))
        self.bootSelect.setText(_translate("MainWindow", "File:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.STMBootTransfer), _translate("MainWindow", "Download"))
        self.Boot.setText(_translate("MainWindow", "Boot"))
        self.Init.setText(_translate("MainWindow", "Init"))
        self.Reconnect.setText(_translate("MainWindow", "Serial"))
        self.Rdp.setText(_translate("MainWindow", "-Rdp"))
        self.Getrpd.setText(_translate("MainWindow", "Get Rpd"))
        self.Erase.setText(_translate("MainWindow", "Erase"))
        self.Get.setText(_translate("MainWindow", "Get"))
        self.Getid.setText(_translate("MainWindow", "Get ID"))
        self.Pages.setText(_translate("MainWindow", "Pages"))
        self.Write.setText(_translate("MainWindow", "Write"))
        self.Address.setText(_translate("MainWindow", "Addr"))
        self.Data.setText(_translate("MainWindow", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.STMTools), _translate("MainWindow", "Tools"))
        self.verbose.setText(_translate("MainWindow", "Verbose"))
        self.setDateTime.setText(_translate("MainWindow", "Set Date/Time"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "STM32F4 Boot Loader"))
        self.sendJam.setText(_translate("MainWindow", "Program CPLD"))
        self.sendFile.setText(_translate("MainWindow", "Write FIle"))
        self.jamSelect.setText(_translate("MainWindow", "File:"))
        self.label_40.setText(_translate("MainWindow", "Size:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Jam Player"))
        self.label_72.setText(_translate("MainWindow", "Size:"))
        self.eepromTarget.setItemText(0, _translate("MainWindow", "MotherBoard"))
        self.label_10.setText(_translate("MainWindow", "CRC:"))
        self.eepromSelect.setText(_translate("MainWindow", "File:"))
        self.label.setText(_translate("MainWindow", "Target:"))
        self.sendEeprom.setText(_translate("MainWindow", "Write EEPROM"))
        self.readEeprom.setText(_translate("MainWindow", "Read EEPROM"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "EEPROM Script"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Port 1"))
        self.MonitorPort1.setItemText(0, _translate("MainWindow", "(Select a Port)"))
        self.MonitorBaud1.setItemText(0, _translate("MainWindow", "9600"))
        self.MonitorBaud1.setItemText(1, _translate("MainWindow", "19200"))
        self.MonitorBaud1.setItemText(2, _translate("MainWindow", "28800"))
        self.MonitorBaud1.setItemText(3, _translate("MainWindow", "38400"))
        self.MonitorBaud1.setItemText(4, _translate("MainWindow", "57600"))
        self.MonitorBaud1.setItemText(5, _translate("MainWindow", "115200"))
        self.MonitorBaud1.setItemText(6, _translate("MainWindow", "230400"))
        self.MonitorBaud1.setItemText(7, _translate("MainWindow", "460800"))
        self.MonitorBaud1.setItemText(8, _translate("MainWindow", "500000"))
        self.Color1.setItemText(0, _translate("MainWindow", "white"))
        self.Color1.setItemText(1, _translate("MainWindow", "cyan"))
        self.Color1.setItemText(2, _translate("MainWindow", "blue"))
        self.Color1.setItemText(3, _translate("MainWindow", "green"))
        self.Color1.setItemText(4, _translate("MainWindow", "yellow"))
        self.Color1.setItemText(5, _translate("MainWindow", "orange"))
        self.Color1.setItemText(6, _translate("MainWindow", "magenta"))
        self.Color1.setItemText(7, _translate("MainWindow", "red"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Port 2"))
        self.MonitorPort2.setItemText(0, _translate("MainWindow", "(Select a Port)"))
        self.MonitorBaud2.setItemText(0, _translate("MainWindow", "9600"))
        self.MonitorBaud2.setItemText(1, _translate("MainWindow", "19200"))
        self.MonitorBaud2.setItemText(2, _translate("MainWindow", "28800"))
        self.MonitorBaud2.setItemText(3, _translate("MainWindow", "38400"))
        self.MonitorBaud2.setItemText(4, _translate("MainWindow", "57600"))
        self.MonitorBaud2.setItemText(5, _translate("MainWindow", "115200"))
        self.MonitorBaud2.setItemText(6, _translate("MainWindow", "230400"))
        self.MonitorBaud2.setItemText(7, _translate("MainWindow", "460800"))
        self.MonitorBaud2.setItemText(8, _translate("MainWindow", "500000"))
        self.Color2.setItemText(0, _translate("MainWindow", "white"))
        self.Color2.setItemText(1, _translate("MainWindow", "cyan"))
        self.Color2.setItemText(2, _translate("MainWindow", "blue"))
        self.Color2.setItemText(3, _translate("MainWindow", "green"))
        self.Color2.setItemText(4, _translate("MainWindow", "yellow"))
        self.Color2.setItemText(5, _translate("MainWindow", "orange"))
        self.Color2.setItemText(6, _translate("MainWindow", "magenta"))
        self.Color2.setItemText(7, _translate("MainWindow", "red"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Monitor), _translate("MainWindow", "Monitor"))
        self.Controls.setTabText(self.Controls.indexOf(self.Tools), _translate("MainWindow", "Tools"))
        self.send2.setText(_translate("MainWindow", "Send"))
        self.send6.setText(_translate("MainWindow", "Send"))
        self.send8.setText(_translate("MainWindow", "Send"))
        self.send7.setText(_translate("MainWindow", "Send"))
        self.send3.setText(_translate("MainWindow", "Send"))
        self.send1.setText(_translate("MainWindow", "Send"))
        self.send4.setText(_translate("MainWindow", "Send"))
        self.send5.setText(_translate("MainWindow", "Send"))
        self.Controls.setTabText(self.Controls.indexOf(self.Phrases), _translate("MainWindow", "Phrases"))
        self.Find.setText(_translate("MainWindow", "Find"))
        self.FindBackwards.setText(_translate("MainWindow", "Backwards"))
        self.label_11.setText(_translate("MainWindow", "Size"))
        self.saveText.setText(_translate("MainWindow", "Save"))
        self.ClearText.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

