# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1044, 588)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.PortSelect = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortSelect.sizePolicy().hasHeightForWidth())
        self.PortSelect.setSizePolicy(sizePolicy)
        self.PortSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PortSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PortSelect.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.PortSelect.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.PortSelect.setObjectName("PortSelect")
        self.PortSelect.addItem("")
        self.horizontalLayout_14.addWidget(self.PortSelect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_19.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.BaudRate = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaudRate.sizePolicy().hasHeightForWidth())
        self.BaudRate.setSizePolicy(sizePolicy)
        self.BaudRate.setAcceptDrops(False)
        self.BaudRate.setFrame(True)
        self.BaudRate.setObjectName("BaudRate")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.horizontalLayout_11.addWidget(self.BaudRate)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton_2.setEnabled(True)
        self.toolButton_2.setText("N 8 1")
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_11.addWidget(self.toolButton_2)
        self.ConsoleColor = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConsoleColor.sizePolicy().hasHeightForWidth())
        self.ConsoleColor.setSizePolicy(sizePolicy)
        self.ConsoleColor.setAcceptDrops(False)
        self.ConsoleColor.setMaxVisibleItems(10)
        self.ConsoleColor.setFrame(True)
        self.ConsoleColor.setObjectName("ConsoleColor")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.horizontalLayout_11.addWidget(self.ConsoleColor)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SetSfp = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetSfp.sizePolicy().hasHeightForWidth())
        self.SetSfp.setSizePolicy(sizePolicy)
        self.SetSfp.setMinimumSize(QtCore.QSize(0, 0))
        self.SetSfp.setChecked(True)
        self.SetSfp.setObjectName("SetSfp")
        self.buttonGroup = QtWidgets.QButtonGroup(Frame)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.SetSfp)
        self.horizontalLayout_5.addWidget(self.SetSfp)
        self.SetSerial = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetSerial.sizePolicy().hasHeightForWidth())
        self.SetSerial.setSizePolicy(sizePolicy)
        self.SetSerial.setObjectName("SetSerial")
        self.buttonGroup.addButton(self.SetSerial)
        self.horizontalLayout_5.addWidget(self.SetSerial)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.whoTo = QtWidgets.QComboBox(self.groupBox_6)
        self.whoTo.setMinimumSize(QtCore.QSize(0, 0))
        self.whoTo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.whoTo.setObjectName("whoTo")
        self.horizontalLayout_4.addWidget(self.whoTo)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.whoFrom = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whoFrom.sizePolicy().hasHeightForWidth())
        self.whoFrom.setSizePolicy(sizePolicy)
        self.whoFrom.setMinimumSize(QtCore.QSize(0, 0))
        self.whoFrom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.whoFrom.setObjectName("whoFrom")
        self.horizontalLayout_4.addWidget(self.whoFrom)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProtocolDump = QtWidgets.QCheckBox(self.groupBox_7)
        self.ProtocolDump.setObjectName("ProtocolDump")
        self.verticalLayout_5.addWidget(self.ProtocolDump)
        self.LoopBack = QtWidgets.QCheckBox(self.groupBox_7)
        self.LoopBack.setObjectName("LoopBack")
        self.verticalLayout_5.addWidget(self.LoopBack)
        self.ignoreUnknowns = QtWidgets.QCheckBox(self.groupBox_7)
        self.ignoreUnknowns.setObjectName("ignoreUnknowns")
        self.verticalLayout_5.addWidget(self.ignoreUnknowns)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Ping = QtWidgets.QPushButton(self.groupBox_7)
        self.Ping.setObjectName("Ping")
        self.verticalLayout_4.addWidget(self.Ping)
        self.ResetRcvr = QtWidgets.QPushButton(self.groupBox_7)
        self.ResetRcvr.setObjectName("ResetRcvr")
        self.verticalLayout_4.addWidget(self.ResetRcvr)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.MonitorPort1 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort1.sizePolicy().hasHeightForWidth())
        self.MonitorPort1.setSizePolicy(sizePolicy)
        self.MonitorPort1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort1.setModelColumn(0)
        self.MonitorPort1.setObjectName("MonitorPort1")
        self.MonitorPort1.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MonitorPort1)
        self.MonitorBaud1 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud1.sizePolicy().hasHeightForWidth())
        self.MonitorBaud1.setSizePolicy(sizePolicy)
        self.MonitorBaud1.setAcceptDrops(False)
        self.MonitorBaud1.setFrame(True)
        self.MonitorBaud1.setObjectName("MonitorBaud1")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MonitorBaud1)
        self.MonitorFormat1 = QtWidgets.QComboBox(self.groupBox)
        self.MonitorFormat1.setObjectName("MonitorFormat1")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.MonitorFormat1)
        self.MonitorColor1 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor1.sizePolicy().hasHeightForWidth())
        self.MonitorColor1.setSizePolicy(sizePolicy)
        self.MonitorColor1.setAcceptDrops(False)
        self.MonitorColor1.setMaxVisibleItems(10)
        self.MonitorColor1.setFrame(True)
        self.MonitorColor1.setObjectName("MonitorColor1")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MonitorColor1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.MonitorPort2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort2.sizePolicy().hasHeightForWidth())
        self.MonitorPort2.setSizePolicy(sizePolicy)
        self.MonitorPort2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort2.setObjectName("MonitorPort2")
        self.MonitorPort2.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MonitorPort2)
        self.MonitorBaud2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud2.sizePolicy().hasHeightForWidth())
        self.MonitorBaud2.setSizePolicy(sizePolicy)
        self.MonitorBaud2.setAcceptDrops(False)
        self.MonitorBaud2.setFrame(True)
        self.MonitorBaud2.setObjectName("MonitorBaud2")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MonitorBaud2)
        self.MonitorFormat2 = QtWidgets.QComboBox(self.groupBox_2)
        self.MonitorFormat2.setObjectName("MonitorFormat2")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.MonitorFormat2)
        self.MonitorColor2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor2.sizePolicy().hasHeightForWidth())
        self.MonitorColor2.setSizePolicy(sizePolicy)
        self.MonitorColor2.setAcceptDrops(False)
        self.MonitorColor2.setMaxVisibleItems(10)
        self.MonitorColor2.setFrame(True)
        self.MonitorColor2.setObjectName("MonitorColor2")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MonitorColor2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.MonitorPort3 = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort3.sizePolicy().hasHeightForWidth())
        self.MonitorPort3.setSizePolicy(sizePolicy)
        self.MonitorPort3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort3.setObjectName("MonitorPort3")
        self.MonitorPort3.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MonitorPort3)
        self.MonitorBaud3 = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud3.sizePolicy().hasHeightForWidth())
        self.MonitorBaud3.setSizePolicy(sizePolicy)
        self.MonitorBaud3.setAcceptDrops(False)
        self.MonitorBaud3.setFrame(True)
        self.MonitorBaud3.setObjectName("MonitorBaud3")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MonitorBaud3)
        self.MonitorFormat3 = QtWidgets.QComboBox(self.groupBox_3)
        self.MonitorFormat3.setObjectName("MonitorFormat3")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.MonitorFormat3)
        self.MonitorColor3 = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor3.sizePolicy().hasHeightForWidth())
        self.MonitorColor3.setSizePolicy(sizePolicy)
        self.MonitorColor3.setAcceptDrops(False)
        self.MonitorColor3.setFrame(True)
        self.MonitorColor3.setObjectName("MonitorColor3")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MonitorColor3)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.MonitorPort4 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort4.sizePolicy().hasHeightForWidth())
        self.MonitorPort4.setSizePolicy(sizePolicy)
        self.MonitorPort4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort4.setObjectName("MonitorPort4")
        self.MonitorPort4.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MonitorPort4)
        self.MonitorBaud4 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud4.sizePolicy().hasHeightForWidth())
        self.MonitorBaud4.setSizePolicy(sizePolicy)
        self.MonitorBaud4.setAcceptDrops(False)
        self.MonitorBaud4.setFrame(True)
        self.MonitorBaud4.setObjectName("MonitorBaud4")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MonitorBaud4)
        self.MonitorFormat4 = QtWidgets.QComboBox(self.groupBox_4)
        self.MonitorFormat4.setObjectName("MonitorFormat4")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.MonitorFormat4)
        self.MonitorColor4 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor4.sizePolicy().hasHeightForWidth())
        self.MonitorColor4.setSizePolicy(sizePolicy)
        self.MonitorColor4.setAcceptDrops(False)
        self.MonitorColor4.setFrame(True)
        self.MonitorColor4.setObjectName("MonitorColor4")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MonitorColor4)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.Console = QtWidgets.QPlainTextEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Console.sizePolicy().hasHeightForWidth())
        self.Console.setSizePolicy(sizePolicy)
        self.Console.setMinimumSize(QtCore.QSize(600, 470))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Console.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.Console.setFont(font)
        self.Console.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Console.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Console.setUndoRedoEnabled(False)
        self.Console.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.Console.setPlainText("")
        self.Console.setObjectName("Console")
        self.verticalLayout.addWidget(self.Console)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(0)
        self.BaudRate.setCurrentIndex(6)
        self.ConsoleColor.setCurrentIndex(0)
        self.MonitorPort1.setCurrentIndex(0)
        self.MonitorBaud1.setCurrentIndex(6)
        self.MonitorColor1.setCurrentIndex(4)
        self.MonitorBaud2.setCurrentIndex(6)
        self.MonitorColor2.setCurrentIndex(5)
        self.MonitorBaud3.setCurrentIndex(6)
        self.MonitorColor3.setCurrentIndex(0)
        self.MonitorBaud4.setCurrentIndex(6)
        self.MonitorColor4.setCurrentIndex(2)
        self.pushButton.released.connect(self.Console.clear)
        self.SetSfp.clicked.connect(self.whoTo.show)
        self.SetSerial.clicked.connect(self.whoTo.hide)
        self.SetSerial.clicked.connect(self.whoFrom.hide)
        self.SetSfp.clicked.connect(self.whoFrom.show)
        self.SetSfp.clicked.connect(self.label_5.show)
        self.SetSfp.clicked.connect(self.label_4.show)
        self.SetSerial.clicked.connect(self.label_5.hide)
        self.SetSerial.clicked.connect(self.label_4.hide)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.groupBox_8.setTitle(_translate("Frame", "Port"))
        self.PortSelect.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.BaudRate.setItemText(0, _translate("Frame", "1200"))
        self.BaudRate.setItemText(1, _translate("Frame", "9600"))
        self.BaudRate.setItemText(2, _translate("Frame", "19200"))
        self.BaudRate.setItemText(3, _translate("Frame", "28800"))
        self.BaudRate.setItemText(4, _translate("Frame", "38400"))
        self.BaudRate.setItemText(5, _translate("Frame", "57600"))
        self.BaudRate.setItemText(6, _translate("Frame", "115200"))
        self.BaudRate.setItemText(7, _translate("Frame", "230400"))
        self.BaudRate.setItemText(8, _translate("Frame", "460800"))
        self.BaudRate.setItemText(9, _translate("Frame", "500000"))
        self.BaudRate.setItemText(10, _translate("Frame", "921600"))
        self.ConsoleColor.setCurrentText(_translate("Frame", "white"))
        self.ConsoleColor.setItemText(0, _translate("Frame", "white"))
        self.ConsoleColor.setItemText(1, _translate("Frame", "cyan"))
        self.ConsoleColor.setItemText(2, _translate("Frame", "blue"))
        self.ConsoleColor.setItemText(3, _translate("Frame", "green"))
        self.ConsoleColor.setItemText(4, _translate("Frame", "yellow"))
        self.ConsoleColor.setItemText(5, _translate("Frame", "orange"))
        self.ConsoleColor.setItemText(6, _translate("Frame", "magenta"))
        self.ConsoleColor.setItemText(7, _translate("Frame", "red"))
        self.groupBox_6.setTitle(_translate("Frame", "Protocol"))
        self.SetSfp.setText(_translate("Frame", "SFP"))
        self.SetSerial.setText(_translate("Frame", "Serial"))
        self.label_5.setText(_translate("Frame", "From:"))
        self.label_4.setText(_translate("Frame", "To:"))
        self.groupBox_7.setTitle(_translate("Frame", "Tools"))
        self.ProtocolDump.setText(_translate("Frame", "Protocol Dump"))
        self.LoopBack.setText(_translate("Frame", "Loop back"))
        self.ignoreUnknowns.setText(_translate("Frame", "Ignore Unknowns"))
        self.Ping.setText(_translate("Frame", "Ping"))
        self.ResetRcvr.setText(_translate("Frame", "Reset Receiver"))
        self.pushButton.setText(_translate("Frame", "Clear Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Frame", "Console"))
        self.groupBox.setTitle(_translate("Frame", "al200"))
        self.MonitorPort1.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorBaud1.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud1.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud1.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud1.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud1.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud1.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud1.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud1.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud1.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud1.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud1.setItemText(10, _translate("Frame", "921600"))
        self.MonitorFormat1.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat1.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat1.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat1.setItemText(3, _translate("Frame", "Alert2 IND"))
        self.MonitorColor1.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor1.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor1.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor1.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor1.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor1.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor1.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor1.setItemText(7, _translate("Frame", "red"))
        self.groupBox_2.setTitle(_translate("Frame", "cs600"))
        self.MonitorPort2.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorBaud2.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud2.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud2.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud2.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud2.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud2.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud2.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud2.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud2.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud2.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud2.setItemText(10, _translate("Frame", "921600"))
        self.MonitorFormat2.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat2.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat2.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat2.setItemText(3, _translate("Frame", "Alert2 IND"))
        self.MonitorColor2.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor2.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor2.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor2.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor2.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor2.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor2.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor2.setItemText(7, _translate("Frame", "red"))
        self.groupBox_3.setTitle(_translate("Frame", "M3"))
        self.MonitorPort3.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorBaud3.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud3.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud3.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud3.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud3.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud3.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud3.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud3.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud3.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud3.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud3.setItemText(10, _translate("Frame", "921600"))
        self.MonitorFormat3.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat3.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat3.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat3.setItemText(3, _translate("Frame", "Alert2 IND"))
        self.MonitorColor3.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor3.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor3.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor3.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor3.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor3.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor3.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor3.setItemText(7, _translate("Frame", "red"))
        self.groupBox_4.setTitle(_translate("Frame", "M4"))
        self.MonitorPort4.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorBaud4.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud4.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud4.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud4.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud4.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud4.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud4.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud4.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud4.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud4.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud4.setItemText(10, _translate("Frame", "921600"))
        self.MonitorFormat4.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat4.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat4.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat4.setItemText(3, _translate("Frame", "Alert2 IND"))
        self.MonitorColor4.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor4.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor4.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor4.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor4.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor4.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor4.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor4.setItemText(7, _translate("Frame", "red"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Frame", "Monitor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
