# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(938, 542)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.horizontalLayout_7 = QtGui.QHBoxLayout(Frame)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Frame)
        self.groupBox.setMinimumSize(QtCore.QSize(15, 100))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_3)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.PortSelect = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortSelect.sizePolicy().hasHeightForWidth())
        self.PortSelect.setSizePolicy(sizePolicy)
        self.PortSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PortSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PortSelect.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.PortSelect.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.PortSelect.setObjectName(_fromUtf8("PortSelect"))
        self.PortSelect.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.SpanningRole, self.PortSelect)
        self.SetSerial = QtGui.QRadioButton(self.groupBox)
        self.SetSerial.setObjectName(_fromUtf8("SetSerial"))
        self.buttonGroup = QtGui.QButtonGroup(Frame)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.SetSerial)
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.SetSerial)
        self.SetSfp = QtGui.QRadioButton(self.groupBox)
        self.SetSfp.setMinimumSize(QtCore.QSize(0, 0))
        self.SetSfp.setChecked(True)
        self.SetSfp.setObjectName(_fromUtf8("SetSfp"))
        self.buttonGroup.addButton(self.SetSfp)
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.SetSfp)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.FieldRole, self.formLayout_5)
        self.ConsoleColor = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConsoleColor.sizePolicy().hasHeightForWidth())
        self.ConsoleColor.setSizePolicy(sizePolicy)
        self.ConsoleColor.setAcceptDrops(False)
        self.ConsoleColor.setMaxVisibleItems(10)
        self.ConsoleColor.setFrame(True)
        self.ConsoleColor.setObjectName(_fromUtf8("ConsoleColor"))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.ConsoleColor.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.ConsoleColor)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.line = QtGui.QFrame(Frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.groupBox_2 = QtGui.QGroupBox(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.MonitorPort1 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort1.sizePolicy().hasHeightForWidth())
        self.MonitorPort1.setSizePolicy(sizePolicy)
        self.MonitorPort1.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.MonitorPort1.setModelColumn(0)
        self.MonitorPort1.setObjectName(_fromUtf8("MonitorPort1"))
        self.MonitorPort1.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.MonitorPort1)
        self.MonitorFormat1 = QtGui.QComboBox(self.groupBox_2)
        self.MonitorFormat1.setObjectName(_fromUtf8("MonitorFormat1"))
        self.MonitorFormat1.addItem(_fromUtf8(""))
        self.MonitorFormat1.addItem(_fromUtf8(""))
        self.MonitorFormat1.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.MonitorFormat1)
        self.MonitorColor1 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor1.sizePolicy().hasHeightForWidth())
        self.MonitorColor1.setSizePolicy(sizePolicy)
        self.MonitorColor1.setAcceptDrops(False)
        self.MonitorColor1.setMaxVisibleItems(10)
        self.MonitorColor1.setFrame(True)
        self.MonitorColor1.setObjectName(_fromUtf8("MonitorColor1"))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.MonitorColor1.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.MonitorColor1)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.MonitorPort2 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort2.sizePolicy().hasHeightForWidth())
        self.MonitorPort2.setSizePolicy(sizePolicy)
        self.MonitorPort2.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.MonitorPort2.setObjectName(_fromUtf8("MonitorPort2"))
        self.MonitorPort2.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.SpanningRole, self.MonitorPort2)
        self.MonitorFormat2 = QtGui.QComboBox(self.groupBox_2)
        self.MonitorFormat2.setObjectName(_fromUtf8("MonitorFormat2"))
        self.MonitorFormat2.addItem(_fromUtf8(""))
        self.MonitorFormat2.addItem(_fromUtf8(""))
        self.MonitorFormat2.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.MonitorFormat2)
        self.MonitorColor2 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor2.sizePolicy().hasHeightForWidth())
        self.MonitorColor2.setSizePolicy(sizePolicy)
        self.MonitorColor2.setAcceptDrops(False)
        self.MonitorColor2.setMaxVisibleItems(10)
        self.MonitorColor2.setFrame(True)
        self.MonitorColor2.setObjectName(_fromUtf8("MonitorColor2"))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.MonitorColor2.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.MonitorColor2)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.MonitorPort3 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort3.sizePolicy().hasHeightForWidth())
        self.MonitorPort3.setSizePolicy(sizePolicy)
        self.MonitorPort3.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.MonitorPort3.setObjectName(_fromUtf8("MonitorPort3"))
        self.MonitorPort3.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.MonitorPort3)
        self.MonitorFormat3 = QtGui.QComboBox(self.groupBox_2)
        self.MonitorFormat3.setObjectName(_fromUtf8("MonitorFormat3"))
        self.MonitorFormat3.addItem(_fromUtf8(""))
        self.MonitorFormat3.addItem(_fromUtf8(""))
        self.MonitorFormat3.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.MonitorFormat3)
        self.MonitorColor3 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor3.sizePolicy().hasHeightForWidth())
        self.MonitorColor3.setSizePolicy(sizePolicy)
        self.MonitorColor3.setAcceptDrops(False)
        self.MonitorColor3.setFrame(True)
        self.MonitorColor3.setObjectName(_fromUtf8("MonitorColor3"))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.MonitorColor3.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.MonitorColor3)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.MonitorPort4 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort4.sizePolicy().hasHeightForWidth())
        self.MonitorPort4.setSizePolicy(sizePolicy)
        self.MonitorPort4.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.MonitorPort4.setObjectName(_fromUtf8("MonitorPort4"))
        self.MonitorPort4.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.MonitorPort4)
        self.MonitorFormat4 = QtGui.QComboBox(self.groupBox_2)
        self.MonitorFormat4.setObjectName(_fromUtf8("MonitorFormat4"))
        self.MonitorFormat4.addItem(_fromUtf8(""))
        self.MonitorFormat4.addItem(_fromUtf8(""))
        self.MonitorFormat4.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.MonitorFormat4)
        self.MonitorColor4 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor4.sizePolicy().hasHeightForWidth())
        self.MonitorColor4.setSizePolicy(sizePolicy)
        self.MonitorColor4.setAcceptDrops(False)
        self.MonitorColor4.setFrame(True)
        self.MonitorColor4.setObjectName(_fromUtf8("MonitorColor4"))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.MonitorColor4.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.MonitorColor4)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEdit = QtGui.QPlainTextEdit(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(601, 471))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(12)
        font.setItalic(False)
        font.setKerning(False)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet(_fromUtf8("font: cyan;"))
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.textEdit.setPlainText(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.SendCommand = QtGui.QPushButton(Frame)
        self.SendCommand.setObjectName(_fromUtf8("SendCommand"))
        self.horizontalLayout_2.addWidget(self.SendCommand)
        self.LastCommand = QtGui.QLineEdit(Frame)
        self.LastCommand.setObjectName(_fromUtf8("LastCommand"))
        self.horizontalLayout_2.addWidget(self.LastCommand)
        self.pushButton = QtGui.QPushButton(Frame)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        self.ConsoleColor.setCurrentIndex(1)
        self.MonitorPort1.setCurrentIndex(0)
        self.MonitorColor1.setCurrentIndex(4)
        self.MonitorColor2.setCurrentIndex(5)
        self.MonitorColor3.setCurrentIndex(0)
        self.MonitorColor4.setCurrentIndex(2)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("released()")), self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.groupBox.setTitle(_translate("Frame", "Console:", None))
        self.label.setText(_translate("Frame", "Port:", None))
        self.label_2.setText(_translate("Frame", "Protocol:", None))
        self.PortSelect.setItemText(0, _translate("Frame", "(Select a Port)", None))
        self.SetSerial.setText(_translate("Frame", "Serial", None))
        self.SetSfp.setText(_translate("Frame", "SFP", None))
        self.ConsoleColor.setItemText(0, _translate("Frame", "white", None))
        self.ConsoleColor.setItemText(1, _translate("Frame", "cyan", None))
        self.ConsoleColor.setItemText(2, _translate("Frame", "blue", None))
        self.ConsoleColor.setItemText(3, _translate("Frame", "green", None))
        self.ConsoleColor.setItemText(4, _translate("Frame", "yellow", None))
        self.ConsoleColor.setItemText(5, _translate("Frame", "orange", None))
        self.ConsoleColor.setItemText(6, _translate("Frame", "magenta", None))
        self.ConsoleColor.setItemText(7, _translate("Frame", "red", None))
        self.groupBox_2.setTitle(_translate("Frame", "Monitors:", None))
        self.label_3.setText(_translate("Frame", "M1:", None))
        self.MonitorPort1.setItemText(0, _translate("Frame", "(Select a Port)", None))
        self.MonitorFormat1.setItemText(0, _translate("Frame", "ASCII", None))
        self.MonitorFormat1.setItemText(1, _translate("Frame", "Hex", None))
        self.MonitorFormat1.setItemText(2, _translate("Frame", "SFP", None))
        self.MonitorColor1.setItemText(0, _translate("Frame", "white", None))
        self.MonitorColor1.setItemText(1, _translate("Frame", "cyan", None))
        self.MonitorColor1.setItemText(2, _translate("Frame", "blue", None))
        self.MonitorColor1.setItemText(3, _translate("Frame", "green", None))
        self.MonitorColor1.setItemText(4, _translate("Frame", "yellow", None))
        self.MonitorColor1.setItemText(5, _translate("Frame", "orange", None))
        self.MonitorColor1.setItemText(6, _translate("Frame", "magenta", None))
        self.MonitorColor1.setItemText(7, _translate("Frame", "red", None))
        self.label_4.setText(_translate("Frame", "M2:", None))
        self.MonitorPort2.setItemText(0, _translate("Frame", "(Select a Port)", None))
        self.MonitorFormat2.setItemText(0, _translate("Frame", "ASCII", None))
        self.MonitorFormat2.setItemText(1, _translate("Frame", "Hex", None))
        self.MonitorFormat2.setItemText(2, _translate("Frame", "SFP", None))
        self.MonitorColor2.setItemText(0, _translate("Frame", "white", None))
        self.MonitorColor2.setItemText(1, _translate("Frame", "cyan", None))
        self.MonitorColor2.setItemText(2, _translate("Frame", "blue", None))
        self.MonitorColor2.setItemText(3, _translate("Frame", "green", None))
        self.MonitorColor2.setItemText(4, _translate("Frame", "yellow", None))
        self.MonitorColor2.setItemText(5, _translate("Frame", "orange", None))
        self.MonitorColor2.setItemText(6, _translate("Frame", "magenta", None))
        self.MonitorColor2.setItemText(7, _translate("Frame", "red", None))
        self.label_5.setText(_translate("Frame", "M3:", None))
        self.MonitorPort3.setItemText(0, _translate("Frame", "(Select a Port)", None))
        self.MonitorFormat3.setItemText(0, _translate("Frame", "ASCII", None))
        self.MonitorFormat3.setItemText(1, _translate("Frame", "Hex", None))
        self.MonitorFormat3.setItemText(2, _translate("Frame", "SFP", None))
        self.MonitorColor3.setItemText(0, _translate("Frame", "white", None))
        self.MonitorColor3.setItemText(1, _translate("Frame", "cyan", None))
        self.MonitorColor3.setItemText(2, _translate("Frame", "blue", None))
        self.MonitorColor3.setItemText(3, _translate("Frame", "green", None))
        self.MonitorColor3.setItemText(4, _translate("Frame", "yellow", None))
        self.MonitorColor3.setItemText(5, _translate("Frame", "orange", None))
        self.MonitorColor3.setItemText(6, _translate("Frame", "magenta", None))
        self.MonitorColor3.setItemText(7, _translate("Frame", "red", None))
        self.label_6.setText(_translate("Frame", "M4:", None))
        self.MonitorPort4.setItemText(0, _translate("Frame", "(Select a Port)", None))
        self.MonitorFormat4.setItemText(0, _translate("Frame", "ASCII", None))
        self.MonitorFormat4.setItemText(1, _translate("Frame", "Hex", None))
        self.MonitorFormat4.setItemText(2, _translate("Frame", "SFP", None))
        self.MonitorColor4.setItemText(0, _translate("Frame", "white", None))
        self.MonitorColor4.setItemText(1, _translate("Frame", "cyan", None))
        self.MonitorColor4.setItemText(2, _translate("Frame", "blue", None))
        self.MonitorColor4.setItemText(3, _translate("Frame", "green", None))
        self.MonitorColor4.setItemText(4, _translate("Frame", "yellow", None))
        self.MonitorColor4.setItemText(5, _translate("Frame", "orange", None))
        self.MonitorColor4.setItemText(6, _translate("Frame", "magenta", None))
        self.MonitorColor4.setItemText(7, _translate("Frame", "red", None))
        self.SendCommand.setText(_translate("Frame", "Send", None))
        self.pushButton.setText(_translate("Frame", "Clear Screen", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Frame = QtGui.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

