# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1044, 588)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setStyleSheet("")
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.PortSelect = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortSelect.sizePolicy().hasHeightForWidth())
        self.PortSelect.setSizePolicy(sizePolicy)
        self.PortSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PortSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PortSelect.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.PortSelect.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.PortSelect.setObjectName("PortSelect")
        self.PortSelect.addItem("")
        self.horizontalLayout_14.addWidget(self.PortSelect)
        self.ConsoleColor = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConsoleColor.sizePolicy().hasHeightForWidth())
        self.ConsoleColor.setSizePolicy(sizePolicy)
        self.ConsoleColor.setAcceptDrops(False)
        self.ConsoleColor.setMaxVisibleItems(10)
        self.ConsoleColor.setFrame(True)
        self.ConsoleColor.setObjectName("ConsoleColor")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.ConsoleColor.addItem("")
        self.horizontalLayout_14.addWidget(self.ConsoleColor)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ConsoleProtocol = QtWidgets.QComboBox(self.groupBox_8)
        self.ConsoleProtocol.setObjectName("ConsoleProtocol")
        self.ConsoleProtocol.addItem("")
        self.ConsoleProtocol.addItem("")
        self.ConsoleProtocol.addItem("")
        self.ConsoleProtocol.addItem("")
        self.horizontalLayout_6.addWidget(self.ConsoleProtocol)
        self.BaudRate = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaudRate.sizePolicy().hasHeightForWidth())
        self.BaudRate.setSizePolicy(sizePolicy)
        self.BaudRate.setAcceptDrops(False)
        self.BaudRate.setFrame(True)
        self.BaudRate.setObjectName("BaudRate")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.horizontalLayout_6.addWidget(self.BaudRate)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton.setEnabled(True)
        self.toolButton.setText("N 8 1")
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_6.addWidget(self.toolButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.whoTo = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whoTo.sizePolicy().hasHeightForWidth())
        self.whoTo.setSizePolicy(sizePolicy)
        self.whoTo.setStyleSheet("text-transform: uppercase;")
        self.whoTo.setMaximum(255)
        self.whoTo.setDisplayIntegerBase(16)
        self.whoTo.setObjectName("whoTo")
        self.horizontalLayout_4.addWidget(self.whoTo)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.whoFrom = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whoFrom.sizePolicy().hasHeightForWidth())
        self.whoFrom.setSizePolicy(sizePolicy)
        self.whoFrom.setStyleSheet("text-transform: uppercase;")
        self.whoFrom.setPrefix("")
        self.whoFrom.setMaximum(255)
        self.whoFrom.setDisplayIntegerBase(16)
        self.whoFrom.setObjectName("whoFrom")
        self.horizontalLayout_4.addWidget(self.whoFrom)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProtocolDump = QtWidgets.QCheckBox(self.groupBox_7)
        self.ProtocolDump.setObjectName("ProtocolDump")
        self.verticalLayout_5.addWidget(self.ProtocolDump)
        self.LoopBack = QtWidgets.QCheckBox(self.groupBox_7)
        self.LoopBack.setObjectName("LoopBack")
        self.verticalLayout_5.addWidget(self.LoopBack)
        self.ignoreUnknowns = QtWidgets.QCheckBox(self.groupBox_7)
        self.ignoreUnknowns.setObjectName("ignoreUnknowns")
        self.verticalLayout_5.addWidget(self.ignoreUnknowns)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Ping = QtWidgets.QPushButton(self.groupBox_7)
        self.Ping.setObjectName("Ping")
        self.verticalLayout_4.addWidget(self.Ping)
        self.ResetRcvr = QtWidgets.QPushButton(self.groupBox_7)
        self.ResetRcvr.setObjectName("ResetRcvr")
        self.verticalLayout_4.addWidget(self.ResetRcvr)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        spacerItem4 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab, "")
        self.PortMonitors = QtWidgets.QWidget()
        self.PortMonitors.setObjectName("PortMonitors")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PortMonitors)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = MonitorFrame(self.PortMonitors)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.m1name = QtWidgets.QLineEdit(self.frame)
        self.m1name.setStyleSheet("background-color: palette(window);")
        self.m1name.setObjectName("m1name")
        self.gridLayout_4.addWidget(self.m1name, 0, 0, 1, 1)
        self.MonitorPort1 = PortCombo(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort1.sizePolicy().hasHeightForWidth())
        self.MonitorPort1.setSizePolicy(sizePolicy)
        self.MonitorPort1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort1.setModelColumn(0)
        self.MonitorPort1.setObjectName("MonitorPort1")
        self.MonitorPort1.addItem("")
        self.gridLayout_4.addWidget(self.MonitorPort1, 0, 1, 1, 2)
        self.MonitorColor1 = ColorCombo(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor1.sizePolicy().hasHeightForWidth())
        self.MonitorColor1.setSizePolicy(sizePolicy)
        self.MonitorColor1.setAcceptDrops(False)
        self.MonitorColor1.setMaxVisibleItems(10)
        self.MonitorColor1.setFrame(True)
        self.MonitorColor1.setObjectName("MonitorColor1")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.MonitorColor1.addItem("")
        self.gridLayout_4.addWidget(self.MonitorColor1, 1, 0, 1, 1)
        self.MonitorFormat1 = FormatCombo(self.frame)
        self.MonitorFormat1.setObjectName("MonitorFormat1")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.MonitorFormat1.addItem("")
        self.gridLayout_4.addWidget(self.MonitorFormat1, 1, 1, 1, 1)
        self.MonitorBaud1 = BaudCombo(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud1.sizePolicy().hasHeightForWidth())
        self.MonitorBaud1.setSizePolicy(sizePolicy)
        self.MonitorBaud1.setAcceptDrops(False)
        self.MonitorBaud1.setFrame(True)
        self.MonitorBaud1.setObjectName("MonitorBaud1")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.MonitorBaud1.addItem("")
        self.gridLayout_4.addWidget(self.MonitorBaud1, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = MonitorFrame(self.PortMonitors)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.m2name = QtWidgets.QLineEdit(self.frame_2)
        self.m2name.setStyleSheet("background-color: palette(window);")
        self.m2name.setObjectName("m2name")
        self.gridLayout_3.addWidget(self.m2name, 0, 0, 1, 1)
        self.MonitorPort2 = PortCombo(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort2.sizePolicy().hasHeightForWidth())
        self.MonitorPort2.setSizePolicy(sizePolicy)
        self.MonitorPort2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort2.setObjectName("MonitorPort2")
        self.MonitorPort2.addItem("")
        self.gridLayout_3.addWidget(self.MonitorPort2, 0, 1, 1, 2)
        self.MonitorColor2 = ColorCombo(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor2.sizePolicy().hasHeightForWidth())
        self.MonitorColor2.setSizePolicy(sizePolicy)
        self.MonitorColor2.setAcceptDrops(False)
        self.MonitorColor2.setMaxVisibleItems(10)
        self.MonitorColor2.setFrame(True)
        self.MonitorColor2.setObjectName("MonitorColor2")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.MonitorColor2.addItem("")
        self.gridLayout_3.addWidget(self.MonitorColor2, 1, 0, 1, 1)
        self.MonitorFormat2 = FormatCombo(self.frame_2)
        self.MonitorFormat2.setObjectName("MonitorFormat2")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.MonitorFormat2.addItem("")
        self.gridLayout_3.addWidget(self.MonitorFormat2, 1, 1, 1, 1)
        self.MonitorBaud2 = BaudCombo(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud2.sizePolicy().hasHeightForWidth())
        self.MonitorBaud2.setSizePolicy(sizePolicy)
        self.MonitorBaud2.setAcceptDrops(False)
        self.MonitorBaud2.setFrame(True)
        self.MonitorBaud2.setObjectName("MonitorBaud2")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.MonitorBaud2.addItem("")
        self.gridLayout_3.addWidget(self.MonitorBaud2, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = MonitorFrame(self.PortMonitors)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.m3name = QtWidgets.QLineEdit(self.frame_3)
        self.m3name.setStyleSheet("background-color: palette(window);")
        self.m3name.setObjectName("m3name")
        self.gridLayout_2.addWidget(self.m3name, 0, 0, 1, 1)
        self.MonitorPort3 = PortCombo(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort3.sizePolicy().hasHeightForWidth())
        self.MonitorPort3.setSizePolicy(sizePolicy)
        self.MonitorPort3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort3.setObjectName("MonitorPort3")
        self.MonitorPort3.addItem("")
        self.gridLayout_2.addWidget(self.MonitorPort3, 0, 1, 1, 2)
        self.MonitorColor3 = ColorCombo(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor3.sizePolicy().hasHeightForWidth())
        self.MonitorColor3.setSizePolicy(sizePolicy)
        self.MonitorColor3.setAcceptDrops(False)
        self.MonitorColor3.setFrame(True)
        self.MonitorColor3.setObjectName("MonitorColor3")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.MonitorColor3.addItem("")
        self.gridLayout_2.addWidget(self.MonitorColor3, 1, 0, 1, 1)
        self.MonitorFormat3 = FormatCombo(self.frame_3)
        self.MonitorFormat3.setObjectName("MonitorFormat3")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.MonitorFormat3.addItem("")
        self.gridLayout_2.addWidget(self.MonitorFormat3, 1, 1, 1, 1)
        self.MonitorBaud3 = BaudCombo(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud3.sizePolicy().hasHeightForWidth())
        self.MonitorBaud3.setSizePolicy(sizePolicy)
        self.MonitorBaud3.setAcceptDrops(False)
        self.MonitorBaud3.setFrame(True)
        self.MonitorBaud3.setObjectName("MonitorBaud3")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.MonitorBaud3.addItem("")
        self.gridLayout_2.addWidget(self.MonitorBaud3, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = MonitorFrame(self.PortMonitors)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.m4name = QtWidgets.QLineEdit(self.frame_4)
        self.m4name.setStyleSheet("background-color: palette(window);")
        self.m4name.setObjectName("m4name")
        self.gridLayout.addWidget(self.m4name, 0, 0, 1, 1)
        self.MonitorPort4 = PortCombo(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorPort4.sizePolicy().hasHeightForWidth())
        self.MonitorPort4.setSizePolicy(sizePolicy)
        self.MonitorPort4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.MonitorPort4.setObjectName("MonitorPort4")
        self.MonitorPort4.addItem("")
        self.gridLayout.addWidget(self.MonitorPort4, 0, 1, 1, 2)
        self.MonitorColor4 = ColorCombo(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorColor4.sizePolicy().hasHeightForWidth())
        self.MonitorColor4.setSizePolicy(sizePolicy)
        self.MonitorColor4.setAcceptDrops(False)
        self.MonitorColor4.setFrame(True)
        self.MonitorColor4.setObjectName("MonitorColor4")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.MonitorColor4.addItem("")
        self.gridLayout.addWidget(self.MonitorColor4, 1, 0, 1, 1)
        self.MonitorFormat4 = FormatCombo(self.frame_4)
        self.MonitorFormat4.setObjectName("MonitorFormat4")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.MonitorFormat4.addItem("")
        self.gridLayout.addWidget(self.MonitorFormat4, 1, 1, 1, 1)
        self.MonitorBaud4 = BaudCombo(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MonitorBaud4.sizePolicy().hasHeightForWidth())
        self.MonitorBaud4.setSizePolicy(sizePolicy)
        self.MonitorBaud4.setAcceptDrops(False)
        self.MonitorBaud4.setFrame(True)
        self.MonitorBaud4.setObjectName("MonitorBaud4")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.MonitorBaud4.addItem("")
        self.gridLayout.addWidget(self.MonitorBaud4, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.line = QtWidgets.QFrame(self.PortMonitors)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.PortMonitors)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.SavePortMonitor = QtWidgets.QPushButton(self.PortMonitors)
        self.SavePortMonitor.setObjectName("SavePortMonitor")
        self.horizontalLayout_5.addWidget(self.SavePortMonitor)
        self.LoadPortMonitor = QtWidgets.QPushButton(self.PortMonitors)
        self.LoadPortMonitor.setObjectName("LoadPortMonitor")
        self.horizontalLayout_5.addWidget(self.LoadPortMonitor)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.PortMonitors, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.Console = QtWidgets.QPlainTextEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Console.sizePolicy().hasHeightForWidth())
        self.Console.setSizePolicy(sizePolicy)
        self.Console.setMinimumSize(QtCore.QSize(600, 470))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Console.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.Console.setFont(font)
        self.Console.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Console.setStyleSheet("")
        self.Console.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Console.setUndoRedoEnabled(False)
        self.Console.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.Console.setPlainText("")
        self.Console.setObjectName("Console")
        self.verticalLayout.addWidget(self.Console)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(1)
        self.ConsoleColor.setCurrentIndex(1)
        self.ConsoleProtocol.setCurrentIndex(2)
        self.BaudRate.setCurrentIndex(6)
        self.MonitorPort1.setCurrentIndex(0)
        self.MonitorColor1.setCurrentIndex(4)
        self.MonitorBaud1.setCurrentIndex(6)
        self.MonitorColor2.setCurrentIndex(5)
        self.MonitorBaud2.setCurrentIndex(6)
        self.MonitorColor3.setCurrentIndex(0)
        self.MonitorBaud3.setCurrentIndex(6)
        self.MonitorColor4.setCurrentIndex(2)
        self.MonitorBaud4.setCurrentIndex(6)
        self.pushButton.released.connect(self.Console.clear)
        self.m1name.textChanged['QString'].connect(self.m1name.repaint)
        self.m2name.textChanged['QString'].connect(self.m2name.repaint)
        self.m3name.textChanged['QString'].connect(self.m3name.repaint)
        self.m4name.textChanged['QString'].connect(self.m4name.repaint)
        self.MonitorBaud1.currentTextChanged['QString'].connect(self.MonitorBaud1.repaint)
        self.MonitorBaud2.currentTextChanged['QString'].connect(self.MonitorBaud2.repaint)
        self.MonitorBaud3.currentTextChanged['QString'].connect(self.MonitorBaud3.repaint)
        self.MonitorBaud4.currentTextChanged['QString'].connect(self.MonitorBaud4.repaint)
        self.MonitorFormat4.currentTextChanged['QString'].connect(self.MonitorFormat4.repaint)
        self.MonitorFormat3.currentTextChanged['QString'].connect(self.MonitorFormat3.repaint)
        self.MonitorFormat2.currentTextChanged['QString'].connect(self.MonitorFormat2.repaint)
        self.MonitorFormat1.currentTextChanged['QString'].connect(self.MonitorFormat1.repaint)
        self.MonitorColor1.currentTextChanged['QString'].connect(self.MonitorColor1.repaint)
        self.MonitorColor2.currentTextChanged['QString'].connect(self.MonitorColor2.repaint)
        self.MonitorColor3.currentTextChanged['QString'].connect(self.MonitorColor3.repaint)
        self.MonitorColor4.currentTextChanged['QString'].connect(self.MonitorColor4.repaint)
        self.MonitorPort2.currentTextChanged['QString'].connect(self.MonitorPort2.repaint)
        self.MonitorPort3.currentTextChanged['QString'].connect(self.MonitorPort3.repaint)
        self.MonitorPort4.currentTextChanged['QString'].connect(self.MonitorPort4.repaint)
        self.MonitorPort1.currentTextChanged['QString'].connect(self.MonitorPort1.repaint)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.groupBox_8.setTitle(_translate("Frame", "Port"))
        self.PortSelect.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.ConsoleColor.setCurrentText(_translate("Frame", "cyan"))
        self.ConsoleColor.setItemText(0, _translate("Frame", "white"))
        self.ConsoleColor.setItemText(1, _translate("Frame", "cyan"))
        self.ConsoleColor.setItemText(2, _translate("Frame", "blue"))
        self.ConsoleColor.setItemText(3, _translate("Frame", "green"))
        self.ConsoleColor.setItemText(4, _translate("Frame", "yellow"))
        self.ConsoleColor.setItemText(5, _translate("Frame", "orange"))
        self.ConsoleColor.setItemText(6, _translate("Frame", "magenta"))
        self.ConsoleColor.setItemText(7, _translate("Frame", "red"))
        self.ConsoleProtocol.setItemText(0, _translate("Frame", "ASCII"))
        self.ConsoleProtocol.setItemText(1, _translate("Frame", "Hex"))
        self.ConsoleProtocol.setItemText(2, _translate("Frame", "SFP"))
        self.ConsoleProtocol.setItemText(3, _translate("Frame", "Alert2 IND"))
        self.BaudRate.setItemText(0, _translate("Frame", "1200"))
        self.BaudRate.setItemText(1, _translate("Frame", "9600"))
        self.BaudRate.setItemText(2, _translate("Frame", "19200"))
        self.BaudRate.setItemText(3, _translate("Frame", "28800"))
        self.BaudRate.setItemText(4, _translate("Frame", "38400"))
        self.BaudRate.setItemText(5, _translate("Frame", "57600"))
        self.BaudRate.setItemText(6, _translate("Frame", "115200"))
        self.BaudRate.setItemText(7, _translate("Frame", "230400"))
        self.BaudRate.setItemText(8, _translate("Frame", "460800"))
        self.BaudRate.setItemText(9, _translate("Frame", "500000"))
        self.BaudRate.setItemText(10, _translate("Frame", "921600"))
        self.groupBox_6.setTitle(_translate("Frame", "Protocol"))
        self.label_5.setText(_translate("Frame", "From:"))
        self.label_4.setText(_translate("Frame", "To:"))
        self.whoFrom.setSpecialValueText(_translate("Frame", "0"))
        self.groupBox_7.setTitle(_translate("Frame", "Tools"))
        self.ProtocolDump.setText(_translate("Frame", "Protocol Dump"))
        self.LoopBack.setText(_translate("Frame", "Loop back"))
        self.ignoreUnknowns.setText(_translate("Frame", "Ignore Unknowns"))
        self.Ping.setText(_translate("Frame", "Ping"))
        self.ResetRcvr.setText(_translate("Frame", "Reset Receiver"))
        self.pushButton.setText(_translate("Frame", "Clear Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Frame", "Console"))
        self.m1name.setText(_translate("Frame", "M1"))
        self.MonitorPort1.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorColor1.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor1.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor1.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor1.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor1.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor1.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor1.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor1.setItemText(7, _translate("Frame", "red"))
        self.MonitorFormat1.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat1.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat1.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat1.setItemText(3, _translate("Frame", "ALERT2 IND"))
        self.MonitorFormat1.setItemText(4, _translate("Frame", "AirLink PDU"))
        self.MonitorBaud1.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud1.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud1.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud1.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud1.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud1.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud1.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud1.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud1.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud1.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud1.setItemText(10, _translate("Frame", "921600"))
        self.m2name.setText(_translate("Frame", "M2"))
        self.MonitorPort2.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorColor2.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor2.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor2.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor2.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor2.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor2.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor2.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor2.setItemText(7, _translate("Frame", "red"))
        self.MonitorFormat2.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat2.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat2.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat2.setItemText(3, _translate("Frame", "ALERT2 IND"))
        self.MonitorFormat2.setItemText(4, _translate("Frame", "AirLink PDU"))
        self.MonitorBaud2.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud2.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud2.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud2.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud2.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud2.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud2.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud2.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud2.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud2.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud2.setItemText(10, _translate("Frame", "921600"))
        self.m3name.setText(_translate("Frame", "M3"))
        self.MonitorPort3.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorColor3.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor3.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor3.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor3.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor3.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor3.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor3.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor3.setItemText(7, _translate("Frame", "red"))
        self.MonitorFormat3.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat3.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat3.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat3.setItemText(3, _translate("Frame", "ALERT2 IND"))
        self.MonitorFormat3.setItemText(4, _translate("Frame", "AirLink PDU"))
        self.MonitorBaud3.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud3.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud3.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud3.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud3.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud3.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud3.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud3.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud3.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud3.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud3.setItemText(10, _translate("Frame", "921600"))
        self.m4name.setText(_translate("Frame", "M4"))
        self.MonitorPort4.setItemText(0, _translate("Frame", "(Select a Port)"))
        self.MonitorColor4.setItemText(0, _translate("Frame", "white"))
        self.MonitorColor4.setItemText(1, _translate("Frame", "cyan"))
        self.MonitorColor4.setItemText(2, _translate("Frame", "blue"))
        self.MonitorColor4.setItemText(3, _translate("Frame", "green"))
        self.MonitorColor4.setItemText(4, _translate("Frame", "yellow"))
        self.MonitorColor4.setItemText(5, _translate("Frame", "orange"))
        self.MonitorColor4.setItemText(6, _translate("Frame", "magenta"))
        self.MonitorColor4.setItemText(7, _translate("Frame", "red"))
        self.MonitorFormat4.setItemText(0, _translate("Frame", "ASCII"))
        self.MonitorFormat4.setItemText(1, _translate("Frame", "Hex"))
        self.MonitorFormat4.setItemText(2, _translate("Frame", "SFP"))
        self.MonitorFormat4.setItemText(3, _translate("Frame", "ALERT2 IND"))
        self.MonitorFormat4.setItemText(4, _translate("Frame", "AirLink PDU"))
        self.MonitorBaud4.setItemText(0, _translate("Frame", "1200"))
        self.MonitorBaud4.setItemText(1, _translate("Frame", "9600"))
        self.MonitorBaud4.setItemText(2, _translate("Frame", "19200"))
        self.MonitorBaud4.setItemText(3, _translate("Frame", "28800"))
        self.MonitorBaud4.setItemText(4, _translate("Frame", "38400"))
        self.MonitorBaud4.setItemText(5, _translate("Frame", "57600"))
        self.MonitorBaud4.setItemText(6, _translate("Frame", "115200"))
        self.MonitorBaud4.setItemText(7, _translate("Frame", "230400"))
        self.MonitorBaud4.setItemText(8, _translate("Frame", "460800"))
        self.MonitorBaud4.setItemText(9, _translate("Frame", "500000"))
        self.MonitorBaud4.setItemText(10, _translate("Frame", "921600"))
        self.label.setText(_translate("Frame", "Settings:"))
        self.SavePortMonitor.setText(_translate("Frame", "Save"))
        self.LoadPortMonitor.setText(_translate("Frame", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PortMonitors), _translate("Frame", "Monitor"))
from baudcombo import BaudCombo
from colorcombo import ColorCombo
from formatcombo import FormatCombo
from monitorframe import MonitorFrame
from portcombo import PortCombo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
