# spids
(TRANSFER_REQUEST,	# size in bytes (32 bit), name (count prefixed), type (byte)
TRANSFER_REPLY,		# status (byte)
TRANSFER_DATA,		# data
TRANSFER_RESULT, 	# status
TRANSFER_DONE,		# send checksum
# results
REQUEST_OK, REQUEST_TOOBIG, TRANSFER_BUSY, # from request
TRANSFER_OK, CHECK_ERROR, TRANSFER_INCOMPLETE, UNSUPORTED_TYPE, # from transfer
# types
UNKNOWN, JAM_PLAYER, JBC_PLAYER, TEXT_TRANSFER) = range (0,16)

resultText = {
	REQUEST_OK:'REQUEST_OK',
	REQUEST_TOOBIG:' REQUEST_TOOBIG',
	TRANSFER_BUSY:' TRANSFER_BUSY',
	TRANSFER_OK:' TRANSFER_OK',
	CHECK_ERROR:' CHECK_ERROR',
	TRANSFER_INCOMPLETE:' TRANSFER_INCOMPLETE',
	UNSUPORTED_TYPE:'UNSUPORTED_TYPE'}
