# -*- mode: python -*-
# generated by running tt.py instead of ttmac.spec in buildApp.py; added binaries= stuff in this spec file
block_cipher = None


a = Analysis(['tt.py'],
             pathex=['.', '/Volumes/SharedFolders/robchapm/TimbreWorks/IP/TimbreTalk'],
             binaries=[('/Volumes/SharedFolders/robchapm/TimbreWorks/IP/TimbreTalk/libs/libjlinkarm.dylib', '.')],
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=['rthook_pyqt4.py'],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='tt',
          debug=False,
          strip=False,
          upx=False,
          console=False , icon='timbretalk.icns')
app = BUNDLE(exe,
             name='tt.app',
             icon='timbretalk.icns',
             bundle_identifier='TimbreTalk')
